import { BaseModel } from "../common/base-model";
import { ApId } from "../common/id-generator";

export type FlagId = ApId;

export interface Flag extends BaseModel<FlagId> {
    value: unknown;
}

export enum ApEnvironment {
    PRODUCTION = "prod",
    DEVELOPMENT = "dev",
    TESTING = "test",
}

export enum ApEdition {
    COMMUNITY = "ce",
    ENTERPRISE = "ee",
    CLOUD = "cloud"
}

export enum ApFlagId {
    SANDBOX_RUN_TIME_SECONDS = 'SANDBOX_RUN_TIME_SECONDS',
    FRONTEND_URL = "FRONTEND_URL",
    THEME = "THEME",
    EDITION = "EDITION",
    ENVIRONMENT = "ENVIRONMENT",
    CHATBOT_ENABLED = 'CHATBOT_ENABLED',
    WEBHOOK_URL_PREFIX = "WEBHOOK_URL_PREFIX",
    USER_CREATED = "USER_CREATED",
    SIGN_UP_ENABLED = "SIGN_UP_ENABLED",
    SHOW_COMMUNITY = "SHOW_COMMUNITY",
    SHOW_DOCS = "SHOW_DOCS",
    TELEMETRY_ENABLED = "TELEMETRY_ENABLED",
    CURRENT_VERSION = "CURRENT_VERSION",
    LATEST_VERSION = "LATEST_VERSION",
    CLOUD_AUTH_ENABLED = "CLOUD_AUTH_ENABLED",
    TEMPLATES_SOURCE_URL = "TEMPLATES_SOURCE_URL",
    SHOW_BILLING = 'SHOW_BILLING',
    PROJECT_MEMBERS_ENABLED = "PROJECT_MEMBERS_ENABLED",
    TEMPLATES_PROJECT_ID = "TEMPLATES_PROJECT_ID",
    PRIVATE_PIECES_ENABLED = "PRIVATE_PIECES_ENABLED",
    SHOW_AUTH_PROVIDERS = "SHOW_AUTH_PROVIDERS",
    SHOW_BLOG_GUIDE = "SHOW_BLOG_GUIDE",
}
