events {
    worker_connections 1024;
}

http {
    upstream app_backend {
        server app:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 900s;
            proxy_send_timeout 900s;
            proxy_buffering off;
            proxy_cache off;
        }
    }
}
