import { newCall, newCallDefinition } from './native/new-call';
import { phoneCallEnded, phoneCallEndedDefinition } from './native/phone-call-ended';
import { inboundCall, inboundCallDefinition } from './native/inbound-call';
import { newOutboundCall, newOutboundCallDefinition } from './native/new-outbound-call';
import { newWebCall, newWebCallDefinition } from './native/new-web-call';
import { callFailed, callFailedDefinition } from './native/call-failed';
import { callNotAnswered, callNotAnsweredDefinition } from './native/call-not-answered';
import { getAssistants, getAssistantsDefinition } from './native/get-assistants';
import { newContact, newContactDefinition } from './native/new-contact';
import { newCampaign, newCampaignDefinition } from './native/new-campaign';
import { campaignStarted, campaignStartedDefinition } from './native/campaign-started';
import { campaignPaused, campaignPausedDefinition } from './native/campaign-paused';
import { campaignCompleted, campaignCompletedDefinition } from './native/campaign-completed';
import { newCampaignLead, newCampaignLeadDefinition } from './native/new-campaign-lead';
import { campaignLeadCompleted, campaignLeadCompletedDefinition } from './native/campaign-lead-completed';
import { conversationEnded, conversationEndedDefinition } from './native/conversation-ended';
import { newHistoryActivity, newHistoryActivityDefinition } from './native/new-history-activity';
import { newEmailActivity, newEmailActivityDefinition } from './native/new-email-activity';
import { newWhatsAppActivity, newWhatsAppActivityDefinition } from './native/new-whats-app-activity';
import { newPhoneNumber, newPhoneNumberDefinition } from './native/new-phone-number';
import { newKnowledgeBase, newKnowledgeBaseDefinition } from './native/new-knowledge-base';
import { newBooking, newBookingDefinition } from './native/new-booking';
import { bookingCancelled, bookingCancelledDefinition } from './native/booking-cancelled';
import { bookingCompleted, bookingCompletedDefinition } from './native/booking-completed';
import { newBookingEventType, newBookingEventTypeDefinition } from './native/new-booking-event-type';
import { newScheduledCallback, newScheduledCallbackDefinition } from './native/new-scheduled-callback';
import { callbackCompleted, callbackCompletedDefinition } from './native/callback-completed';
import { newTool, newToolDefinition } from './native/new-tool';
import { newAutomation, newAutomationDefinition } from './native/new-automation';
import { newMission, newMissionDefinition } from './native/new-mission';
import { newSegment, newSegmentDefinition } from './native/new-segment';
import { newSuppressionEntry, newSuppressionEntryDefinition } from './native/new-suppression-entry';

export const pollingDefinitions = [newCallDefinition, phoneCallEndedDefinition, inboundCallDefinition, newOutboundCallDefinition, newWebCallDefinition, callFailedDefinition, callNotAnsweredDefinition, getAssistantsDefinition, newContactDefinition, newCampaignDefinition, campaignStartedDefinition, campaignPausedDefinition, campaignCompletedDefinition, newCampaignLeadDefinition, campaignLeadCompletedDefinition, conversationEndedDefinition, newHistoryActivityDefinition, newEmailActivityDefinition, newWhatsAppActivityDefinition, newPhoneNumberDefinition, newKnowledgeBaseDefinition, newBookingDefinition, bookingCancelledDefinition, bookingCompletedDefinition, newBookingEventTypeDefinition, newScheduledCallbackDefinition, callbackCompletedDefinition, newToolDefinition, newAutomationDefinition, newMissionDefinition, newSegmentDefinition, newSuppressionEntryDefinition];
export const pollingTriggers = [newCall, phoneCallEnded, inboundCall, newOutboundCall, newWebCall, callFailed, callNotAnswered, getAssistants, newContact, newCampaign, campaignStarted, campaignPaused, campaignCompleted, newCampaignLead, campaignLeadCompleted, conversationEnded, newHistoryActivity, newEmailActivity, newWhatsAppActivity, newPhoneNumber, newKnowledgeBase, newBooking, bookingCancelled, bookingCompleted, newBookingEventType, newScheduledCallback, callbackCompleted, newTool, newAutomation, newMission, newSegment, newSuppressionEntry];
export { famulorPolling } from '../common/polling';
