export enum SystemProp {
  BACKEND_URL = "BACKEND_URL",
  ENGINE_EXECUTABLE_PATH = "ENGINE_EXECUTABLE_PATH",
  FRONTEND_URL = "FRONTEND_URL",
  JWT_SECRET = "JWT_SECRET",
  TELEMETRY_ENABLED = "TELEMETRY_ENABLED",
  SIGN_UP_ENABLED = "SIGN_UP_ENABLED",
  NODE_EXECUTABLE_PATH = "NODE_EXECUTABLE_PATH",

  POSTGRES_DATABASE = "POSTGRES_DATABASE",
  POSTGRES_HOST = "POSTGRES_HOST",
  POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
  POSTGRES_PORT = "POSTGRES_PORT",
  POSTGRES_USERNAME = "POSTGRES_USERNAME",
  POSTGRES_USE_SSL = "POSTGRES_USE_SSL",
  POSTGRES_SSL_CA = "POSTGRES_SSL_CA",

  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",
  REDIS_USER = "REDIS_USER",
  REDIS_PASSWORD = "REDIS_PASSWORD",
  REDIS_USE_SSL = "REDIS_USE_SSL",
  
  WARNING_TEXT_BODY = "WARNING_TEXT_BODY",
  WARNING_TEXT_HEADER = "WARNING_TEXT_HEADER",
}
