export const COUNTRY_OPTIONS = [
  { label: 'us (United States)', value: 'us' },
  { label: 'af (Afghanistan)', value: 'af' },
  { label: 'al (Albania)', value: 'al' },
  { label: 'dz (Algeria)', value: 'dz' },
  { label: 'as (American Samoa)', value: 'as' },
  { label: 'ad (Andorra)', value: 'ad' },
  { label: 'ao (Angola)', value: 'ao' },
  { label: 'ai (Anguilla)', value: 'ai' },
  { label: 'aq (Antarctica)', value: 'aq' },
  { label: 'ag (Antigua and Barbuda)', value: 'ag' },
  { label: 'ar (Argentina)', value: 'ar' },
  { label: 'am (Armenia)', value: 'am' },
  { label: 'aw (Aruba)', value: 'aw' },
  { label: 'au (Australia)', value: 'au' },
  { label: 'at (Austria)', value: 'at' },
  { label: 'az (Azerbaijan)', value: 'az' },
  { label: 'bs (Bahamas)', value: 'bs' },
  { label: 'bh (Bahrain)', value: 'bh' },
  { label: 'bd (Bangladesh)', value: 'bd' },
  { label: 'bb (Barbados)', value: 'bb' },
  { label: 'by (Belarus)', value: 'by' },
  { label: 'be (Belgium)', value: 'be' },
  { label: 'bz (Belize)', value: 'bz' },
  { label: 'bj (Benin)', value: 'bj' },
  { label: 'bm (Bermuda)', value: 'bm' },
  { label: 'bt (Bhutan)', value: 'bt' },
  { label: 'bo (Bolivia)', value: 'bo' },
  { label: 'ba (Bosnia and Herzegovina)', value: 'ba' },
  { label: 'bw (Botswana)', value: 'bw' },
  { label: 'bv (Bouvet Island)', value: 'bv' },
  { label: 'br (Brazil)', value: 'br' },
  { label: 'io (British Indian Ocean Territory)', value: 'io' },
  { label: 'bn (Brunei Darussalam)', value: 'bn' },
  { label: 'bg (Bulgaria)', value: 'bg' },
  { label: 'bf (Burkina Faso)', value: 'bf' },
  { label: 'bi (Burundi)', value: 'bi' },
  { label: 'kh (Cambodia)', value: 'kh' },
  { label: 'cm (Cameroon)', value: 'cm' },
  { label: 'ca (Canada)', value: 'ca' },
  { label: 'cv (Cape Verde)', value: 'cv' },
  { label: 'ky (Cayman Islands)', value: 'ky' },
  { label: 'cf (Central African Republic)', value: 'cf' },
  { label: 'td (Chad)', value: 'td' },
  { label: 'cl (Chile)', value: 'cl' },
  { label: 'cn (China)', value: 'cn' },
  { label: 'cx (Christmas Island)', value: 'cx' },
  { label: 'cc (Cocos (Keeling) Islands)', value: 'cc' },
  { label: 'co (Colombia)', value: 'co' },
  { label: 'km (Comoros)', value: 'km' },
  { label: 'cg (Congo)', value: 'cg' },
  { label: 'cd (Congo, the Democratic Republic of the)', value: 'cd' },
  { label: 'ck (Cook Islands)', value: 'ck' },
  { label: 'cr (Costa Rica)', value: 'cr' },
  { label: 'ci (Cote D\'ivoire)', value: 'ci' },
  { label: 'hr (Croatia)', value: 'hr' },
  { label: 'cu (Cuba)', value: 'cu' },
  { label: 'cy (Cyprus)', value: 'cy' },
  { label: 'cz (Czech Republic)', value: 'cz' },
  { label: 'dk (Denmark)', value: 'dk' },
  { label: 'dj (Djibouti)', value: 'dj' },
  { label: 'dm (Dominica)', value: 'dm' },
  { label: 'do (Dominican Republic)', value: 'do' },
  { label: 'ec (Ecuador)', value: 'ec' },
  { label: 'eg (Egypt)', value: 'eg' },
  { label: 'sv (El Salvador)', value: 'sv' },
  { label: 'gq (Equatorial Guinea)', value: 'gq' },
  { label: 'er (Eritrea)', value: 'er' },
  { label: 'ee (Estonia)', value: 'ee' },
  { label: 'et (Ethiopia)', value: 'et' },
  { label: 'fk (Falkland Islands (Malvinas))', value: 'fk' },
  { label: 'fo (Faroe Islands)', value: 'fo' },
  { label: 'fj (Fiji)', value: 'fj' },
  { label: 'fi (Finland)', value: 'fi' },
  { label: 'fr (France)', value: 'fr' },
  { label: 'gf (French Guiana)', value: 'gf' },
  { label: 'pf (French Polynesia)', value: 'pf' },
  { label: 'tf (French Southern Territories)', value: 'tf' },
  { label: 'ga (Gabon)', value: 'ga' },
  { label: 'gm (Gambia)', value: 'gm' },
  { label: 'ge (Georgia)', value: 'ge' },
  { label: 'de (Germany)', value: 'de' },
  { label: 'gh (Ghana)', value: 'gh' },
  { label: 'gi (Gibraltar)', value: 'gi' },
  { label: 'gr (Greece)', value: 'gr' },
  { label: 'gl (Greenland)', value: 'gl' },
  { label: 'gd (Grenada)', value: 'gd' },
  { label: 'gp (Guadeloupe)', value: 'gp' },
  { label: 'gu (Guam)', value: 'gu' },
  { label: 'gt (Guatemala)', value: 'gt' },
  { label: 'gg (Guernsey)', value: 'gg' },
  { label: 'gn (Guinea)', value: 'gn' },
  { label: 'gw (Guinea-Bissau)', value: 'gw' },
  { label: 'gy (Guyana)', value: 'gy' },
  { label: 'ht (Haiti)', value: 'ht' },
  { label: 'hm (Heard Island and Mcdonald Islands)', value: 'hm' },
  { label: 'va (Holy See (Vatican City State))', value: 'va' },
  { label: 'hn (Honduras)', value: 'hn' },
  { label: 'hk (Hong Kong)', value: 'hk' },
  { label: 'hu (Hungary)', value: 'hu' },
  { label: 'is (Iceland)', value: 'is' },
  { label: 'in (India)', value: 'in' },
  { label: 'id (Indonesia)', value: 'id' },
  { label: 'ir (Iran, Islamic Republic of)', value: 'ir' },
  { label: 'iq (Iraq)', value: 'iq' },
  { label: 'ie (Ireland)', value: 'ie' },
  { label: 'im (Isle of Man)', value: 'im' },
  { label: 'il (Israel)', value: 'il' },
  { label: 'it (Italy)', value: 'it' },
  { label: 'je (Jersey)', value: 'je' },
  { label: 'jm (Jamaica)', value: 'jm' },
  { label: 'jp (Japan)', value: 'jp' },
  { label: 'jo (Jordan)', value: 'jo' },
  { label: 'kz (Kazakhstan)', value: 'kz' },
  { label: 'ke (Kenya)', value: 'ke' },
  { label: 'ki (Kiribati)', value: 'ki' },
  { label: 'kp (Korea, Democratic People\'s Republic of)', value: 'kp' },
  { label: 'kr (Korea, Republic of)', value: 'kr' },
  { label: 'kw (Kuwait)', value: 'kw' },
  { label: 'kg (Kyrgyzstan)', value: 'kg' },
  { label: 'la (Lao People\'s Democratic Republic)', value: 'la' },
  { label: 'lv (Latvia)', value: 'lv' },
  { label: 'lb (Lebanon)', value: 'lb' },
  { label: 'ls (Lesotho)', value: 'ls' },
  { label: 'lr (Liberia)', value: 'lr' },
  { label: 'ly (Libyan Arab Jamahiriya)', value: 'ly' },
  { label: 'li (Liechtenstein)', value: 'li' },
  { label: 'lt (Lithuania)', value: 'lt' },
  { label: 'lu (Luxembourg)', value: 'lu' },
  { label: 'mo (Macao)', value: 'mo' },
  { label: 'mk (Macedonia, the Former Yugosalv Republic of)', value: 'mk' },
  { label: 'mg (Madagascar)', value: 'mg' },
  { label: 'mw (Malawi)', value: 'mw' },
  { label: 'my (Malaysia)', value: 'my' },
  { label: 'mv (Maldives)', value: 'mv' },
  { label: 'ml (Mali)', value: 'ml' },
  { label: 'mt (Malta)', value: 'mt' },
  { label: 'mh (Marshall Islands)', value: 'mh' },
  { label: 'mq (Martinique)', value: 'mq' },
  { label: 'mr (Mauritania)', value: 'mr' },
  { label: 'mu (Mauritius)', value: 'mu' },
  { label: 'yt (Mayotte)', value: 'yt' },
  { label: 'mx (Mexico)', value: 'mx' },
  { label: 'fm (Micronesia, Federated States of)', value: 'fm' },
  { label: 'md (Moldova, Republic of)', value: 'md' },
  { label: 'mc (Monaco)', value: 'mc' },
  { label: 'mn (Mongolia)', value: 'mn' },
  { label: 'me (Montenegro)', value: 'me' },
  { label: 'ms (Montserrat)', value: 'ms' },
  { label: 'ma (Morocco)', value: 'ma' },
  { label: 'mz (Mozambique)', value: 'mz' },
  { label: 'mm (Myanmar)', value: 'mm' },
  { label: 'na (Namibia)', value: 'na' },
  { label: 'nr (Nauru)', value: 'nr' },
  { label: 'np (Nepal)', value: 'np' },
  { label: 'nl (Netherlands)', value: 'nl' },
  { label: 'an (Netherlands Antilles)', value: 'an' },
  { label: 'nc (New Caledonia)', value: 'nc' },
  { label: 'nz (New Zealand)', value: 'nz' },
  { label: 'ni (Nicaragua)', value: 'ni' },
  { label: 'ne (Niger)', value: 'ne' },
  { label: 'ng (Nigeria)', value: 'ng' },
  { label: 'nu (Niue)', value: 'nu' },
  { label: 'nf (Norfolk Island)', value: 'nf' },
  { label: 'mp (Northern Mariana Islands)', value: 'mp' },
  { label: 'no (Norway)', value: 'no' },
  { label: 'om (Oman)', value: 'om' },
  { label: 'pk (Pakistan)', value: 'pk' },
  { label: 'pw (Palau)', value: 'pw' },
  { label: 'ps (Palestinian Territory, Occupied)', value: 'ps' },
  { label: 'pa (Panama)', value: 'pa' },
  { label: 'pg (Papua New Guinea)', value: 'pg' },
  { label: 'py (Paraguay)', value: 'py' },
  { label: 'pe (Peru)', value: 'pe' },
  { label: 'ph (Philippines)', value: 'ph' },
  { label: 'pn (Pitcairn)', value: 'pn' },
  { label: 'pl (Poland)', value: 'pl' },
  { label: 'pt (Portugal)', value: 'pt' },
  { label: 'pr (Puerto Rico)', value: 'pr' },
  { label: 'qa (Qatar)', value: 'qa' },
  { label: 're (Reunion)', value: 're' },
  { label: 'ro (Romania)', value: 'ro' },
  { label: 'ru (Russian Federation)', value: 'ru' },
  { label: 'rw (Rwanda)', value: 'rw' },
  { label: 'sh (Saint Helena)', value: 'sh' },
  { label: 'kn (Saint Kitts and Nevis)', value: 'kn' },
  { label: 'lc (Saint Lucia)', value: 'lc' },
  { label: 'pm (Saint Pierre and Miquelon)', value: 'pm' },
  { label: 'vc (Saint Vincent and the Grenadines)', value: 'vc' },
  { label: 'ws (Samoa)', value: 'ws' },
  { label: 'sm (San Marino)', value: 'sm' },
  { label: 'st (Sao Tome and Principe)', value: 'st' },
  { label: 'sa (Saudi Arabia)', value: 'sa' },
  { label: 'sn (Senegal)', value: 'sn' },
  { label: 'rs (Serbia)', value: 'rs' },
  { label: 'sc (Seychelles)', value: 'sc' },
  { label: 'sl (Sierra Leone)', value: 'sl' },
  { label: 'sg (Singapore)', value: 'sg' },
  { label: 'sk (Slovakia)', value: 'sk' },
  { label: 'si (Slovenia)', value: 'si' },
  { label: 'sb (Solomon Islands)', value: 'sb' },
  { label: 'so (Somalia)', value: 'so' },
  { label: 'za (South Africa)', value: 'za' },
  { label: 'gs (South Georgia and the South Sandwich Islands)', value: 'gs' },
  { label: 'es (Spain)', value: 'es' },
  { label: 'lk (Sri Lanka)', value: 'lk' },
  { label: 'sd (Sudan)', value: 'sd' },
  { label: 'sr (Suriname)', value: 'sr' },
  { label: 'sj (Svalbard and Jan Mayen)', value: 'sj' },
  { label: 'sz (Swaziland)', value: 'sz' },
  { label: 'se (Sweden)', value: 'se' },
  { label: 'ch (Switzerland)', value: 'ch' },
  { label: 'sy (Syrian Arab Republic)', value: 'sy' },
  { label: 'tw (Taiwan, Province of China)', value: 'tw' },
  { label: 'tj (Tajikistan)', value: 'tj' },
  { label: 'tz (Tanzania, United Republic of)', value: 'tz' },
  { label: 'th (Thailand)', value: 'th' },
  { label: 'tl (Timor-Leste)', value: 'tl' },
  { label: 'tg (Togo)', value: 'tg' },
  { label: 'tk (Tokelau)', value: 'tk' },
  { label: 'to (Tonga)', value: 'to' },
  { label: 'tt (Trinidad and Tobago)', value: 'tt' },
  { label: 'tn (Tunisia)', value: 'tn' },
  { label: 'tr (Turkiye)', value: 'tr' },
  { label: 'tm (Turkmenistan)', value: 'tm' },
  { label: 'tc (Turks and Caicos Islands)', value: 'tc' },
  { label: 'tv (Tuvalu)', value: 'tv' },
  { label: 'ug (Uganda)', value: 'ug' },
  { label: 'ua (Ukraine)', value: 'ua' },
  { label: 'ae (United Arab Emirates)', value: 'ae' },
  { label: 'uk (United Kingdom)', value: 'uk' },
  { label: 'gb (United Kingdom)', value: 'gb' },
  { label: 'um (United States Minor Outlying Islands)', value: 'um' },
  { label: 'uy (Uruguay)', value: 'uy' },
  { label: 'uz (Uzbekistan)', value: 'uz' },
  { label: 'vu (Vanuatu)', value: 'vu' },
  { label: 've (Venezuela)', value: 've' },
  { label: 'vn (Viet Nam)', value: 'vn' },
  { label: 'vg (Virgin Islands, British)', value: 'vg' },
  { label: 'vi (Virgin Islands, U.S.)', value: 'vi' },
  { label: 'wf (Wallis and Futuna)', value: 'wf' },
  { label: 'eh (Western Sahara)', value: 'eh' },
  { label: 'ye (Yemen)', value: 'ye' },
  { label: 'zm (Zambia)', value: 'zm' },
  { label: 'zw (Zimbabwe)', value: 'zw' },
];