export const GOOGLE_DOMAIN_OPTIONS = [
  { label: 'google.com (United States)', value: 'google.com' },
  { label: 'google.ad (Andorra)', value: 'google.ad' },
  { label: 'google.ae (United Arab Emirates)', value: 'google.ae' },
  { label: 'google.al (Albania)', value: 'google.al' },
  { label: 'google.am (Armenia)', value: 'google.am' },
  { label: 'google.as (American Samoa)', value: 'google.as' },
  { label: 'google.at (Austria)', value: 'google.at' },
  { label: 'google.az (Azerbaijan)', value: 'google.az' },
  { label: 'google.ba (Bosnia and Herzegovina)', value: 'google.ba' },
  { label: 'google.be (Belgium)', value: 'google.be' },
  { label: 'google.bf (Burkina Faso)', value: 'google.bf' },
  { label: 'google.bg (Bulgaria)', value: 'google.bg' },
  { label: 'google.bi (Burundi)', value: 'google.bi' },
  { label: 'google.bj (Benin)', value: 'google.bj' },
  { label: 'google.bs (Bahamas)', value: 'google.bs' },
  { label: 'google.bt (Bhutan)', value: 'google.bt' },
  { label: 'google.by (Belarus)', value: 'google.by' },
  { label: 'google.ca (Canada)', value: 'google.ca' },
  { label: 'google.cd (Democratic Republic of the Congo)', value: 'google.cd' },
  { label: 'google.cf (Central African Republic)', value: 'google.cf' },
  { label: 'google.cg (Republic of the Congo)', value: 'google.cg' },
  { label: 'google.ch (Switzerland)', value: 'google.ch' },
  { label: 'google.ci (Ivory Coast)', value: 'google.ci' },
  { label: 'google.cl (Chile)', value: 'google.cl' },
  { label: 'google.cm (Cameroon)', value: 'google.cm' },
  { label: 'google.co.ao (Angola)', value: 'google.co.ao' },
  { label: 'google.co.bw (Botswana)', value: 'google.co.bw' },
  { label: 'google.co.ck (Cook Islands)', value: 'google.co.ck' },
  { label: 'google.co.cr (Costa Rica)', value: 'google.co.cr' },
  { label: 'google.co.id (Indonesia)', value: 'google.co.id' },
  { label: 'google.co.il (Israel)', value: 'google.co.il' },
  { label: 'google.co.in (India)', value: 'google.co.in' },
  { label: 'google.co.jp (Japan)', value: 'google.co.jp' },
  { label: 'google.co.ke (Kenya)', value: 'google.co.ke' },
  { label: 'google.co.kr (South Korea)', value: 'google.co.kr' },
  { label: 'google.co.ls (Lesotho)', value: 'google.co.ls' },
  { label: 'google.co.ma (Morocco)', value: 'google.co.ma' },
  { label: 'google.co.mz (Mozambique)', value: 'google.co.mz' },
  { label: 'google.co.nz (New Zealand)', value: 'google.co.nz' },
  { label: 'google.co.th (Thailand)', value: 'google.co.th' },
  { label: 'google.co.tz (Tanzania)', value: 'google.co.tz' },
  { label: 'google.co.ug (Uganda)', value: 'google.co.ug' },
  { label: 'google.co.uk (United Kingdom)', value: 'google.co.uk' },
  { label: 'google.co.uz (Uzbekistan)', value: 'google.co.uz' },
  { label: 'google.co.ve (Venezuela)', value: 'google.co.ve' },
  { label: 'google.co.vi (United States Virgin Islands)', value: 'google.co.vi' },
  { label: 'google.co.za (South Africa)', value: 'google.co.za' },
  { label: 'google.co.zm (Zambia)', value: 'google.co.zm' },
  { label: 'google.co.zw (Zimbabwe)', value: 'google.co.zw' },
  { label: 'google.com.af (Afghanistan)', value: 'google.com.af' },
  { label: 'google.com.ag (Antigua and Barbuda)', value: 'google.com.ag' },
  { label: 'google.com.ai (Anguilla)', value: 'google.com.ai' },
  { label: 'google.com.ar (Argentina)', value: 'google.com.ar' },
  { label: 'google.com.au (Australia)', value: 'google.com.au' },
  { label: 'google.com.bd (Bangladesh)', value: 'google.com.bd' },
  { label: 'google.com.bh (Bahrain)', value: 'google.com.bh' },
  { label: 'google.com.bn (Brunei)', value: 'google.com.bn' },
  { label: 'google.com.bo (Bolivia)', value: 'google.com.bo' },
  { label: 'google.com.br (Brazil)', value: 'google.com.br' },
  { label: 'google.com.bz (Belize)', value: 'google.com.bz' },
  { label: 'google.com.co (Colombia)', value: 'google.com.co' },
  { label: 'google.com.cu (Cuba)', value: 'google.com.cu' },
  { label: 'google.com.cy (Cyprus)', value: 'google.com.cy' },
  { label: 'google.com.do (Dominican Republic)', value: 'google.com.do' },
  { label: 'google.com.ec (Ecuador)', value: 'google.com.ec' },
  { label: 'google.com.eg (Egypt)', value: 'google.com.eg' },
  { label: 'google.com.et (Ethiopia)', value: 'google.com.et' },
  { label: 'google.com.fj (Fiji)', value: 'google.com.fj' },
  { label: 'google.com.gh (Ghana)', value: 'google.com.gh' },
  { label: 'google.com.gi (Gibraltar)', value: 'google.com.gi' },
  { label: 'google.com.gt (Guatemala)', value: 'google.com.gt' },
  { label: 'google.com.hk (Hong Kong)', value: 'google.com.hk' },
  { label: 'google.com.jm (Jamaica)', value: 'google.com.jm' },
  { label: 'google.com.kh (Cambodia)', value: 'google.com.kh' },
  { label: 'google.com.kw (Kuwait)', value: 'google.com.kw' },
  { label: 'google.com.lb (Lebanon)', value: 'google.com.lb' },
  { label: 'google.com.ly (Libya)', value: 'google.com.ly' },
  { label: 'google.com.mm (Myanmar)', value: 'google.com.mm' },
  { label: 'google.com.mt (Malta)', value: 'google.com.mt' },
  { label: 'google.com.mx (Mexico)', value: 'google.com.mx' },
  { label: 'google.com.my (Malaysia)', value: 'google.com.my' },
  { label: 'google.com.na (Namibia)', value: 'google.com.na' },
  { label: 'google.com.ng (Nigeria)', value: 'google.com.ng' },
  { label: 'google.com.ni (Nicaragua)', value: 'google.com.ni' },
  { label: 'google.com.np (Nepal)', value: 'google.com.np' },
  { label: 'google.com.om (Oman)', value: 'google.com.om' },
  { label: 'google.com.pa (Panama)', value: 'google.com.pa' },
  { label: 'google.com.pe (Peru)', value: 'google.com.pe' },
  { label: 'google.com.pg (Papua New Guinea)', value: 'google.com.pg' },
  { label: 'google.com.ph (Philippines)', value: 'google.com.ph' },
  { label: 'google.com.pk (Pakistan)', value: 'google.com.pk' },
  { label: 'google.com.pr (Puerto Rico)', value: 'google.com.pr' },
  { label: 'google.com.py (Paraguay)', value: 'google.com.py' },
  { label: 'google.com.qa (Qatar)', value: 'google.com.qa' },
  { label: 'google.com.sa (Saudi Arabia)', value: 'google.com.sa' },
  { label: 'google.com.sb (Solomon Islands)', value: 'google.com.sb' },
  { label: 'google.com.sg (Singapore)', value: 'google.com.sg' },
  { label: 'google.com.sl (Sierra Leone)', value: 'google.com.sl' },
  { label: 'google.com.sv (El Salvador)', value: 'google.com.sv' },
  { label: 'google.com.tj (Tajikistan)', value: 'google.com.tj' },
  { label: 'google.com.tr (Turkey)', value: 'google.com.tr' },
  { label: 'google.com.tw (Taiwan)', value: 'google.com.tw' },
  { label: 'google.com.ua (Ukraine)', value: 'google.com.ua' },
  { label: 'google.com.uy (Uruguay)', value: 'google.com.uy' },
  { label: 'google.com.vc (Saint Vincent and the Grenadines)', value: 'google.com.vc' },
  { label: 'google.com.vn (Vietnam)', value: 'google.com.vn' },
  { label: 'google.cv (Cape Verde)', value: 'google.cv' },
  { label: 'google.cz (Czech Republic)', value: 'google.cz' },
  { label: 'google.de (Germany)', value: 'google.de' },
  { label: 'google.dj (Djibouti)', value: 'google.dj' },
  { label: 'google.dk (Denmark)', value: 'google.dk' },
  { label: 'google.dm (Dominica)', value: 'google.dm' },
  { label: 'google.dz (Algeria)', value: 'google.dz' },
  { label: 'google.ee (Estonia)', value: 'google.ee' },
  { label: 'google.es (Spain)', value: 'google.es' },
  { label: 'google.fi (Finland)', value: 'google.fi' },
  { label: 'google.fm (Micronesia, Federated States of)', value: 'google.fm' },
  { label: 'google.fr (France)', value: 'google.fr' },
  { label: 'google.ga (Gabon)', value: 'google.ga' },
  { label: 'google.ge (Georgia)', value: 'google.ge' },
  { label: 'google.gl (Greenland)', value: 'google.gl' },
  { label: 'google.gm (Gambia)', value: 'google.gm' },
  { label: 'google.gp (Guadeloupe)', value: 'google.gp' },
  { label: 'google.gr (Greece)', value: 'google.gr' },
  { label: 'google.gy (Guyana)', value: 'google.gy' },
  { label: 'google.hn (Honduras)', value: 'google.hn' },
  { label: 'google.hr (Croatia)', value: 'google.hr' },
  { label: 'google.ht (Haiti)', value: 'google.ht' },
  { label: 'google.hu (Hungary)', value: 'google.hu' },
  { label: 'google.ie (Ireland)', value: 'google.ie' },
  { label: 'google.iq (Iraq)', value: 'google.iq' },
  { label: 'google.is (Iceland)', value: 'google.is' },
  { label: 'google.it (Italy)', value: 'google.it' },
  { label: 'google.je (Jersey)', value: 'google.je' },
  { label: 'google.jo (Jordan)', value: 'google.jo' },
  { label: 'google.kg (Kyrgyzstan)', value: 'google.kg' },
  { label: 'google.ki (Kiribati)', value: 'google.ki' },
  { label: 'google.kz (Kazakhstan)', value: 'google.kz' },
  { label: 'google.la (Laos)', value: 'google.la' },
  { label: 'google.li (Liechtenstein)', value: 'google.li' },
  { label: 'google.lk (Sri Lanka)', value: 'google.lk' },
  { label: 'google.lt (Lithuania)', value: 'google.lt' },
  { label: 'google.lu (Luxembourg)', value: 'google.lu' },
  { label: 'google.lv (Latvia)', value: 'google.lv' },
  { label: 'google.md (Moldova)', value: 'google.md' },
  { label: 'google.mg (Madagascar)', value: 'google.mg' },
  { label: 'google.mk (Macedonia)', value: 'google.mk' },
  { label: 'google.ml (Mali)', value: 'google.ml' },
  { label: 'google.mn (Mongolia)', value: 'google.mn' },
  { label: 'google.ms (Montserrat)', value: 'google.ms' },
  { label: 'google.mu (Mauritius)', value: 'google.mu' },
  { label: 'google.mv (Maldives)', value: 'google.mv' },
  { label: 'google.mw (Malawi)', value: 'google.mw' },
  { label: 'google.ne (Niger)', value: 'google.ne' },
  { label: 'google.nl (Netherlands)', value: 'google.nl' },
  { label: 'google.no (Norway)', value: 'google.no' },
  { label: 'google.nr (Nauru)', value: 'google.nr' },
  { label: 'google.nu (Niue)', value: 'google.nu' },
  { label: 'google.pl (Poland)', value: 'google.pl' },
  { label: 'google.ps (Palestine)', value: 'google.ps' },
  { label: 'google.pt (Portugal)', value: 'google.pt' },
  { label: 'google.ro (Romania)', value: 'google.ro' },
  { label: 'google.rs (Serbia)', value: 'google.rs' },
  { label: 'google.ru (Russia)', value: 'google.ru' },
  { label: 'google.rw (Rwanda)', value: 'google.rw' },
  { label: 'google.sc (Seychelles)', value: 'google.sc' },
  { label: 'google.se (Sweden)', value: 'google.se' },
  { label: 'google.sh (Saint Helena, Ascension and Tristan da Cunha)', value: 'google.sh' },
  { label: 'google.si (Slovenia)', value: 'google.si' },
  { label: 'google.sk (Slovakia)', value: 'google.sk' },
  { label: 'google.sm (San Marino)', value: 'google.sm' },
  { label: 'google.sn (Senegal)', value: 'google.sn' },
  { label: 'google.so (Somalia)', value: 'google.so' },
  { label: 'google.sr (Suriname)', value: 'google.sr' },
  { label: 'google.td (Chad)', value: 'google.td' },
  { label: 'google.tg (Togo)', value: 'google.tg' },
  { label: 'google.tk (Tokelau)', value: 'google.tk' },
  { label: 'google.tl (Timor-Leste)', value: 'google.tl' },
  { label: 'google.tm (Turkmenistan)', value: 'google.tm' },
  { label: 'google.tn (Tunisia)', value: 'google.tn' },
  { label: 'google.to (Tonga)', value: 'google.to' },
  { label: 'google.tt (Trinidad and Tobago)', value: 'google.tt' },
  { label: 'google.vg (British Virgin Islands)', value: 'google.vg' },
  { label: 'google.vu (Vanuatu)', value: 'google.vu' },
  { label: 'google.ws (Samoa)', value: 'google.ws' },
];