import { HttpMethod } from '@activepieces/pieces-common';
import { createAction } from '@activepieces/pieces-framework';
import { jungleGridAuth } from '../..';
import { jungleGridCommon } from '../common';

export const listArtifacts = createAction({
  auth: jungleGridAuth,
  name: 'list_artifacts',
  displayName: 'List Artifacts',
  description: 'List artifacts generated by a completed or running Jungle Grid job.',
  props: {
    job_id: jungleGridCommon.jobId,
  },
  async run(context) {
    const response = await jungleGridCommon.apiCall<Record<string, unknown>>({
      auth: context.auth,
      method: HttpMethod.GET,
      path: jungleGridCommon.endpoints.artifacts(context.propsValue.job_id),
    });

    return jungleGridCommon.toFlatRecords(response.body);
  },
});
