export enum ActionType {
	BRANCH = 'BRANCH',
	CODE = 'CODE',
	STORAGE = 'STORAGE',
	LOCAL_FLOW = 'LOCAL_FLOW',
	REMOTE_FLOW = 'REMOTE_FLOW',
	RESPONSE = 'RESPONSE',
	LOOP_ON_ITEMS = 'LOOP_ON_ITEMS',
	COMPONENT = 'COMPONENT',
}
