export enum OnboardingUsecasesEnum {
	LOAD_DATA_INTO_WAREHOUSE = 'LOAD_DATA_INTO_WAREHOUSE',
	SEND_DATA_INT_DIFFERENT_TOOLS = 'SEND_DATA_INT_DIFFERENT_TOOLS',
	COLLECT_USER_DATA = 'COLLECT_USER_DATA',
	AUTOMATE_MANUAL_WORK = 'AUTOMATE_MANUAL_WORK',
	INTEGRATE_DIFFERENT_TOOL = 'INTEGRATE_DIFFERENT_TOOL',
}
