export enum OnboardingUserRoleEnum {
	DEVELOPER = 'DEVELOPER',
	MARKETING_MANAGER = 'MARKETING_MANAGER',
	PRODUCT_MANAGER = 'PRODUCT_MANAGER',
	QUALITY_ENGINEER = 'QUALITY_ENGINEER',
	OTHER = 'OTHER',
}
