export enum OnboardingTechnicalLevelEnum {
	NOT_DEVELOPER = 'NOT_DEVELOPER',
	STIlL_LEARNING = 'STIlL_LEARNING',
	LOW_CODE = 'LOW_CODE',
	BEGINNER = 'BEGINNER',
	INTERMEDIATE = 'INTERMEDIATE',
	EXPERT = 'EXPERT',
}
