export enum RightSideBarType {
	COLLECTION_VERSIONS = 'COLLECTION_VERSIONS',
	FLOW_VERSIONS = 'FLOW_VERSIONS',
	STEP_TYPE = 'STEP_TYPE',
	TRIGGER_TYPE = 'TRIGGER_TYPE',
	EDIT_STEP = 'EDIT_STEP',
	NONE = 'NONE',
}
