export enum RightSideBarType {
	PIECE_VERSIONS = 'PIECE_VERSIONS',
	FLOW_VERSIONS = 'FLOW_VERSIONS',
	PIECE_TYPE = 'PIECE_TYPE',
	TRIGGER_TYPE = 'TRIGGER_TYPE',
	EDIT_PIECE = 'EDIT_PIECE',
	NONE = 'NONE',
}
