export enum TriggerType {
	SCHEDULE = 'SCHEDULE',
	EVENT = 'EVENT',
	MANUAL = 'MANUAL',
	EMPTY = 'EMPTY',
	WEBHOOK = 'WEBHOOK',
	INSTANCE_STARTED = 'INSTANCE_STARTED',
	INSTANCE_STOPPED = 'INSTANCE_STOPPED',
}
