const CLOCK_SKEW_BUFFER_SECONDS = 60

export const MCP_OAUTH_ACCESS_TOKEN_TTL_SECONDS = 15 * 60
export const MCP_OAUTH_REFRESH_TOKEN_TTL_MS = 30 * 24 * 60 * 60 * 1000
export const MCP_OAUTH_REVOKED_GRANT_TTL_SECONDS = MCP_OAUTH_ACCESS_TOKEN_TTL_SECONDS + CLOCK_SKEW_BUFFER_SECONDS
