export enum WebsocketClientEvent {
    TEST_FLOW_RUN_STARTED = 'TEST_FLOW_RUN_STARTED',
    GENERATE_CODE_FINISHED = 'GENERATE_CODE_FINIISHED',
    GENERATE_HTTP_REQUEST_FINISHED = 'GENERATE_HTTP_REQUEST_FINISHED',
    TEST_STEP_FINISHED = 'TEST_STEP_FINISHED',
    REFRESH_PIECE = 'REFRESH_PIECE',
    FLOW_RUN_PROGRESS = 'FLOW_RUN_PROGRESS',
}

export enum WebsocketServerEvent {
    TEST_STEP_RUN = 'TEST_STEP_RUN',
    GENERATE_CODE = 'GENERATE_CODE',
    GENERATE_HTTP_REQUEST = 'GENERATE_HTTP_REQUEST_FINISHED',
    TEST_FLOW_RUN = 'TEST_FLOW_RUN',
}
