

export enum WebsocketClientEvent {
    TEST_FLOW_RUN_STARTED = 'TEST_FLOW_RUN_STARTED',
    TEST_FLOW_RUN_PROGRESS = 'TEST_FLOW_RUN_PROGRESS',
    GENERATE_CODE_FINISHED = 'GENERATE_CODE_FINIISHED',
    TEST_STEP_FINISHED = 'TEST_STEP_FINISHED',
    GENERATE_HTTP_REQUEST_DETAILS_FINISHED = 'GENERATE_HTTP_REQUEST_DETAILS_FINISHED',
}

export enum WebsocketServerEvent {
    TEST_STEP_RUN = 'TEST_STEP_RUN',
    GENERATE_CODE = 'GENERATE_CODE',
    TEST_FLOW_RUN = 'TEST_FLOW_RUN',
    GENERATE_HTTP_REQUEST_DETAILS = 'GENERATE_HTTP_REQUEST_DETAILS',
}
