

export enum WebsocketClientEvent {
    TEST_FLOW_RUN_STARTED = 'TEST_FLOW_RUN_STARTED',
    TEST_FLOW_RUN_PROGRESS = 'TEST_FLOW_RUN_PROGRESS',
    GENERATE_CODE_FINISHED = 'GENERATE_CODE_FINIISHED',
    REQUEST_WRITE_FINISHED = 'REQUEST_WRITE_FINIISHED',
    TEST_STEP_FINISHED = 'TEST_STEP_FINISHED',
}

export enum WebsocketServerEvent {
    TEST_STEP_RUN = 'TEST_STEP_RUN',
    GENERATE_CODE = 'GENERATE_CODE',
    REQUEST_WRITE = 'REQUEST_WRITE',
    TEST_FLOW_RUN = 'TEST_FLOW_RUN', 
}
