export type ProjectSettingsTab =
  | 'general'
  | 'members'
  | 'alerts'
  | 'pieces'
  | 'environment';

export type SettingsTarget =
  | { type: 'route'; href: string }
  | { type: 'project-settings'; tab: ProjectSettingsTab }
  | { type: 'account-settings' };

export type SettingsEntry = {
  id: string;
  label: string;
  aliases: string;
  breadcrumb: string[];
  kind: 'setting' | 'section';
  scope: 'platform-admin' | 'project' | 'account';
  target: SettingsTarget;
  hideOnCloud?: boolean;
};

const route = (href: string): SettingsTarget => ({ type: 'route', href });
const projectTab = (tab: ProjectSettingsTab): SettingsTarget => ({
  type: 'project-settings',
  tab,
});

export const SETTINGS_INDEX: SettingsEntry[] = [
  {
    id: 'setting-project-members',
    label: 'Members',
    aliases: 'invite people team users project roles',
    breadcrumb: ['Project settings', 'Members'],
    kind: 'setting',
    scope: 'project',
    target: projectTab('members'),
  },
  {
    id: 'setting-project-name',
    label: 'Project name',
    aliases:
      'rename icon colour color concurrency active flows limit external id',
    breadcrumb: ['Project settings', 'General'],
    kind: 'setting',
    scope: 'project',
    target: projectTab('general'),
  },
  {
    id: 'setting-project-alerts',
    label: 'Alert Emails',
    aliases: 'notifications failure email alerts',
    breadcrumb: ['Project settings', 'Alert Emails'],
    kind: 'setting',
    scope: 'project',
    target: projectTab('alerts'),
  },
  {
    id: 'setting-project-pieces',
    label: 'Pieces',
    aliases: 'allowed pieces hide integrations apps',
    breadcrumb: ['Project settings', 'Pieces'],
    kind: 'setting',
    scope: 'project',
    target: projectTab('pieces'),
  },
  {
    id: 'setting-project-environment',
    label: 'Environment',
    aliases: 'git sync branch releases version control github repository',
    breadcrumb: ['Project settings', 'Environment'],
    kind: 'setting',
    scope: 'project',
    target: projectTab('environment'),
  },

  {
    id: 'setting-account-theme',
    label: 'Theme',
    aliases: 'dark mode light mode appearance system',
    breadcrumb: ['Account Settings'],
    kind: 'setting',
    scope: 'account',
    target: { type: 'account-settings' },
  },
  {
    id: 'setting-account-language',
    label: 'Language',
    aliases: 'locale translation',
    breadcrumb: ['Account Settings'],
    kind: 'setting',
    scope: 'account',
    target: { type: 'account-settings' },
  },
  {
    id: 'setting-account-picture',
    label: 'Profile picture',
    aliases: 'avatar photo image',
    breadcrumb: ['Account Settings'],
    kind: 'setting',
    scope: 'account',
    target: { type: 'account-settings' },
  },

  {
    id: 'setting-roles',
    label: 'Roles & Access',
    aliases: 'project roles permissions custom role rbac viewer editor',
    breadcrumb: ['Platform', 'Users'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/users/roles'),
  },
  {
    id: 'setting-global-connections',
    label: 'Global Connections',
    aliases: 'shared connections credentials all projects',
    breadcrumb: ['Platform', 'Connections'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/connections/global'),
  },

  {
    id: 'section-piece-sets',
    label: 'Piece Sets',
    aliases: 'allowlist which pieces projects',
    breadcrumb: ['Catalogue', 'Pieces'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/pieces/piece-sets'),
  },
  {
    id: 'setting-ai-providers',
    label: 'AI providers',
    aliases: 'openai anthropic gemini azure api key llm',
    breadcrumb: ['Catalogue', 'AI Center'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/ai'),
  },
  {
    id: 'setting-ai-models',
    label: 'Models',
    aliases: 'ai llm model type default',
    breadcrumb: ['Catalogue', 'AI Center'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/ai'),
  },
  {
    id: 'section-ai-capabilities',
    label: 'Capabilities',
    aliases: 'ai web search scraping image generation tavily firecrawl',
    breadcrumb: ['Catalogue', 'AI Center'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/ai/capabilities'),
  },

  {
    id: 'setting-saml',
    label: 'SAML 2.0',
    aliases: 'sso single sign on idp okta entra identity provider metadata',
    breadcrumb: ['Security', 'Single Sign On'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/sso'),
  },
  {
    id: 'setting-google-sign-in',
    label: 'Google sign-in',
    aliases: 'sso oauth social login',
    breadcrumb: ['Security', 'Single Sign On'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/sso'),
  },
  {
    id: 'setting-allowed-domains',
    label: 'Allowed Domains',
    aliases: 'allowed email domains restrict signup domain sso',
    breadcrumb: ['Security', 'Single Sign On'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/sso'),
  },
  {
    id: 'setting-email-login',
    label: 'Allowed Email Login',
    aliases: 'email and password sign-in disable password login sso',
    breadcrumb: ['Security', 'Single Sign On'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/sso'),
  },
  {
    id: 'setting-sso-domain',
    label: 'SSO Domain',
    aliases: 'custom domain dns txt verify',
    breadcrumb: ['Security', 'Single Sign On'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/sso'),
  },
  {
    id: 'setting-secret-managers',
    label: 'Secret Managers',
    aliases: 'vault hashicorp aws cyberark 1password secrets',
    breadcrumb: ['Security', 'Secret Managers'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/secret-managers'),
  },
  {
    id: 'setting-event-streaming',
    label: 'Event Streaming',
    aliases: 'audit log destinations forwarding webhook siem splunk datadog',
    breadcrumb: ['Security', 'Audit Logs'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/audit-log/streaming'),
  },

  {
    id: 'setting-api-keys',
    label: 'API Keys',
    aliases: 'token rest api access key',
    breadcrumb: ['Developers', 'API Keys'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/api-keys'),
  },
  {
    id: 'setting-embed-domain',
    label: 'Embed domain',
    aliases: 'allowed websites origins iframe cors subdomain dns',
    breadcrumb: ['Developers', 'Embedding'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/embedding'),
  },
  {
    id: 'setting-signing-keys',
    label: 'Signing keys',
    aliases: 'jwt embed token sdk',
    breadcrumb: ['Developers', 'Embedding'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/embedding'),
  },
  {
    id: 'setting-mcp-server',
    label: 'Platform MCP Server',
    aliases: 'mcp connection json configuration agents claude cursor',
    breadcrumb: ['Developers', 'MCP Server'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/mcp'),
  },
  {
    id: 'setting-mcp-tools',
    label: 'Tools',
    aliases: 'mcp internal tools agents permissions',
    breadcrumb: ['Developers', 'MCP Server'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/mcp/tools'),
  },

  {
    id: 'section-worker-groups',
    label: 'Worker groups',
    aliases: 'dedicated capacity pinned projects',
    breadcrumb: ['Operations', 'Workers'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/workers/groups'),
  },
  {
    id: 'section-sandboxes',
    label: 'Sandboxes',
    aliases: 'worker sandbox execution isolation',
    breadcrumb: ['Operations', 'Workers'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/workers'),
  },
  {
    id: 'section-stuck-jobs',
    label: 'Stuck jobs',
    aliases: 'queue running queued oldest wait',
    breadcrumb: ['Operations', 'Health'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/health'),
  },
  {
    id: 'section-trigger-health',
    label: 'Trigger Health Status',
    aliases: 'triggers failing webhook polling schedule',
    breadcrumb: ['Operations', 'Triggers'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/triggers'),
  },

  {
    id: 'setting-platform-name',
    label: 'Platform Name',
    aliases: 'branding rename title',
    breadcrumb: ['Account', 'General'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/general'),
  },
  {
    id: 'setting-logo',
    label: 'Logo',
    aliases: 'branding icon appearance white label',
    breadcrumb: ['Account', 'General'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/general'),
  },
  {
    id: 'setting-favicon',
    label: 'Favicon',
    aliases: 'branding browser tab icon',
    breadcrumb: ['Account', 'General'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/general'),
  },
  {
    id: 'setting-primary-color',
    label: 'Primary Color',
    aliases: 'primary colour theme brand accent white label',
    breadcrumb: ['Account', 'General'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/general'),
  },
  {
    id: 'setting-delete-platform',
    label: 'Delete platform',
    aliases: 'danger zone destroy',
    breadcrumb: ['Account', 'General'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/general'),
  },
  {
    id: 'setting-seats',
    label: 'Seats',
    aliases: 'licences licenses members users billing',
    breadcrumb: ['Account', 'Billing'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/billing'),
  },
  {
    id: 'setting-credits',
    label: 'Credits',
    aliases: 'ai credits top up auto recharge billing',
    breadcrumb: ['Account', 'Billing'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/billing'),
  },
  {
    id: 'setting-subscription',
    label: 'Current subscription',
    aliases: 'plan upgrade cancel invoices payment card billing',
    breadcrumb: ['Account', 'Billing'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/billing'),
  },
  {
    id: 'section-usage',
    label: 'Usage',
    aliases: 'consumption tasks runs ai credits limits',
    breadcrumb: ['Account', 'Billing'],
    kind: 'section',
    scope: 'platform-admin',
    target: route('/platform/billing/usage'),
  },
  {
    id: 'setting-telemetry',
    label: 'Telemetry',
    aliases: 'product analytics tracking opt out events',
    breadcrumb: ['Account', 'General'],
    kind: 'setting',
    scope: 'platform-admin',
    target: route('/platform/general'),
    hideOnCloud: true,
  },
];
