import {
  ChartLineData02Icon,
  CompassIcon,
  ConnectIcon,
  DashboardSquare01Icon,
  FileBracesIcon,
  FileHeartIcon,
  FrameIcon,
  Key01Icon,
  Login03Icon,
  MousePointerClickIcon,
  PaletteIcon,
  PreferenceHorizontalIcon,
  PuzzleIcon,
  ReceiptIcon,
  Robot01Icon,
  ServerStack01Icon,
  Shield01Icon,
  SourceCodeSquareIcon,
  UnplugIcon,
  UserMultipleIcon,
  WebhookIcon,
  WorkflowSquare02Icon,
} from '@hugeicons/core-free-icons';

import { type IconSvgElement } from '@/components/custom/hugeicons-icon';

export type StaticPage = {
  id: string;
  label: string;
  href: string;
  icon: IconSvgElement;
  requiresPlatformAdmin?: boolean;
};

export const STATIC_PAGES: StaticPage[] = [
  {
    id: 'page-automations',
    label: 'Automations',
    href: '/automations',
    icon: WorkflowSquare02Icon,
  },
  {
    id: 'page-explore',
    label: 'Explore Templates',
    href: '/templates',
    icon: CompassIcon,
  },
  {
    id: 'page-impact',
    label: 'Impact',
    href: '/impact',
    icon: ChartLineData02Icon,
  },
  {
    id: 'page-mcp',
    label: 'MCP',
    href: '/mcp-server',
    icon: ConnectIcon,
  },
  // Platform Admin pages
  {
    id: 'page-platform-projects',
    label: 'Platform Admin — Projects',
    href: '/platform/projects',
    icon: DashboardSquare01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-users',
    label: 'Platform Admin — Users',
    href: '/platform/users',
    icon: UserMultipleIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-ai',
    label: 'Platform Admin — AI Center',
    href: '/platform/ai',
    icon: Robot01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-ai-capabilities',
    label: 'Platform Admin — AI Capabilities',
    href: '/platform/ai/capabilities',
    icon: Robot01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-mcp',
    label: 'Platform Admin — MCP Server',
    href: '/platform/mcp',
    icon: ConnectIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-mcp-tools',
    label: 'Platform Admin — MCP Tools',
    href: '/platform/mcp/tools',
    icon: ConnectIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-mcp-activity',
    label: 'Platform Admin — MCP Activity',
    href: '/platform/mcp/activity',
    icon: ConnectIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-branding',
    label: 'Platform Admin — General',
    href: '/platform/general',
    icon: PaletteIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-connections',
    label: 'Platform Admin — Global Connections',
    href: '/platform/connections/global',
    icon: UnplugIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-pieces',
    label: 'Platform Admin — Pieces',
    href: '/platform/pieces',
    icon: PuzzleIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-piece-sets',
    label: 'Platform Admin — Piece Sets',
    href: '/platform/pieces/piece-sets',
    icon: PuzzleIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-templates',
    label: 'Platform Admin — Templates',
    href: '/platform/templates',
    icon: DashboardSquare01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-billing',
    label: 'Platform Admin — Billing',
    href: '/platform/billing',
    icon: ReceiptIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-embedding',
    label: 'Platform Admin — Embedding',
    href: '/platform/embedding',
    icon: FrameIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-audit-logs',
    label: 'Platform Admin — Audit Logs',
    href: '/platform/audit-log',
    icon: SourceCodeSquareIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-sso',
    label: 'Platform Admin — Single Sign On',
    href: '/platform/sso',
    icon: Login03Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-project-roles',
    label: 'Platform Admin — Roles & Access',
    href: '/platform/users/roles',
    icon: PreferenceHorizontalIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-api-keys',
    label: 'Platform Admin — API Keys',
    href: '/platform/api-keys',
    icon: FileBracesIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-secret-managers',
    label: 'Platform Admin — Secret Managers',
    href: '/platform/secret-managers',
    icon: Key01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-workers',
    label: 'Platform Admin — Workers',
    href: '/platform/workers',
    icon: ServerStack01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-worker-groups',
    label: 'Platform Admin — Worker Groups',
    href: '/platform/workers/groups',
    icon: ServerStack01Icon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-health',
    label: 'Platform Admin — Health',
    href: '/platform/health',
    icon: FileHeartIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-health-runs',
    label: 'Platform Admin — Runs Health',
    href: '/platform/health/runs',
    icon: FileHeartIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-health-queue',
    label: 'Platform Admin — Queue Health',
    href: '/platform/health/queue',
    icon: FileHeartIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-triggers',
    label: 'Platform Admin — Triggers',
    href: '/platform/triggers',
    icon: MousePointerClickIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-event-streaming',
    label: 'Platform Admin — Event Streaming',
    href: '/platform/audit-log/streaming',
    icon: WebhookIcon,
    requiresPlatformAdmin: true,
  },
  {
    id: 'page-platform-admin',
    label: 'Platform Admin',
    href: '/platform/projects',
    icon: Shield01Icon,
    requiresPlatformAdmin: true,
  },
];
