export const clayCompanySearchOptions = {
    companyType: [
        { label: "Privately held", value: "Privately Held" },
        { label: "Public company", value: "Public Company" },
        { label: "Partnership", value: "Partnership" },
        { label: "Self-employed", value: "Self Employed" },
        { label: "Nonprofit", value: "Non Profit" },
        { label: "Educational", value: "Educational" },
        { label: "Self-owned", value: "Self Owned" },
        { label: "Government agency", value: "Government Agency" },
    ],
    companySize: [
        { label: "1 employee", value: "1" },
        { label: "2–10 employees", value: "2-10" },
        { label: "11–50 employees", value: "11-50" },
        { label: "51–200 employees", value: "51-200" },
        { label: "201–500 employees", value: "201-500" },
        { label: "501–1,000 employees", value: "501-1,000" },
        { label: "1,001–5,000 employees", value: "1,001-5,000" },
        { label: "5,001–10,000 employees", value: "5,001-10,000" },
        { label: "10,001+ employees", value: "10,001+" },
    ],
    annualRevenue: [
        { label: "$0–$500K", value: "0-500K" },
        { label: "$500K–$1M", value: "500K-1M" },
        { label: "$1M–$5M", value: "1M-5M" },
        { label: "$5M–$10M", value: "5M-10M" },
        { label: "$10M–$25M", value: "10M-25M" },
        { label: "$25M–$75M", value: "25M-75M" },
        { label: "$75M–$200M", value: "75M-200M" },
        { label: "$200M–$500M", value: "200M-500M" },
        { label: "$500M–$1B", value: "500M-1B" },
        { label: "$1B–$10B", value: "1B-10B" },
        { label: "$10B–$100B", value: "10B-100B" },
        { label: "$100B+", value: "100B-1T" },
    ],
    industry: [
        { label: "Abrasives and Nonmetallic Minerals Manufacturing", value: "Abrasives and Nonmetallic Minerals Manufacturing" },
        { label: "Accessible Architecture and Design", value: "Accessible Architecture and Design" },
        { label: "Accommodation Services", value: "Accommodation Services" },
        { label: "Accounting", value: "Accounting" },
        { label: "Administration of Justice", value: "Administration of Justice" },
        { label: "Administrative and Support Services", value: "Administrative and Support Services" },
        { label: "Advertising Services", value: "Advertising Services" },
        { label: "Agricultural Chemical Manufacturing", value: "Agricultural Chemical Manufacturing" },
        { label: "Agriculture, Construction, Mining Machinery Manufacturing", value: "Agriculture, Construction, Mining Machinery Manufacturing" },
        { label: "Air, Water, and Waste Program Management", value: "Air, Water, and Waste Program Management" },
        { label: "Airlines and Aviation", value: "Airlines and Aviation" },
        { label: "Alternative Dispute Resolution", value: "Alternative Dispute Resolution" },
        { label: "Alternative Medicine", value: "Alternative Medicine" },
        { label: "Ambulance Services", value: "Ambulance Services" },
        { label: "Amusement Parks and Arcades", value: "Amusement Parks and Arcades" },
        { label: "Animal Feed Manufacturing", value: "Animal Feed Manufacturing" },
        { label: "Animation", value: "Animation" },
        { label: "Animation and Post-production", value: "Animation and Post-production" },
        { label: "Apparel Manufacturing", value: "Apparel Manufacturing" },
        { label: "Apparel and Fashion", value: "Apparel and Fashion" },
        { label: "Appliances, Electrical, and Electronics Manufacturing", value: "Appliances, Electrical, and Electronics Manufacturing" },
        { label: "Architectural and Structural Metal Manufacturing", value: "Architectural and Structural Metal Manufacturing" },
        { label: "Architecture and Planning", value: "Architecture and Planning" },
        { label: "Armed Forces", value: "Armed Forces" },
        { label: "Artists and Writers", value: "Artists and Writers" },
        { label: "Arts and Crafts", value: "Arts and Crafts" },
        { label: "Audio and Video Equipment Manufacturing", value: "Audio and Video Equipment Manufacturing" },
        { label: "Automation Machinery Manufacturing", value: "Automation Machinery Manufacturing" },
        { label: "Automotive", value: "Automotive" },
        { label: "Aviation & Aerospace", value: "Aviation & Aerospace" },
        { label: "Aviation and Aerospace Component Manufacturing", value: "Aviation and Aerospace Component Manufacturing" },
        { label: "Baked Goods Manufacturing", value: "Baked Goods Manufacturing" },
        { label: "Banking", value: "Banking" },
        { label: "Bars, Taverns, and Nightclubs", value: "Bars, Taverns, and Nightclubs" },
        { label: "Bed-and-Breakfasts, Hostels, Homestays", value: "Bed-and-Breakfasts, Hostels, Homestays" },
        { label: "Beverage Manufacturing", value: "Beverage Manufacturing" },
        { label: "Biomass Electric Power Generation", value: "Biomass Electric Power Generation" },
        { label: "Biotechnology", value: "Biotechnology" },
        { label: "Biotechnology Research", value: "Biotechnology Research" },
        { label: "Blockchain Services", value: "Blockchain Services" },
        { label: "Blogs", value: "Blogs" },
        { label: "Boilers, Tanks, and Shipping Container Manufacturing", value: "Boilers, Tanks, and Shipping Container Manufacturing" },
        { label: "Book Publishing", value: "Book Publishing" },
        { label: "Book and Periodical Publishing", value: "Book and Periodical Publishing" },
        { label: "Breweries", value: "Breweries" },
        { label: "Broadcast Media Production and Distribution", value: "Broadcast Media Production and Distribution" },
        { label: "Building Construction", value: "Building Construction" },
        { label: "Building Equipment Contractors", value: "Building Equipment Contractors" },
        { label: "Building Finishing Contractors", value: "Building Finishing Contractors" },
        { label: "Building Materials", value: "Building Materials" },
        { label: "Building Structure and Exterior Contractors", value: "Building Structure and Exterior Contractors" },
        { label: "Business Consulting and Services", value: "Business Consulting and Services" },
        { label: "Business Content", value: "Business Content" },
        { label: "Business Intelligence Platforms", value: "Business Intelligence Platforms" },
        { label: "Business Supplies and Equipment", value: "Business Supplies and Equipment" },
        { label: "Capital Markets", value: "Capital Markets" },
        { label: "Caterers", value: "Caterers" },
        { label: "Chemical Manufacturing", value: "Chemical Manufacturing" },
        { label: "Chemical Raw Materials Manufacturing", value: "Chemical Raw Materials Manufacturing" },
        { label: "Child Day Care Services", value: "Child Day Care Services" },
        { label: "Chiropractors", value: "Chiropractors" },
        { label: "Civic and Social Organizations", value: "Civic and Social Organizations" },
        { label: "Civil Engineering", value: "Civil Engineering" },
        { label: "Claims Adjusting, Actuarial Services", value: "Claims Adjusting, Actuarial Services" },
        { label: "Clay and Refractory Products Manufacturing", value: "Clay and Refractory Products Manufacturing" },
        { label: "Climate Data and Analytics", value: "Climate Data and Analytics" },
        { label: "Climate Technology Product Manufacturing", value: "Climate Technology Product Manufacturing" },
        { label: "Coal Mining", value: "Coal Mining" },
        { label: "Collection Agencies", value: "Collection Agencies" },
        { label: "Commercial Real Estate", value: "Commercial Real Estate" },
        { label: "Commercial and Industrial Equipment Rental", value: "Commercial and Industrial Equipment Rental" },
        { label: "Commercial and Industrial Machinery Maintenance", value: "Commercial and Industrial Machinery Maintenance" },
        { label: "Commercial and Service Industry Machinery Manufacturing", value: "Commercial and Service Industry Machinery Manufacturing" },
        { label: "Communications Equipment Manufacturing", value: "Communications Equipment Manufacturing" },
        { label: "Community Development and Urban Planning", value: "Community Development and Urban Planning" },
        { label: "Community Services", value: "Community Services" },
        { label: "Computer Games", value: "Computer Games" },
        { label: "Computer Hardware", value: "Computer Hardware" },
        { label: "Computer Hardware Manufacturing", value: "Computer Hardware Manufacturing" },
        { label: "Computer Networking", value: "Computer Networking" },
        { label: "Computer Networking Products", value: "Computer Networking Products" },
        { label: "Computer and Network Security", value: "Computer and Network Security" },
        { label: "Computers and Electronics Manufacturing", value: "Computers and Electronics Manufacturing" },
        { label: "Conservation Programs", value: "Conservation Programs" },
        { label: "Construction", value: "Construction" },
        { label: "Construction Hardware Manufacturing", value: "Construction Hardware Manufacturing" },
        { label: "Consumer Electronics", value: "Consumer Electronics" },
        { label: "Consumer Goods", value: "Consumer Goods" },
        { label: "Consumer Goods Rental", value: "Consumer Goods Rental" },
        { label: "Consumer Services", value: "Consumer Services" },
        { label: "Cosmetics", value: "Cosmetics" },
        { label: "Cosmetology and Barber Schools", value: "Cosmetology and Barber Schools" },
        { label: "Courts of Law", value: "Courts of Law" },
        { label: "Credit Intermediation", value: "Credit Intermediation" },
        { label: "Dairy", value: "Dairy" },
        { label: "Dairy Product Manufacturing", value: "Dairy Product Manufacturing" },
        { label: "Dance Companies", value: "Dance Companies" },
        { label: "Data Infrastructure and Analytics", value: "Data Infrastructure and Analytics" },
        { label: "Data Security Software Products", value: "Data Security Software Products" },
        { label: "Defense & Space", value: "Defense & Space" },
        { label: "Defense and Space Manufacturing", value: "Defense and Space Manufacturing" },
        { label: "Dentists", value: "Dentists" },
        { label: "Design", value: "Design" },
        { label: "Design Services", value: "Design Services" },
        { label: "Desktop Computing Software Products", value: "Desktop Computing Software Products" },
        { label: "Digital Accessibility Services", value: "Digital Accessibility Services" },
        { label: "Distilleries", value: "Distilleries" },
        { label: "E-Learning", value: "E-Learning" },
        { label: "E-Learning Providers", value: "E-Learning Providers" },
        { label: "Economic Programs", value: "Economic Programs" },
        { label: "Education", value: "Education" },
        { label: "Education Administration Programs", value: "Education Administration Programs" },
        { label: "Education Management", value: "Education Management" },
        { label: "Electric Lighting Equipment Manufacturing", value: "Electric Lighting Equipment Manufacturing" },
        { label: "Electric Power Generation", value: "Electric Power Generation" },
        { label: "Electric Power Transmission, Control, and Distribution", value: "Electric Power Transmission, Control, and Distribution" },
        { label: "Electrical Equipment Manufacturing", value: "Electrical Equipment Manufacturing" },
        { label: "Electronic and Precision Equipment Maintenance", value: "Electronic and Precision Equipment Maintenance" },
        { label: "Embedded Software Products", value: "Embedded Software Products" },
        { label: "Emergency and Relief Services", value: "Emergency and Relief Services" },
        { label: "Engineering Services", value: "Engineering Services" },
        { label: "Engines and Power Transmission Equipment Manufacturing", value: "Engines and Power Transmission Equipment Manufacturing" },
        { label: "Entertainment", value: "Entertainment" },
        { label: "Entertainment Providers", value: "Entertainment Providers" },
        { label: "Environmental Quality Programs", value: "Environmental Quality Programs" },
        { label: "Environmental Services", value: "Environmental Services" },
        { label: "Equipment Rental Services", value: "Equipment Rental Services" },
        { label: "Events Services", value: "Events Services" },
        { label: "Executive Offices", value: "Executive Offices" },
        { label: "Executive Search Services", value: "Executive Search Services" },
        { label: "Fabricated Metal Products", value: "Fabricated Metal Products" },
        { label: "Facilities Services", value: "Facilities Services" },
        { label: "Farming, Ranching, Forestry", value: "Farming, Ranching, Forestry" },
        { label: "Farming", value: "Farming" },
        { label: "Fashion Accessories Manufacturing", value: "Fashion Accessories Manufacturing" },
        { label: "Financial Services", value: "Financial Services" },
        { label: "Fine Art", value: "Fine Art" },
        { label: "Fine Arts Schools", value: "Fine Arts Schools" },
        { label: "Fire Protection", value: "Fire Protection" },
        { label: "Fisheries", value: "Fisheries" },
        { label: "Flight Training", value: "Flight Training" },
        { label: "Food & Beverages", value: "Food & Beverages" },
        { label: "Food and Beverage Manufacturing", value: "Food and Beverage Manufacturing" },
        { label: "Food and Beverage Retail", value: "Food and Beverage Retail" },
        { label: "Food and Beverage Services", value: "Food and Beverage Services" },
        { label: "Food Production", value: "Food Production" },
        { label: "Footwear Manufacturing", value: "Footwear Manufacturing" },
        { label: "Forestry and Logging", value: "Forestry and Logging" },
        { label: "Freight and Package Transportation", value: "Freight and Package Transportation" },
        { label: "Fruit and Vegetable Preserves Manufacturing", value: "Fruit and Vegetable Preserves Manufacturing" },
        { label: "Fundraising", value: "Fundraising" },
        { label: "Funds and Trusts", value: "Funds and Trusts" },
        { label: "Furniture", value: "Furniture" },
        { label: "Furniture and Home Furnishings Manufacturing", value: "Furniture and Home Furnishings Manufacturing" },
        { label: "Gambling Facilities and Casinos", value: "Gambling Facilities and Casinos" },
        { label: "Geothermal Electric Power Generation", value: "Geothermal Electric Power Generation" },
        { label: "Glass Product Manufacturing", value: "Glass Product Manufacturing" },
        { label: "Glass, Ceramics and Concrete Manufacturing", value: "Glass, Ceramics and Concrete Manufacturing" },
        { label: "Golf Courses and Country Clubs", value: "Golf Courses and Country Clubs" },
        { label: "Government Administration", value: "Government Administration" },
        { label: "Government Relations", value: "Government Relations" },
        { label: "Government Relations Services", value: "Government Relations Services" },
        { label: "Graphic Design", value: "Graphic Design" },
        { label: "Ground Passenger Transportation", value: "Ground Passenger Transportation" },
        { label: "HVAC and Refrigeration Equipment Manufacturing", value: "HVAC and Refrigeration Equipment Manufacturing" },
        { label: "Health and Human Services", value: "Health and Human Services" },
        { label: "Health, Wellness and Fitness", value: "Health, Wellness and Fitness" },
        { label: "Higher Education", value: "Higher Education" },
        { label: "Highway, Street, and Bridge Construction", value: "Highway, Street, and Bridge Construction" },
        { label: "Historical Sites", value: "Historical Sites" },
        { label: "Holding Companies", value: "Holding Companies" },
        { label: "Home Health Care Services", value: "Home Health Care Services" },
        { label: "Horticulture", value: "Horticulture" },
        { label: "Hospitality", value: "Hospitality" },
        { label: "Hospitals", value: "Hospitals" },
        { label: "Hospitals and Health Care", value: "Hospitals and Health Care" },
        { label: "Hotels and Motels", value: "Hotels and Motels" },
        { label: "Household Appliance Manufacturing", value: "Household Appliance Manufacturing" },
        { label: "Household Services", value: "Household Services" },
        { label: "Household and Institutional Furniture Manufacturing", value: "Household and Institutional Furniture Manufacturing" },
        { label: "Housing Programs", value: "Housing Programs" },
        { label: "Housing and Community Development", value: "Housing and Community Development" },
        { label: "Human Resources", value: "Human Resources" },
        { label: "Human Resources Services", value: "Human Resources Services" },
        { label: "Hydroelectric Power Generation", value: "Hydroelectric Power Generation" },
        { label: "IT Services and IT Consulting", value: "IT Services and IT Consulting" },
        { label: "IT System Custom Software Development", value: "IT System Custom Software Development" },
        { label: "IT System Data Services", value: "IT System Data Services" },
        { label: "IT System Design Services", value: "IT System Design Services" },
        { label: "IT System Installation and Disposal", value: "IT System Installation and Disposal" },
        { label: "IT System Operations and Maintenance", value: "IT System Operations and Maintenance" },
        { label: "IT System Testing and Evaluation", value: "IT System Testing and Evaluation" },
        { label: "IT System Training and Support", value: "IT System Training and Support" },
        { label: "Import and Export", value: "Import and Export" },
        { label: "Individual and Family Services", value: "Individual and Family Services" },
        { label: "Industrial Automation", value: "Industrial Automation" },
        { label: "Industrial Machinery Manufacturing", value: "Industrial Machinery Manufacturing" },
        { label: "Industry Associations", value: "Industry Associations" },
        { label: "Information Services", value: "Information Services" },
        { label: "Information Technology and Services", value: "Information Technology and Services" },
        { label: "Insurance", value: "Insurance" },
        { label: "Insurance Agencies and Brokerages", value: "Insurance Agencies and Brokerages" },
        { label: "Insurance Carriers", value: "Insurance Carriers" },
        { label: "Insurance and Employee Benefit Funds", value: "Insurance and Employee Benefit Funds" },
        { label: "Interior Design", value: "Interior Design" },
        { label: "International Affairs", value: "International Affairs" },
        { label: "International Trade and Development", value: "International Trade and Development" },
        { label: "Internet Marketplace Platforms", value: "Internet Marketplace Platforms" },
        { label: "Internet News", value: "Internet News" },
        { label: "Internet Publishing", value: "Internet Publishing" },
        { label: "Investment Advice", value: "Investment Advice" },
        { label: "Investment Banking", value: "Investment Banking" },
        { label: "Investment Management", value: "Investment Management" },
        { label: "Janitorial Services", value: "Janitorial Services" },
        { label: "Landscaping Services", value: "Landscaping Services" },
        { label: "Language Schools", value: "Language Schools" },
        { label: "Laundry and Drycleaning Services", value: "Laundry and Drycleaning Services" },
        { label: "Law Enforcement", value: "Law Enforcement" },
        { label: "Law Practice", value: "Law Practice" },
        { label: "Leasing Non-residential Real Estate", value: "Leasing Non-residential Real Estate" },
        { label: "Leasing Residential Real Estate", value: "Leasing Residential Real Estate" },
        { label: "Leather Product Manufacturing", value: "Leather Product Manufacturing" },
        { label: "Legal Services", value: "Legal Services" },
        { label: "Legislative Offices", value: "Legislative Offices" },
        { label: "Leisure, Travel & Tourism", value: "Leisure, Travel & Tourism" },
        { label: "Libraries", value: "Libraries" },
        { label: "Loan Brokers", value: "Loan Brokers" },
        { label: "Luxury Goods and Jewelry", value: "Luxury Goods and Jewelry" },
        { label: "Machinery Manufacturing", value: "Machinery Manufacturing" },
        { label: "Manufacturing", value: "Manufacturing" },
        { label: "Maritime", value: "Maritime" },
        { label: "Maritime Transportation", value: "Maritime Transportation" },
        { label: "Market Research", value: "Market Research" },
        { label: "Marketing Services", value: "Marketing Services" },
        { label: "Mattress and Blinds Manufacturing", value: "Mattress and Blinds Manufacturing" },
        { label: "Measuring and Control Instrument Manufacturing", value: "Measuring and Control Instrument Manufacturing" },
        { label: "Meat Products Manufacturing", value: "Meat Products Manufacturing" },
        { label: "Mechanical or Industrial Engineering", value: "Mechanical or Industrial Engineering" },
        { label: "Media & Telecommunications", value: "Media & Telecommunications" },
        { label: "Media Production", value: "Media Production" },
        { label: "Medical Devices", value: "Medical Devices" },
        { label: "Medical Equipment Manufacturing", value: "Medical Equipment Manufacturing" },
        { label: "Medical Practices", value: "Medical Practices" },
        { label: "Medical and Diagnostic Laboratories", value: "Medical and Diagnostic Laboratories" },
        { label: "Mental Health Care", value: "Mental Health Care" },
        { label: "Metal Ore Mining", value: "Metal Ore Mining" },
        { label: "Metal Treatments", value: "Metal Treatments" },
        { label: "Metal Valve, Ball, and Roller Manufacturing", value: "Metal Valve, Ball, and Roller Manufacturing" },
        { label: "Metalworking Machinery Manufacturing", value: "Metalworking Machinery Manufacturing" },
        { label: "Military and International Affairs", value: "Military and International Affairs" },
        { label: "Mining", value: "Mining" },
        { label: "Mobile Computing Software Products", value: "Mobile Computing Software Products" },
        { label: "Mobile Food Services", value: "Mobile Food Services" },
        { label: "Mobile Gaming Apps", value: "Mobile Gaming Apps" },
        { label: "Motor Vehicle Manufacturing", value: "Motor Vehicle Manufacturing" },
        { label: "Motor Vehicle Parts Manufacturing", value: "Motor Vehicle Parts Manufacturing" },
        { label: "Movies and Sound Recording", value: "Movies and Sound Recording" },
        { label: "Movies, Videos and Sound", value: "Movies, Videos and Sound" },
        { label: "Museums", value: "Museums" },
        { label: "Museums, Historical Sites, and Zoos", value: "Museums, Historical Sites, and Zoos" },
        { label: "Music", value: "Music" },
        { label: "Musicians", value: "Musicians" },
        { label: "Nanotechnology Research", value: "Nanotechnology Research" },
        { label: "Natural Gas Distribution", value: "Natural Gas Distribution" },
        { label: "Newspaper Publishing", value: "Newspaper Publishing" },
        { label: "Non-profit Organization Management", value: "Non-profit Organization Management" },
        { label: "Non-profit Organizations", value: "Non-profit Organizations" },
        { label: "Nonmetallic Mineral Mining", value: "Nonmetallic Mineral Mining" },
        { label: "Nonresidential Building Construction", value: "Nonresidential Building Construction" },
        { label: "Nuclear Electric Power Generation", value: "Nuclear Electric Power Generation" },
        { label: "Nursing Homes and Residential Care Facilities", value: "Nursing Homes and Residential Care Facilities" },
        { label: "Office Administration", value: "Office Administration" },
        { label: "Office Furniture and Fixtures Manufacturing", value: "Office Furniture and Fixtures Manufacturing" },
        { label: "Oil and Gas", value: "Oil and Gas" },
        { label: "Oil, Gas, and Mining", value: "Oil, Gas, and Mining" },
        { label: "Online Audio and Video Media", value: "Online Audio and Video Media" },
        { label: "Online Media", value: "Online Media" },
        { label: "Online and Mail Order Retail", value: "Online and Mail Order Retail" },
        { label: "Operations Consulting", value: "Operations Consulting" },
        { label: "Optometrists", value: "Optometrists" },
        { label: "Outpatient Care Centers", value: "Outpatient Care Centers" },
        { label: "Outsourcing and Offshoring Consulting", value: "Outsourcing and Offshoring Consulting" },
        { label: "Outsourcing/Offshoring", value: "Outsourcing/Offshoring" },
        { label: "Packaging and Containers", value: "Packaging and Containers" },
        { label: "Packaging and Containers Manufacturing", value: "Packaging and Containers Manufacturing" },
        { label: "Paint, Coating, and Adhesive Manufacturing", value: "Paint, Coating, and Adhesive Manufacturing" },
        { label: "Paper and Forest Product Manufacturing", value: "Paper and Forest Product Manufacturing" },
        { label: "Paper and Forest Products", value: "Paper and Forest Products" },
        { label: "Performing Arts", value: "Performing Arts" },
        { label: "Performing Arts and Spectator Sports", value: "Performing Arts and Spectator Sports" },
        { label: "Periodical Publishing", value: "Periodical Publishing" },
        { label: "Personal Care Product Manufacturing", value: "Personal Care Product Manufacturing" },
        { label: "Personal Care Services", value: "Personal Care Services" },
        { label: "Personal and Laundry Services", value: "Personal and Laundry Services" },
        { label: "Pet Services", value: "Pet Services" },
        { label: "Pharmaceutical Manufacturing", value: "Pharmaceutical Manufacturing" },
        { label: "Philanthropic Fundraising Services", value: "Philanthropic Fundraising Services" },
        { label: "Philanthropy", value: "Philanthropy" },
        { label: "Photography", value: "Photography" },
        { label: "Physical, Occupational and Speech Therapists", value: "Physical, Occupational and Speech Therapists" },
        { label: "Physicians", value: "Physicians" },
        { label: "Plastics Manufacturing", value: "Plastics Manufacturing" },
        { label: "Plastics and Rubber Product Manufacturing", value: "Plastics and Rubber Product Manufacturing" },
        { label: "Political Organizations", value: "Political Organizations" },
        { label: "Primary Metal Manufacturing", value: "Primary Metal Manufacturing" },
        { label: "Primary and Secondary Education", value: "Primary and Secondary Education" },
        { label: "Printing Services", value: "Printing Services" },
        { label: "Professional Organizations", value: "Professional Organizations" },
        { label: "Professional Services", value: "Professional Services" },
        { label: "Professional Training and Coaching", value: "Professional Training and Coaching" },
        { label: "Program Development", value: "Program Development" },
        { label: "Public Assistance Programs", value: "Public Assistance Programs" },
        { label: "Public Health", value: "Public Health" },
        { label: "Public Policy", value: "Public Policy" },
        { label: "Public Policy Offices", value: "Public Policy Offices" },
        { label: "Public Relations and Communications Services", value: "Public Relations and Communications Services" },
        { label: "Public Safety", value: "Public Safety" },
        { label: "Radio and Television Broadcasting", value: "Radio and Television Broadcasting" },
        { label: "Rail Transportation", value: "Rail Transportation" },
        { label: "Railroad Equipment Manufacturing", value: "Railroad Equipment Manufacturing" },
        { label: "Ranching", value: "Ranching" },
        { label: "Real Estate", value: "Real Estate" },
        { label: "Real Estate Agents and Brokers", value: "Real Estate Agents and Brokers" },
        { label: "Real Estate and Equipment Rental Services", value: "Real Estate and Equipment Rental Services" },
        { label: "Recreational Facilities", value: "Recreational Facilities" },
        { label: "Religious Institutions", value: "Religious Institutions" },
        { label: "Renewable Energy Equipment Manufacturing", value: "Renewable Energy Equipment Manufacturing" },
        { label: "Renewable Energy Power Generation", value: "Renewable Energy Power Generation" },
        { label: "Renewable Energy Semiconductor Manufacturing", value: "Renewable Energy Semiconductor Manufacturing" },
        { label: "Renewables & Environment", value: "Renewables & Environment" },
        { label: "Repair and Maintenance", value: "Repair and Maintenance" },
        { label: "Research", value: "Research" },
        { label: "Research Services", value: "Research Services" },
        { label: "Residential Building Construction", value: "Residential Building Construction" },
        { label: "Restaurants", value: "Restaurants" },
        { label: "Retail", value: "Retail" },
        { label: "Retail Apparel and Fashion", value: "Retail Apparel and Fashion" },
        { label: "Retail Appliances, Electrical, and Electronic Equipment", value: "Retail Appliances, Electrical, and Electronic Equipment" },
        { label: "Retail Art Dealers", value: "Retail Art Dealers" },
        { label: "Retail Art Supplies", value: "Retail Art Supplies" },
        { label: "Retail Books and Printed News", value: "Retail Books and Printed News" },
        { label: "Retail Building Materials and Garden Equipment", value: "Retail Building Materials and Garden Equipment" },
        { label: "Retail Florists", value: "Retail Florists" },
        { label: "Retail Furniture and Home Furnishings", value: "Retail Furniture and Home Furnishings" },
        { label: "Retail Gasoline", value: "Retail Gasoline" },
        { label: "Retail Groceries", value: "Retail Groceries" },
        { label: "Retail Health and Personal Care Products", value: "Retail Health and Personal Care Products" },
        { label: "Retail Luxury Goods and Jewelry", value: "Retail Luxury Goods and Jewelry" },
        { label: "Retail Motor Vehicles", value: "Retail Motor Vehicles" },
        { label: "Retail Musical Instruments", value: "Retail Musical Instruments" },
        { label: "Retail Office Equipment", value: "Retail Office Equipment" },
        { label: "Retail Office Supplies and Gifts", value: "Retail Office Supplies and Gifts" },
        { label: "Retail Pharmacies", value: "Retail Pharmacies" },
        { label: "Retail Recyclable Materials & Used Merchandise", value: "Retail Recyclable Materials & Used Merchandise" },
        { label: "Reupholstery and Furniture Repair", value: "Reupholstery and Furniture Repair" },
        { label: "Robotics Engineering", value: "Robotics Engineering" },
        { label: "Rubber Products Manufacturing", value: "Rubber Products Manufacturing" },
        { label: "Satellite Telecommunications", value: "Satellite Telecommunications" },
        { label: "School and Employee Bus Services", value: "School and Employee Bus Services" },
        { label: "Seafood Product Manufacturing", value: "Seafood Product Manufacturing" },
        { label: "Securities and Commodity Exchanges", value: "Securities and Commodity Exchanges" },
        { label: "Security Guards and Patrol Services", value: "Security Guards and Patrol Services" },
        { label: "Security Systems Services", value: "Security Systems Services" },
        { label: "Security and Investigations", value: "Security and Investigations" },
        { label: "Semiconductor Manufacturing", value: "Semiconductor Manufacturing" },
        { label: "Semiconductors", value: "Semiconductors" },
        { label: "Services for Renewable Energy", value: "Services for Renewable Energy" },
        { label: "Services for the Elderly and Disabled", value: "Services for the Elderly and Disabled" },
        { label: "Sheet Music Publishing", value: "Sheet Music Publishing" },
        { label: "Shipbuilding", value: "Shipbuilding" },
        { label: "Shuttles and Special Needs Transportation Services", value: "Shuttles and Special Needs Transportation Services" },
        { label: "Sightseeing Transportation", value: "Sightseeing Transportation" },
        { label: "Soap and Cleaning Product Manufacturing", value: "Soap and Cleaning Product Manufacturing" },
        { label: "Social Networking Platforms", value: "Social Networking Platforms" },
        { label: "Software Development", value: "Software Development" },
        { label: "Solar Electric Power Generation", value: "Solar Electric Power Generation" },
        { label: "Sound Recording", value: "Sound Recording" },
        { label: "Space Research and Technology", value: "Space Research and Technology" },
        { label: "Specialty Trade Contractors", value: "Specialty Trade Contractors" },
        { label: "Spectator Sports", value: "Spectator Sports" },
        { label: "Sporting Goods", value: "Sporting Goods" },
        { label: "Sporting Goods Manufacturing", value: "Sporting Goods Manufacturing" },
        { label: "Sports Teams and Clubs", value: "Sports Teams and Clubs" },
        { label: "Sports and Recreation Instruction", value: "Sports and Recreation Instruction" },
        { label: "Spring and Wire Product Manufacturing", value: "Spring and Wire Product Manufacturing" },
        { label: "Staffing and Recruiting", value: "Staffing and Recruiting" },
        { label: "Steam and Air-Conditioning Supply", value: "Steam and Air-Conditioning Supply" },
        { label: "Strategic Management Services", value: "Strategic Management Services" },
        { label: "Subdivision of Land", value: "Subdivision of Land" },
        { label: "Sugar and Confectionery Product Manufacturing", value: "Sugar and Confectionery Product Manufacturing" },
        { label: "Surveying and Mapping Services", value: "Surveying and Mapping Services" },
        { label: "Taxi and Limousine Services", value: "Taxi and Limousine Services" },
        { label: "Technical and Vocational Training", value: "Technical and Vocational Training" },
        { label: "Technology, Information and Internet", value: "Technology, Information and Internet" },
        { label: "Technology, Information and Media", value: "Technology, Information and Media" },
        { label: "Telecommunications", value: "Telecommunications" },
        { label: "Telecommunications Carriers", value: "Telecommunications Carriers" },
        { label: "Telephone Call Centers", value: "Telephone Call Centers" },
        { label: "Temporary Help Services", value: "Temporary Help Services" },
        { label: "Textile Manufacturing", value: "Textile Manufacturing" },
        { label: "Theater Companies", value: "Theater Companies" },
        { label: "Think Tanks", value: "Think Tanks" },
        { label: "Tobacco", value: "Tobacco" },
        { label: "Tobacco Manufacturing", value: "Tobacco Manufacturing" },
        { label: "Translation and Localization", value: "Translation and Localization" },
        { label: "Transportation Equipment Manufacturing", value: "Transportation Equipment Manufacturing" },
        { label: "Transportation Programs", value: "Transportation Programs" },
        { label: "Transportation, Logistics, Supply Chain and Storage", value: "Transportation, Logistics, Supply Chain and Storage" },
        { label: "Transportation/Trucking/Railroad", value: "Transportation/Trucking/Railroad" },
        { label: "Travel Arrangements", value: "Travel Arrangements" },
        { label: "Truck Transportation", value: "Truck Transportation" },
        { label: "Trusts and Estates", value: "Trusts and Estates" },
        { label: "Turned Products and Fastener Manufacturing", value: "Turned Products and Fastener Manufacturing" },
        { label: "Urban Transit Services", value: "Urban Transit Services" },
        { label: "Utilities", value: "Utilities" },
        { label: "Utilities Administration", value: "Utilities Administration" },
        { label: "Utility System Construction", value: "Utility System Construction" },
        { label: "Vehicle Repair and Maintenance", value: "Vehicle Repair and Maintenance" },
        { label: "Venture Capital and Private Equity Principals", value: "Venture Capital and Private Equity Principals" },
        { label: "Veterinary", value: "Veterinary" },
        { label: "Veterinary Services", value: "Veterinary Services" },
        { label: "Vocational Rehabilitation Services", value: "Vocational Rehabilitation Services" },
        { label: "Warehousing", value: "Warehousing" },
        { label: "Warehousing and Storage", value: "Warehousing and Storage" },
        { label: "Waste Collection", value: "Waste Collection" },
        { label: "Waste Treatment and Disposal", value: "Waste Treatment and Disposal" },
        { label: "Water Supply and Irrigation Systems", value: "Water Supply and Irrigation Systems" },
        { label: "Water, Waste, Steam, and Air Conditioning Services", value: "Water, Waste, Steam, and Air Conditioning Services" },
        { label: "Wellness and Fitness Services", value: "Wellness and Fitness Services" },
        { label: "Wholesale", value: "Wholesale" },
        { label: "Wholesale Alcoholic Beverages", value: "Wholesale Alcoholic Beverages" },
        { label: "Wholesale Apparel and Sewing Supplies", value: "Wholesale Apparel and Sewing Supplies" },
        { label: "Wholesale Appliances, Electrical, and Electronics", value: "Wholesale Appliances, Electrical, and Electronics" },
        { label: "Wholesale Building Materials", value: "Wholesale Building Materials" },
        { label: "Wholesale Chemical and Allied Products", value: "Wholesale Chemical and Allied Products" },
        { label: "Wholesale Computer Equipment", value: "Wholesale Computer Equipment" },
        { label: "Wholesale Drugs and Sundries", value: "Wholesale Drugs and Sundries" },
        { label: "Wholesale Food and Beverage", value: "Wholesale Food and Beverage" },
        { label: "Wholesale Footwear", value: "Wholesale Footwear" },
        { label: "Wholesale Furniture and Home Furnishings", value: "Wholesale Furniture and Home Furnishings" },
        { label: "Wholesale Hardware, Plumbing, Heating Equipment", value: "Wholesale Hardware, Plumbing, Heating Equipment" },
        { label: "Wholesale Import and Export", value: "Wholesale Import and Export" },
        { label: "Wholesale Luxury Goods and Jewelry", value: "Wholesale Luxury Goods and Jewelry" },
        { label: "Wholesale Machinery", value: "Wholesale Machinery" },
        { label: "Wholesale Metals and Minerals", value: "Wholesale Metals and Minerals" },
        { label: "Wholesale Motor Vehicles and Parts", value: "Wholesale Motor Vehicles and Parts" },
        { label: "Wholesale Paper Products", value: "Wholesale Paper Products" },
        { label: "Wholesale Petroleum and Petroleum Products", value: "Wholesale Petroleum and Petroleum Products" },
        { label: "Wholesale Raw Farm Products", value: "Wholesale Raw Farm Products" },
        { label: "Wholesale Recyclable Materials", value: "Wholesale Recyclable Materials" },
        { label: "Wind Electric Power Generation", value: "Wind Electric Power Generation" },
        { label: "Wine and Spirits", value: "Wine and Spirits" },
        { label: "Wineries", value: "Wineries" },
        { label: "Wireless Services", value: "Wireless Services" },
        { label: "Wood Product Manufacturing", value: "Wood Product Manufacturing" },
        { label: "Writing and Editing", value: "Writing and Editing" },
        { label: "Zoos and Botanical Gardens", value: "Zoos and Botanical Gardens" },
    ],
    locationCountry: [
        { label: "Afghanistan", value: "Afghanistan" },
        { label: "Albania", value: "Albania" },
        { label: "Algeria", value: "Algeria" },
        { label: "Andorra", value: "Andorra" },
        { label: "Angola", value: "Angola" },
        { label: "Anguilla", value: "Anguilla" },
        { label: "Antarctica", value: "Antarctica" },
        { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
        { label: "Argentina", value: "Argentina" },
        { label: "Armenia", value: "Armenia" },
        { label: "Aruba", value: "Aruba" },
        { label: "Australia", value: "Australia" },
        { label: "Austria", value: "Austria" },
        { label: "Azerbaijan", value: "Azerbaijan" },
        { label: "Bahamas", value: "Bahamas" },
        { label: "Bahrain", value: "Bahrain" },
        { label: "Bangladesh", value: "Bangladesh" },
        { label: "Barbados", value: "Barbados" },
        { label: "Belarus", value: "Belarus" },
        { label: "Belgium", value: "Belgium" },
        { label: "Belize", value: "Belize" },
        { label: "Benin", value: "Benin" },
        { label: "Bermuda", value: "Bermuda" },
        { label: "Bhutan", value: "Bhutan" },
        { label: "Bolivia", value: "Bolivia" },
        { label: "Bonaire, Saint Eustatius and Saba ", value: "Bonaire, Saint Eustatius and Saba " },
        { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
        { label: "Botswana", value: "Botswana" },
        { label: "Brazil", value: "Brazil" },
        { label: "British Virgin Islands", value: "British Virgin Islands" },
        { label: "Brunei", value: "Brunei" },
        { label: "Bulgaria", value: "Bulgaria" },
        { label: "Burkina Faso", value: "Burkina Faso" },
        { label: "Burundi", value: "Burundi" },
        { label: "Cambodia", value: "Cambodia" },
        { label: "Cameroon", value: "Cameroon" },
        { label: "Canada", value: "Canada" },
        { label: "Cape Verde", value: "Cape Verde" },
        { label: "Cayman Islands", value: "Cayman Islands" },
        { label: "Central African Republic", value: "Central African Republic" },
        { label: "Chad", value: "Chad" },
        { label: "Chile", value: "Chile" },
        { label: "China", value: "China" },
        { label: "Colombia", value: "Colombia" },
        { label: "Comoros", value: "Comoros" },
        { label: "Costa Rica", value: "Costa Rica" },
        { label: "Croatia", value: "Croatia" },
        { label: "Cuba", value: "Cuba" },
        { label: "Curacao", value: "Curacao" },
        { label: "Cyprus", value: "Cyprus" },
        { label: "Czechia", value: "Czechia" },
        { label: "Democratic Republic of the Congo", value: "Democratic Republic of the Congo" },
        { label: "Denmark", value: "Denmark" },
        { label: "Djibouti", value: "Djibouti" },
        { label: "Dominican Republic", value: "Dominican Republic" },
        { label: "East Timor", value: "East Timor" },
        { label: "Ecuador", value: "Ecuador" },
        { label: "Egypt", value: "Egypt" },
        { label: "El Salvador", value: "El Salvador" },
        { label: "Equatorial Guinea", value: "Equatorial Guinea" },
        { label: "Estonia", value: "Estonia" },
        { label: "Ethiopia", value: "Ethiopia" },
        { label: "Faroe Islands", value: "Faroe Islands" },
        { label: "Fiji", value: "Fiji" },
        { label: "Finland", value: "Finland" },
        { label: "France", value: "France" },
        { label: "French Guiana", value: "French Guiana" },
        { label: "French Polynesia", value: "French Polynesia" },
        { label: "Gabon", value: "Gabon" },
        { label: "Gambia", value: "Gambia" },
        { label: "Georgia", value: "Georgia" },
        { label: "Germany", value: "Germany" },
        { label: "Ghana", value: "Ghana" },
        { label: "Gibraltar", value: "Gibraltar" },
        { label: "Greece", value: "Greece" },
        { label: "Greenland", value: "Greenland" },
        { label: "Grenada", value: "Grenada" },
        { label: "Guadeloupe", value: "Guadeloupe" },
        { label: "Guam", value: "Guam" },
        { label: "Guatemala", value: "Guatemala" },
        { label: "Guernsey", value: "Guernsey" },
        { label: "Guinea", value: "Guinea" },
        { label: "Guyana", value: "Guyana" },
        { label: "Haiti", value: "Haiti" },
        { label: "Honduras", value: "Honduras" },
        { label: "Hong Kong", value: "Hong Kong" },
        { label: "Hungary", value: "Hungary" },
        { label: "Iceland", value: "Iceland" },
        { label: "India", value: "India" },
        { label: "Indonesia", value: "Indonesia" },
        { label: "Iran", value: "Iran" },
        { label: "Iraq", value: "Iraq" },
        { label: "Ireland", value: "Ireland" },
        { label: "Isle of Man", value: "Isle of Man" },
        { label: "Israel", value: "Israel" },
        { label: "Italy", value: "Italy" },
        { label: "Ivory Coast", value: "Ivory Coast" },
        { label: "Jamaica", value: "Jamaica" },
        { label: "Japan", value: "Japan" },
        { label: "Jersey", value: "Jersey" },
        { label: "Jordan", value: "Jordan" },
        { label: "Kazakhstan", value: "Kazakhstan" },
        { label: "Kenya", value: "Kenya" },
        { label: "Kosovo", value: "Kosovo" },
        { label: "Kuwait", value: "Kuwait" },
        { label: "Kyrgyzstan", value: "Kyrgyzstan" },
        { label: "Laos", value: "Laos" },
        { label: "Latvia", value: "Latvia" },
        { label: "Lebanon", value: "Lebanon" },
        { label: "Lesotho", value: "Lesotho" },
        { label: "Liberia", value: "Liberia" },
        { label: "Libya", value: "Libya" },
        { label: "Liechtenstein", value: "Liechtenstein" },
        { label: "Lithuania", value: "Lithuania" },
        { label: "Luxembourg", value: "Luxembourg" },
        { label: "Macao", value: "Macao" },
        { label: "Macedonia", value: "Macedonia" },
        { label: "Madagascar", value: "Madagascar" },
        { label: "Malawi", value: "Malawi" },
        { label: "Malaysia", value: "Malaysia" },
        { label: "Maldives", value: "Maldives" },
        { label: "Mali", value: "Mali" },
        { label: "Malta", value: "Malta" },
        { label: "Marshall Islands", value: "Marshall Islands" },
        { label: "Martinique", value: "Martinique" },
        { label: "Mauritania", value: "Mauritania" },
        { label: "Mauritius", value: "Mauritius" },
        { label: "Mayotte", value: "Mayotte" },
        { label: "Mexico", value: "Mexico" },
        { label: "Moldova", value: "Moldova" },
        { label: "Monaco", value: "Monaco" },
        { label: "Mongolia", value: "Mongolia" },
        { label: "Montenegro", value: "Montenegro" },
        { label: "Morocco", value: "Morocco" },
        { label: "Mozambique", value: "Mozambique" },
        { label: "Myanmar", value: "Myanmar" },
        { label: "Namibia", value: "Namibia" },
        { label: "Nepal", value: "Nepal" },
        { label: "Netherlands", value: "Netherlands" },
        { label: "Netherlands Antilles", value: "Netherlands Antilles" },
        { label: "New Caledonia", value: "New Caledonia" },
        { label: "New Zealand", value: "New Zealand" },
        { label: "Nicaragua", value: "Nicaragua" },
        { label: "Niger", value: "Niger" },
        { label: "Nigeria", value: "Nigeria" },
        { label: "North Korea", value: "North Korea" },
        { label: "Northern Mariana Islands", value: "Northern Mariana Islands" },
        { label: "Norway", value: "Norway" },
        { label: "Oman", value: "Oman" },
        { label: "Pakistan", value: "Pakistan" },
        { label: "Palestinian Territory", value: "Palestinian Territory" },
        { label: "Panama", value: "Panama" },
        { label: "Papua New Guinea", value: "Papua New Guinea" },
        { label: "Paraguay", value: "Paraguay" },
        { label: "Peru", value: "Peru" },
        { label: "Philippines", value: "Philippines" },
        { label: "Poland", value: "Poland" },
        { label: "Portugal", value: "Portugal" },
        { label: "Puerto Rico", value: "Puerto Rico" },
        { label: "Qatar", value: "Qatar" },
        { label: "Republic of the Congo", value: "Republic of the Congo" },
        { label: "Reunion", value: "Reunion" },
        { label: "Romania", value: "Romania" },
        { label: "Russia", value: "Russia" },
        { label: "Rwanda", value: "Rwanda" },
        { label: "Saint Barthelemy", value: "Saint Barthelemy" },
        { label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
        { label: "Saint Lucia", value: "Saint Lucia" },
        { label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
        { label: "Samoa", value: "Samoa" },
        { label: "San Marino", value: "San Marino" },
        { label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
        { label: "Saudi Arabia", value: "Saudi Arabia" },
        { label: "Senegal", value: "Senegal" },
        { label: "Serbia", value: "Serbia" },
        { label: "Serbia and Montenegro", value: "Serbia and Montenegro" },
        { label: "Seychelles", value: "Seychelles" },
        { label: "Sierra Leone", value: "Sierra Leone" },
        { label: "Singapore", value: "Singapore" },
        { label: "Sint Maarten", value: "Sint Maarten" },
        { label: "Slovakia", value: "Slovakia" },
        { label: "Slovenia", value: "Slovenia" },
        { label: "Somalia", value: "Somalia" },
        { label: "South Africa", value: "South Africa" },
        { label: "South Korea", value: "South Korea" },
        { label: "South Sudan", value: "South Sudan" },
        { label: "Spain", value: "Spain" },
        { label: "Sri Lanka", value: "Sri Lanka" },
        { label: "Sudan", value: "Sudan" },
        { label: "Suriname", value: "Suriname" },
        { label: "Svalbard and Jan Mayen", value: "Svalbard and Jan Mayen" },
        { label: "Swaziland", value: "Swaziland" },
        { label: "Sweden", value: "Sweden" },
        { label: "Switzerland", value: "Switzerland" },
        { label: "Syria", value: "Syria" },
        { label: "Taiwan", value: "Taiwan" },
        { label: "Tajikistan", value: "Tajikistan" },
        { label: "Tanzania", value: "Tanzania" },
        { label: "Thailand", value: "Thailand" },
        { label: "Togo", value: "Togo" },
        { label: "Tonga", value: "Tonga" },
        { label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
        { label: "Tunisia", value: "Tunisia" },
        { label: "Turkey", value: "Turkey" },
        { label: "Turkmenistan", value: "Turkmenistan" },
        { label: "Turks and Caicos Islands", value: "Turks and Caicos Islands" },
        { label: "U.S. Virgin Islands", value: "U.S. Virgin Islands" },
        { label: "Uganda", value: "Uganda" },
        { label: "Ukraine", value: "Ukraine" },
        { label: "United Arab Emirates", value: "United Arab Emirates" },
        { label: "United Kingdom", value: "United Kingdom" },
        { label: "United States", value: "United States" },
        { label: "Uruguay", value: "Uruguay" },
        { label: "Uzbekistan", value: "Uzbekistan" },
        { label: "Vanuatu", value: "Vanuatu" },
        { label: "Venezuela", value: "Venezuela" },
        { label: "Vietnam", value: "Vietnam" },
        { label: "Yemen", value: "Yemen" },
        { label: "Zambia", value: "Zambia" },
        { label: "Zimbabwe", value: "Zimbabwe" },
    ],
};
