export * from './lib';

// Foundation symbols re-exported so pieces depend only on framework/common — never
// on core-*/shared directly (enforced by the community-piece import boundary lint).
export {
  isNil,
  isEmpty,
  isString,
  isNotUndefined,
  assertNotNullOrUndefined,
  apId,
  chunk,
  unique,
  pickBy,
  spreadIfDefined,
  kebabCase,
  camelCase,
  startCase,
  tryCatch,
  AIProviderName,
} from '@activepieces/core-utils';
export type { SeekPage } from '@activepieces/core-utils';

export {
  PieceCategory,
  AppConnectionType,
  MarkdownVariant,
  OAuth2GrantType,
  WebhookHandshakeStrategy,
  ExecutionType,
  AgentToolType,
  // agents / tools
  AgentTool,
  AgentFlowTool,
  AgentMcpTool,
  AgentKnowledgeBaseTool,
  AgentOutputField,
  AgentOutputFieldType,
  AgentPieceProps,
  AgentStepBlock,
  AgentTaskStatus,
  ContentBlockType,
  ExecutionToolStatus,
  KnowledgeBaseSourceType,
  MarkdownContentBlock,
  McpProtocol,
  McpAuthType,
  ToolCallContentBlock,
  ToolCallStatus,
  ToolCallType,
  TASK_COMPLETION_TOOL_NAME,
  buildAuthHeaders,
  mcpToolNameUtils,
  normalizeToolOutputToExecuteResponse,
  // ai providers
  AIProviderModel,
  AIProviderWithoutSensitiveData,
  AzureProviderConfig,
  BaseAIProviderAuthConfig,
  BedrockProviderAuthConfig,
  BedrockProviderConfig,
  CloudflareGatewayProviderConfig,
  GetProviderConfigResponse,
  OpenAICompatibleProviderConfig,
  getEffectiveProviderAndModel,
  splitCloudflareGatewayModelId,
  // mcp
  McpProperty,
  McpPropertyType,
  McpTrigger,
  // forms
  ChatFormResponse,
  FileResponseInterface,
  HumanInputFormResult,
  HumanInputFormResultTypes,
  createKeyForFormInput,
  // tables
  Table,
  Field,
  FieldType,
  Filter,
  FilterOperator,
  PopulatedRecord,
  StaticDropdownEmptyOption,
  TableWebhookEventType,
  CreateTableWebhookRequest,
  CreateRecordsRequest,
  ExportTableResponse,
  ListRecordsRequest,
  ListTablesRequest,
  UpdateRecordRequest,
  // flow contracts
  FlowStatus,
  FlowTriggerType,
  Project,
  StopResponse,
  USE_DRAFT_QUERY_PARAM_NAME,
  RAW_PAYLOAD_HEADER,
  PARENT_RUN_ID_HEADER,
  FAIL_PARENT_ON_FAILURE_HEADER,
} from '@activepieces/core-piece-types';
export type {
  McpAuthConfig,
  BasicAuthConnectionValue,
  CustomAuthConnectionValue,
  PopulatedFlowSummary,
  AgentProviderModel,
  AgentResult,
  ToolCallBase,
  ExecuteToolResponse,
  PopulatedFlow,
} from '@activepieces/core-piece-types';
