/* eslint-disable */
// Minimal `mime-db` replacement aliased into piece bundles by the bundler.
// The full mime-db is ~133 KB of MIME→extension data that `form-data`/`mime-types` pulls into
// every piece bundle that makes HTTP requests. form-data only needs it to guess a file part's
// Content-Type from its filename; for any type not listed here mime.lookup() returns false and
// form-data falls back gracefully (no/explicit Content-Type), so common uploads keep working
// while the bundle drops ~130 KB. Shape matches mime-db: { '<type>': { source, extensions, compressible, charset } }.
module.exports = {
  'application/json': { source: 'iana', charset: 'UTF-8', compressible: true, extensions: ['json', 'map'] },
  'application/xml': { source: 'iana', compressible: true, extensions: ['xml'] },
  'application/javascript': { source: 'iana', charset: 'UTF-8', compressible: true, extensions: ['js', 'mjs'] },
  'application/pdf': { source: 'iana', compressible: false, extensions: ['pdf'] },
  'application/zip': { source: 'iana', compressible: false, extensions: ['zip'] },
  'application/gzip': { source: 'iana', compressible: false, extensions: ['gz'] },
  'application/octet-stream': { source: 'iana', compressible: false, extensions: ['bin', 'dat'] },
  'application/msword': { source: 'iana', extensions: ['doc'] },
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': { source: 'iana', extensions: ['docx'] },
  'application/vnd.ms-excel': { source: 'iana', extensions: ['xls'] },
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': { source: 'iana', extensions: ['xlsx'] },
  'application/vnd.ms-powerpoint': { source: 'iana', extensions: ['ppt'] },
  'application/vnd.openxmlformats-officedocument.presentationml.presentation': { source: 'iana', extensions: ['pptx'] },
  'application/csv': { compressible: true, extensions: ['csv'] },
  'application/rtf': { source: 'iana', compressible: true, extensions: ['rtf'] },
  'application/x-tar': { source: 'apache', compressible: true, extensions: ['tar'] },
  'application/x-7z-compressed': { source: 'apache', compressible: false, extensions: ['7z'] },
  'application/wasm': { source: 'iana', compressible: true, extensions: ['wasm'] },
  'text/plain': { source: 'iana', compressible: true, charset: 'UTF-8', extensions: ['txt', 'text', 'log'] },
  'text/html': { source: 'iana', compressible: true, charset: 'UTF-8', extensions: ['html', 'htm'] },
  'text/css': { source: 'iana', compressible: true, charset: 'UTF-8', extensions: ['css'] },
  'text/csv': { source: 'iana', compressible: true, charset: 'UTF-8', extensions: ['csv'] },
  'text/markdown': { source: 'iana', compressible: true, charset: 'UTF-8', extensions: ['md', 'markdown'] },
  'text/xml': { source: 'iana', compressible: true, extensions: ['xml'] },
  'text/yaml': { compressible: true, extensions: ['yaml', 'yml'] },
  'image/png': { source: 'iana', compressible: false, extensions: ['png'] },
  'image/jpeg': { source: 'iana', compressible: false, extensions: ['jpeg', 'jpg', 'jpe'] },
  'image/gif': { source: 'iana', compressible: false, extensions: ['gif'] },
  'image/webp': { source: 'apache', compressible: false, extensions: ['webp'] },
  'image/svg+xml': { source: 'iana', compressible: true, extensions: ['svg', 'svgz'] },
  'image/bmp': { source: 'iana', compressible: true, extensions: ['bmp'] },
  'image/tiff': { source: 'iana', compressible: false, extensions: ['tiff', 'tif'] },
  'image/x-icon': { source: 'apache', compressible: true, extensions: ['ico'] },
  'image/heic': { source: 'iana', compressible: false, extensions: ['heic'] },
  'image/avif': { source: 'iana', compressible: false, extensions: ['avif'] },
  'audio/mpeg': { source: 'iana', compressible: false, extensions: ['mp3', 'mpga'] },
  'audio/wav': { compressible: false, extensions: ['wav'] },
  'audio/ogg': { source: 'iana', compressible: false, extensions: ['ogg', 'oga'] },
  'audio/webm': { source: 'apache', compressible: false, extensions: ['weba'] },
  'audio/mp4': { source: 'iana', compressible: false, extensions: ['m4a'] },
  'video/mp4': { source: 'iana', compressible: false, extensions: ['mp4', 'm4v'] },
  'video/mpeg': { source: 'iana', compressible: false, extensions: ['mpeg', 'mpg'] },
  'video/webm': { source: 'iana', compressible: false, extensions: ['webm'] },
  'video/quicktime': { source: 'iana', compressible: false, extensions: ['mov', 'qt'] },
  'video/x-msvideo': { source: 'iana', compressible: false, extensions: ['avi'] },
  'font/woff': { source: 'iana', compressible: false, extensions: ['woff'] },
  'font/woff2': { source: 'iana', compressible: false, extensions: ['woff2'] },
  'font/ttf': { source: 'iana', compressible: true, extensions: ['ttf'] },
  'font/otf': { source: 'iana', compressible: true, extensions: ['otf'] },
  'application/ld+json': { source: 'iana', compressible: true, extensions: ['jsonld'] },
  'application/x-www-form-urlencoded': { source: 'iana', compressible: true },
  'multipart/form-data': { source: 'iana' },
  'application/vnd.api+json': { source: 'iana', compressible: true },
  'application/manifest+json': { source: 'iana', charset: 'UTF-8', compressible: true, extensions: ['webmanifest'] },
  'application/ics': { compressible: true, extensions: ['ics'] },
  'text/calendar': { source: 'iana', compressible: true, extensions: ['ics', 'ifb'] },
  'application/x-ndjson': { compressible: true, extensions: ['ndjson'] },
}
