steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - -f
      - Dockerfile.poolserver
      - -t
      - europe-west1-docker.pkg.dev/activepieces-b3803/poolserver/poolserver:latest
      - .
images:
  - europe-west1-docker.pkg.dev/activepieces-b3803/poolserver/poolserver:latest
options:
  machineType: E2_HIGHCPU_8
timeout: 1800s
