"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCode = exports.ActivepiecesError = void 0;
class ActivepiecesError extends Error {
    constructor(error, message) {
        super(error.code + (message ? `: ${message}` : ''));
        this.error = error;
    }
    toString() {
        return JSON.stringify({
            code: this.error.code,
            message: this.message,
            params: this.error.params,
        });
    }
}
exports.ActivepiecesError = ActivepiecesError;
var ErrorCode;
(function (ErrorCode) {
    ErrorCode["MACHINE_NOT_CONNECTED"] = "MACHINE_NOT_CONNECTED";
    ErrorCode["MACHINE_NOT_AVAILABLE"] = "MACHINE_NOT_AVAILABLE";
    ErrorCode["INVALID_CUSTOM_DOMAIN"] = "INVALID_CUSTOM_DOMAIN";
    ErrorCode["NO_CHAT_RESPONSE"] = "NO_CHAT_RESPONSE";
    ErrorCode["ERROR_UPDATING_SUBSCRIPTION"] = "ERROR_UPDATING_SUBSCRIPTION";
    ErrorCode["AUTHENTICATION"] = "AUTHENTICATION";
    ErrorCode["AUTHORIZATION"] = "AUTHORIZATION";
    ErrorCode["PROVIDER_PROXY_CONFIG_NOT_FOUND_FOR_PROVIDER"] = "PROVIDER_PROXY_CONFIG_NOT_FOUND_FOR_PROVIDER";
    ErrorCode["AI_MODEL_NOT_SUPPORTED"] = "AI_MODEL_NOT_SUPPORTED";
    ErrorCode["AI_PROVIDER_NOT_SUPPORTED"] = "AI_PROVIDER_NOT_SUPPORTED";
    ErrorCode["AI_REQUEST_NOT_SUPPORTED"] = "AI_REQUEST_NOT_SUPPORTED";
    ErrorCode["CONFIG_NOT_FOUND"] = "CONFIG_NOT_FOUND";
    ErrorCode["DOMAIN_NOT_ALLOWED"] = "DOMAIN_NOT_ALLOWED";
    ErrorCode["EMAIL_IS_NOT_VERIFIED"] = "EMAIL_IS_NOT_VERIFIED";
    ErrorCode["ENGINE_OPERATION_FAILURE"] = "ENGINE_OPERATION_FAILURE";
    ErrorCode["ENTITY_NOT_FOUND"] = "ENTITY_NOT_FOUND";
    ErrorCode["EXECUTION_TIMEOUT"] = "EXECUTION_TIMEOUT";
    ErrorCode["MEMORY_ISSUE"] = "MEMORY_ISSUE";
    ErrorCode["TRIGGER_EXECUTION_FAILED"] = "TRIGGER_EXECUTION_FAILED";
    ErrorCode["EMAIL_AUTH_DISABLED"] = "EMAIL_AUTH_DISABLED";
    ErrorCode["EXISTING_USER"] = "EXISTING_USER";
    ErrorCode["EXISTING_ALERT_CHANNEL"] = "EXISTING_ALERT_CHANNEL";
    ErrorCode["PROJECT_EXTERNAL_ID_ALREADY_EXISTS"] = "PROJECT_EXTERNAL_ID_ALREADY_EXISTS";
    ErrorCode["FLOW_FORM_NOT_FOUND"] = "FLOW_FORM_NOT_FOUND";
    ErrorCode["FILE_NOT_FOUND"] = "FILE_NOT_FOUND";
    ErrorCode["FLOW_INSTANCE_NOT_FOUND"] = "INSTANCE_NOT_FOUND";
    ErrorCode["FLOW_NOT_FOUND"] = "FLOW_NOT_FOUND";
    ErrorCode["FLOW_OPERATION_INVALID"] = "FLOW_OPERATION_INVALID";
    ErrorCode["FLOW_OPERATION_IN_PROGRESS"] = "FLOW_OPERATION_IN_PROGRESS";
    ErrorCode["FLOW_IN_USE"] = "FLOW_IN_USE";
    ErrorCode["FLOW_RUN_NOT_FOUND"] = "FLOW_RUN_NOT_FOUND";
    ErrorCode["INVALID_API_KEY"] = "INVALID_API_KEY";
    ErrorCode["INVALID_APP_CONNECTION"] = "INVALID_APP_CONNECTION";
    ErrorCode["INVALID_BEARER_TOKEN"] = "INVALID_BEARER_TOKEN";
    ErrorCode["SESSION_EXPIRED"] = "SESSION_EXPIRED";
    ErrorCode["INVALID_CLAIM"] = "INVALID_CLAIM";
    ErrorCode["INVALID_CLOUD_CLAIM"] = "INVALID_CLOUD_CLAIM";
    ErrorCode["INVALID_CREDENTIALS"] = "INVALID_CREDENTIALS";
    ErrorCode["INVALID_OR_EXPIRED_JWT_TOKEN"] = "INVALID_OR_EXPIRED_JWT_TOKEN";
    ErrorCode["INVALID_OTP"] = "INVALID_OTP";
    ErrorCode["INVALID_SAML_RESPONSE"] = "INVALID_SAML_RESPONSE";
    ErrorCode["INVITATION_ONLY_SIGN_UP"] = "INVITATION_ONLY_SIGN_UP";
    ErrorCode["JOB_REMOVAL_FAILURE"] = "JOB_REMOVAL_FAILURE";
    ErrorCode["OPEN_AI_FAILED"] = "OPEN_AI_FAILED";
    ErrorCode["PAUSE_METADATA_MISSING"] = "PAUSE_METADATA_MISSING";
    ErrorCode["PERMISSION_DENIED"] = "PERMISSION_DENIED";
    ErrorCode["PIECE_NOT_FOUND"] = "PIECE_NOT_FOUND";
    ErrorCode["PIECE_TRIGGER_NOT_FOUND"] = "PIECE_TRIGGER_NOT_FOUND";
    ErrorCode["QUOTA_EXCEEDED"] = "QUOTA_EXCEEDED";
    ErrorCode["FEATURE_DISABLED"] = "FEATURE_DISABLED";
    ErrorCode["AI_CREDIT_LIMIT_EXCEEDED"] = "AI_CREDIT_LIMIT_EXCEEDED";
    ErrorCode["SIGN_UP_DISABLED"] = "SIGN_UP_DISABLED";
    ErrorCode["STEP_NOT_FOUND"] = "STEP_NOT_FOUND";
    ErrorCode["SYSTEM_PROP_INVALID"] = "SYSTEM_PROP_INVALID";
    ErrorCode["SYSTEM_PROP_NOT_DEFINED"] = "SYSTEM_PROP_NOT_DEFINED";
    ErrorCode["TEST_TRIGGER_FAILED"] = "TEST_TRIGGER_FAILED";
    ErrorCode["TRIGGER_UPDATE_STATUS"] = "TRIGGER_UPDATE_STATUS";
    ErrorCode["TRIGGER_FAILED"] = "TRIGGER_FAILED";
    ErrorCode["USER_IS_INACTIVE"] = "USER_IS_INACTIVE";
    ErrorCode["VALIDATION"] = "VALIDATION";
    ErrorCode["INVALID_LICENSE_KEY"] = "INVALID_LICENSE_KEY";
    ErrorCode["EMAIL_ALREADY_HAS_ACTIVATION_KEY"] = "EMAIL_ALREADY_HAS_ACTIVATION_KEY";
    ErrorCode["INVALID_SMTP_CREDENTIALS"] = "INVALID_SMTP_CREDENTIALS";
    ErrorCode["INVALID_GIT_CREDENTIALS"] = "INVALID_GIT_CREDENTIALS";
    ErrorCode["INVALID_RELEASE_TYPE"] = "INVALID_RELEASE_TYPE";
    ErrorCode["MCP_PIECE_REQUIRES_CONNECTION"] = "MCP_PIECE_REQUIRES_CONNECTION";
    ErrorCode["MCP_PIECE_CONNECTION_MISMATCH"] = "MCP_PIECE_CONNECTION_MISMATCH";
    ErrorCode["SUBFLOW_FAILED"] = "SUBFLOW_FAILED";
    ErrorCode["DOES_NOT_MEET_BUSINESS_REQUIREMENTS"] = "DOES_NOT_MEET_BUSINESS_REQUIREMENTS";
})(ErrorCode || (exports.ErrorCode = ErrorCode = {}));
//# sourceMappingURL=activepieces-error.js.map