export const enum BaserowFieldType {
  TEXT = 'text',
  BOOLEAN = 'boolean',
  LONG_TEXT = 'long_text',
  LINK_TO_TABLE = 'link_row',
  NUMBER = 'number',
  RATING = 'rating',
  DATE = 'date',
  EMAIL='email',
  DURATION = 'duration',
  LAST_MODIFIED = 'last_modified',
  LAST_MODIFIED_BY = 'last_modified_by',
  CREATED_ON = 'created_on',
  CREATED_BY = 'created_by',
  URL = 'url',
  FILE = 'file',
  SINGLE_SELECT = 'single_select',
  MULTI_SELECT = 'multiple_select',
  PHONE_NUMBER = 'phone_number',
  COUNT = 'count',
  ROLLUP = 'rollup',
  LOOKUP = 'lookup',
  MULTIPLE_COLLABORATORS = 'multiple_collaborators',
  UUID = 'uuid',
  AUTO_NUMBER = 'autonumber',
}
