export const enum BaserowFieldType {
  TEXT = 'text',
  BOOLEAN = 'boolean',
  LONG_TEXT = 'long_text',
  LINK_TO_TABLE = 'link_row',
  NUMBER = 'number',
  RATING = 'rating',
  DATE = 'date',
  EMAIL='email',
  DURATION = 'duration',
  LAST_MODIFIED = 'last_modified',
  LAST_MODIFIED_BY = 'last_modified_by',
  CREATED_ON = 'created_on',
  CREATED_BY = 'created_by',
  URL = 'url',
  FILE = 'file',
  SINGLE_SELECT = 'single_select',
  MULTI_SELECT = 'multiple_select',
  PHONE_NUMBER = 'phone_number',
  COUNT = 'count',
  ROLLUP = 'rollup',
  LOOKUP = 'lookup',
  MULTIPLE_COLLABORATORS = 'multiple_collaborators',
  UUID = 'uuid',
  AUTO_NUMBER = 'autonumber',
}

export const BASEROW_FILTER_OPERATORS = [
  { label: 'Equal', value: 'equal' },
  { label: 'Not Equal', value: 'not_equal' },
  { label: 'Contains', value: 'contains' },
  { label: 'Contains Not', value: 'contains_not' },
  { label: 'Contains Word', value: 'contains_word' },
  { label: 'Does Not Contain Word', value: 'doesnt_contain_word' },
  { label: 'Is Empty', value: 'empty' },
  { label: 'Is Not Empty', value: 'not_empty' },
  { label: 'Higher Than', value: 'higher_than' },
  { label: 'Higher Than or Equal', value: 'higher_than_or_equal' },
  { label: 'Lower Than', value: 'lower_than' },
  { label: 'Lower Than or Equal', value: 'lower_than_or_equal' },
  { label: 'Date Is', value: 'date_is' },
  { label: 'Date Is Before', value: 'date_is_before' },
  { label: 'Date Is On or Before', value: 'date_is_on_or_before' },
  { label: 'Date Is After', value: 'date_is_after' },
  { label: 'Date Is On or After', value: 'date_is_on_or_after' },
  { label: 'Date Is Within', value: 'date_is_within' },
  { label: 'Single Select Equal', value: 'single_select_equal' },
  { label: 'Single Select Not Equal', value: 'single_select_not_equal' },
  { label: 'Multiple Select Has', value: 'multiple_select_has' },
  { label: 'Multiple Select Has Not', value: 'multiple_select_has_not' },
  { label: 'Link Row Has', value: 'link_row_has' },
  { label: 'Link Row Has Not', value: 'link_row_has_not' },
  { label: 'Link Row Contains', value: 'link_row_contains' },
  { label: 'Link Row Not Contains', value: 'link_row_not_contains' },
  { label: 'Boolean', value: 'boolean' },
  { label: 'Filename Contains', value: 'filename_contains' },
  { label: 'Has File Type', value: 'has_file_type' },
  { label: 'Files Lower Than', value: 'files_lower_than' },
  { label: 'Length Is Lower Than', value: 'length_is_lower_than' },
  { label: 'Is Even And Whole', value: 'is_even_and_whole' },
];
