{
  "openapi": "3.0.0",
  "info": {
    "title": "Slack Test",
    "version": "1.0",
    "description": "OpenAPI specification generated from the Slack piece."
  },
  "servers": [
    {
      "url": "https://slack.com/api"
    }
  ],
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://slack.com/oauth/v2/authorize",
            "tokenUrl": "https://slack.com/api/oauth.v2.access",
            "scopes": {
              "channels:read": "Read channels",
              "channels:manage": "Manage channels",
              "channels:history": "View channel history",
              "chat:write": "Write messages",
              "groups:read": "Read groups",
              "groups:write": "Write to groups",
              "reactions:read": "Read reactions",
              "mpim:read": "Read multi-party IMs",
              "mpim:write": "Write to multi-party IMs",
              "im:write": "Write to IMs",
              "users:read": "Read user information",
              "files:write": "Write files",
              "files:read": "Read files",
              "users:read.email": "Read user email",
              "reactions:write": "Write reactions"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "OAuth2": [
        "channels:read",
        "channels:manage",
        "channels:history",
        "chat:write",
        "groups:read",
        "groups:write",
        "reactions:read",
        "mpim:read",
        "mpim:write",
        "im:write",
        "users:read",
        "files:write",
        "files:read",
        "users:read.email",
        "reactions:write"
      ]
    }
  ],
  "paths": {
    "/chat.postMessage": {
      "post": {
        "summary": "Send Message to a Channel",
        "operationId": "send_channel_message",
        "description": "Send a message to a specified channel"
      }
    },
    "/chat.update": {
      "post": {
        "summary": "Update Message",
        "operationId": "update_message",
        "description": "Update an existing message"
      }
    }
  }
}
