export const mockFlowVersion = {
  id: 'i48ni42W2R8QONuUPG48i',
  created: '2024-08-07T13:00:56.839Z',
  updated: '2024-08-09T09:31:29.948Z',
  flowId: 'bQLT0L1M1RQ3nCAsuR2JU',
  displayName: 'Alex .... 🪲',
  trigger: {
    name: 'trigger',
    valid: true,
    displayName: 'Every Day',
    type: 'PIECE_TRIGGER',
    settings: {
      pieceName: '@openops/piece-schedule',
      pieceVersion: '~0.1.5',
      pieceType: 'OFFICIAL',
      packageType: 'REGISTRY',
      triggerName: 'every_day',
      input: {
        timezone: 'Europe/Bucharest',
        hour_of_the_day: 9,
        run_on_weekends: false,
      },
      inputUiInfo: {
        currentSelectedData: {},
        lastTestDate: '2024-08-07T13:14:53.972Z',
      },
    },
    nextAction: {
      name: 'step_1',
      type: 'PIECE',
      valid: true,
      settings: {
        input: {
          auth: "{{connections['aws']}}",
          dryRun: false,
          regions: 'us-east-2',
          accounts: {},
          volumeTypes: [],
          shouldQueryOnlyUnattached: false,
        },
        pieceName: '@openops/piece-aws',
        pieceType: 'OFFICIAL',
        actionName: 'ebs_get_volumes',
        inputUiInfo: {
          lastTestDate:
            'Wed Aug 07 2024 12:32:50 GMT+0300 (Eastern European Summer Time)',
          customizedInputs: {
            accounts: true,
          },
          currentSelectedData: [
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-09379a025db826c0a',
              Iops: 3000,
              Size: 8,
              size: 8,
              State: 'in-use',
              region: 'us-east-2',
              VolumeId: 'vol-09379a025db826c0a',
              Encrypted: false,
              volume_id: 'vol-09379a025db826c0a',
              CreateTime: '2024-05-13T08:50:44.885Z',
              SnapshotId: 'snap-099b8832bc013861f',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [
                {
                  State: 'attached',
                  Device: '/dev/xvda',
                  VolumeId: 'vol-09379a025db826c0a',
                  AttachTime: '2024-05-13T08:50:44.000Z',
                  InstanceId: 'i-0275a67b06526029e',
                  DeleteOnTermination: true,
                },
              ],
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2b',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-0d3cbb750c9026298',
              Iops: 3000,
              Size: 8,
              size: 8,
              State: 'in-use',
              region: 'us-east-2',
              VolumeId: 'vol-0d3cbb750c9026298',
              Encrypted: false,
              volume_id: 'vol-0d3cbb750c9026298',
              CreateTime: '2023-11-27T09:15:31.421Z',
              SnapshotId: 'snap-0d2b0749ef662d398',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [
                {
                  State: 'attached',
                  Device: '/dev/xvda',
                  VolumeId: 'vol-0d3cbb750c9026298',
                  AttachTime: '2023-11-27T09:15:31.000Z',
                  InstanceId: 'i-02c3b4cb1a90f1c15',
                  DeleteOnTermination: true,
                },
              ],
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-0695db6e5bb74007e',
              Iops: 3000,
              Size: 8,
              size: 8,
              State: 'in-use',
              region: 'us-east-2',
              VolumeId: 'vol-0695db6e5bb74007e',
              Encrypted: false,
              volume_id: 'vol-0695db6e5bb74007e',
              CreateTime: '2023-11-27T09:15:31.396Z',
              SnapshotId: 'snap-0d2b0749ef662d398',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [
                {
                  State: 'attached',
                  Device: '/dev/xvda',
                  VolumeId: 'vol-0695db6e5bb74007e',
                  AttachTime: '2023-11-27T09:15:31.000Z',
                  InstanceId: 'i-0ceea28e89d69844a',
                  DeleteOnTermination: true,
                },
              ],
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-0aaad3f70add7e62c',
              Iops: 3000,
              Size: 8,
              size: 8,
              State: 'in-use',
              region: 'us-east-2',
              VolumeId: 'vol-0aaad3f70add7e62c',
              Encrypted: false,
              volume_id: 'vol-0aaad3f70add7e62c',
              CreateTime: '2023-11-27T09:15:31.445Z',
              SnapshotId: 'snap-0d2b0749ef662d398',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [
                {
                  State: 'attached',
                  Device: '/dev/xvda',
                  VolumeId: 'vol-0aaad3f70add7e62c',
                  AttachTime: '2023-11-27T09:15:31.000Z',
                  InstanceId: 'i-0e855adf27bfdbaea',
                  DeleteOnTermination: true,
                },
              ],
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-02318ef3fc5412d73',
              Iops: 3000,
              Size: 8,
              size: 8,
              State: 'in-use',
              region: 'us-east-2',
              VolumeId: 'vol-02318ef3fc5412d73',
              Encrypted: false,
              volume_id: 'vol-02318ef3fc5412d73',
              CreateTime: '2024-04-04T12:17:01.821Z',
              SnapshotId: 'snap-0d2b0749ef662d398',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [
                {
                  State: 'attached',
                  Device: '/dev/xvda',
                  VolumeId: 'vol-02318ef3fc5412d73',
                  AttachTime: '2024-04-04T12:17:01.000Z',
                  InstanceId: 'i-00389060c41309de4',
                  DeleteOnTermination: true,
                },
              ],
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-0f90f20b0e8e0c668',
              Iops: 100,
              Size: 10,
              Tags: [
                {
                  Key: 'unit',
                  Value: 'devops',
                },
                {
                  Key: 'Name',
                  Value: 'Maor1',
                },
              ],
              size: 10,
              State: 'available',
              region: 'us-east-2',
              VolumeId: 'vol-0f90f20b0e8e0c668',
              Encrypted: false,
              volume_id: 'vol-0f90f20b0e8e0c668',
              CreateTime: '2024-04-23T19:31:50.229Z',
              SnapshotId: '',
              VolumeType: 'gp2',
              account_id: '586998899304',
              Attachments: [],
              displayName: 'Maor1',
              volume_type: 'gp2',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-05ce5b43225052de8',
              Iops: 100,
              Size: 12,
              Tags: [
                {
                  Key: 'unit',
                  Value: 'rnd',
                },
                {
                  Key: 'Name',
                  Value: 'Maor3',
                },
              ],
              size: 12,
              State: 'available',
              region: 'us-east-2',
              VolumeId: 'vol-05ce5b43225052de8',
              Encrypted: false,
              volume_id: 'vol-05ce5b43225052de8',
              CreateTime: '2024-04-23T19:31:52.595Z',
              SnapshotId: '',
              VolumeType: 'gp2',
              account_id: '586998899304',
              Attachments: [],
              displayName: 'Maor3',
              volume_type: 'gp2',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-0f572d754727177d3',
              Iops: 100,
              Size: 2,
              Tags: [
                {
                  Key: 'unit',
                  Value: 'rnd',
                },
                {
                  Key: 'Name',
                  Value: 'Maor4',
                },
              ],
              size: 2,
              State: 'available',
              region: 'us-east-2',
              VolumeId: 'vol-0f572d754727177d3',
              Encrypted: false,
              volume_id: 'vol-0f572d754727177d3',
              CreateTime: '2024-04-23T19:31:53.762Z',
              SnapshotId: '',
              VolumeType: 'gp2',
              account_id: '586998899304',
              Attachments: [],
              displayName: 'Maor4',
              volume_type: 'gp2',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-01936f200951dc46c',
              Iops: 3000,
              Size: 11,
              Tags: [
                {
                  Key: 'Name',
                  Value: 'Maor2',
                },
                {
                  Key: 'unit',
                  Value: 'devops',
                },
              ],
              size: 11,
              State: 'available',
              region: 'us-east-2',
              VolumeId: 'vol-01936f200951dc46c',
              Encrypted: false,
              volume_id: 'vol-01936f200951dc46c',
              CreateTime: '2024-04-23T19:31:51.408Z',
              SnapshotId: '',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [],
              displayName: 'Maor2',
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
            {
              arn: 'arn:aws:ec2:us-east-2:586998899304:volume/vol-05c8f46f06e43270b',
              Iops: 3000,
              Size: 8,
              size: 8,
              State: 'in-use',
              region: 'us-east-2',
              VolumeId: 'vol-05c8f46f06e43270b',
              Encrypted: false,
              volume_id: 'vol-05c8f46f06e43270b',
              CreateTime: '2024-06-24T12:17:47.127Z',
              SnapshotId: 'snap-001e26806510577d1',
              Throughput: 125,
              VolumeType: 'gp3',
              account_id: '586998899304',
              Attachments: [
                {
                  State: 'attached',
                  Device: '/dev/xvda',
                  VolumeId: 'vol-05c8f46f06e43270b',
                  AttachTime: '2024-06-24T12:17:47.000Z',
                  InstanceId: 'i-00837fd8744ac3215',
                  DeleteOnTermination: true,
                },
              ],
              volume_type: 'gp3',
              account_name: 'OpenOps Main',
              AvailabilityZone: 'us-east-2a',
              MultiAttachEnabled: false,
            },
          ],
        },
        packageType: 'REGISTRY',
        pieceVersion: '~0.0.3',
        errorHandlingOptions: {
          retryOnFailure: {
            value: false,
          },
          continueOnFailure: {
            value: false,
          },
        },
      },
      nextAction: {
        name: 'step_3',
        type: 'CODE',
        valid: true,
        settings: {
          input: {},
          sourceCode: {
            code: 'export const code = async (inputs) => {\n  return inputs.ebs.map(i => i.arn).join("\\n");\n};',
            packageJson: '{}',
          },
          inputUiInfo: {
            lastTestDate: '2024-08-08T16:04:34.160Z',
            currentSelectedData:
              'arn:aws:ec2:us-east-2:586998899304:volume/vol-09379a025db826c0a\narn:aws:ec2:us-east-2:586998899304:volume/vol-0d3cbb750c9026298\narn:aws:ec2:us-east-2:586998899304:volume/vol-0695db6e5bb74007e\narn:aws:ec2:us-east-2:586998899304:volume/vol-0aaad3f70add7e62c\narn:aws:ec2:us-east-2:586998899304:volume/vol-02318ef3fc5412d73\narn:aws:ec2:us-east-2:586998899304:volume/vol-0f90f20b0e8e0c668\narn:aws:ec2:us-east-2:586998899304:volume/vol-05ce5b43225052de8\narn:aws:ec2:us-east-2:586998899304:volume/vol-0f572d754727177d3\narn:aws:ec2:us-east-2:586998899304:volume/vol-01936f200951dc46c\narn:aws:ec2:us-east-2:586998899304:volume/vol-05c8f46f06e43270b',
          },
          errorHandlingOptions: {
            retryOnFailure: {
              value: false,
            },
            continueOnFailure: {
              value: false,
            },
          },
        },
        nextAction: {
          name: 'step_2',
          type: 'SWITCH',
          valid: false,
          settings: {
            // TODO settings for switch
            conditions: [
              [
                {
                  operator: 'TEXT_CONTAINS',
                  firstValue: '',
                  secondValue: '',
                  caseSensitive: false,
                },
              ],
            ],
            inputUiInfo: {
              customizedInputs: {},
            },
          },
          switchActions: [
            {
              name: 'step_8',
              type: 'PIECE',
              valid: false,
              settings: {
                input: {},
                pieceName: '@openops/piece-aws-athena',
                pieceType: 'OFFICIAL',
                actionName: '',
                inputUiInfo: {
                  customizedInputs: {},
                },
                packageType: 'REGISTRY',
                pieceVersion: '~0.0.1',
                errorHandlingOptions: {
                  retryOnFailure: {
                    value: false,
                  },
                  continueOnFailure: {
                    value: false,
                  },
                },
              },
              displayName: 'AWS Athena',
            },
            {
              name: 'step_7',
              type: 'PIECE',
              valid: false,
              settings: {
                input: {},
                pieceName: '@openops/piece-aws',
                pieceType: 'OFFICIAL',
                actionName: '',
                inputUiInfo: {
                  customizedInputs: {},
                },
                packageType: 'REGISTRY',
                pieceVersion: '~0.0.3',
                errorHandlingOptions: {
                  retryOnFailure: {
                    value: false,
                  },
                  continueOnFailure: {
                    value: false,
                  },
                },
              },
              displayName: 'AWS',
              nextAction: null, // todo
            },
            {
              displayName: 'AWS Compute Optimizer',
              name: 'step_4',
              valid: false,
              type: 'PIECE',
              settings: {
                pieceName: '@openops/piece-aws-compute-optimizer',
                pieceType: 'OFFICIAL',
                packageType: 'REGISTRY',
                actionName: '',
                pieceVersion: '~0.0.1',
                input: {},
                errorHandlingOptions: {
                  continueOnFailure: {
                    hide: true,
                    value: false,
                  },
                  retryOnFailure: {
                    hide: true,
                    value: false,
                  },
                },
                inputUiInfo: {
                  customizedInputs: {},
                },
              },
              nextAction: {
                displayName: 'FinOps Opportunity',
                name: 'step_5',
                valid: false,
                type: 'PIECE',
                settings: {
                  pieceName: '@openops/piece-finops-opportunity',
                  pieceType: 'OFFICIAL',
                  packageType: 'REGISTRY',
                  actionName: '',
                  pieceVersion: '~0.0.1',
                  input: {},
                  errorHandlingOptions: {
                    continueOnFailure: {
                      hide: true,
                      value: false,
                    },
                    retryOnFailure: {
                      hide: true,
                      value: false,
                    },
                  },
                  inputUiInfo: {
                    customizedInputs: {},
                  },
                },
              },
            },
          ],
          nextAction: {
            name: 'step_6',
            type: 'PIECE',
            valid: true,
            settings: {
              input: {},
              pieceName: '@openops/piece-end-flow',
              pieceType: 'OFFICIAL',
              actionName: 'end_workflow',
              inputUiInfo: {
                lastTestDate: '2024-08-08T17:16:06.749Z',
                customizedInputs: {},
              },
              packageType: 'REGISTRY',
              pieceVersion: '~0.0.1',
              errorHandlingOptions: {
                retryOnFailure: {
                  value: false,
                },
                continueOnFailure: {
                  value: false,
                },
              },
            },
            displayName: 'End Workflow',
          },
          displayName: 'Switch',
        },
        displayName: 'Code',
      },
      displayName: 'EBS Get Volumes',
    },
  },
  valid: false,
  state: 'DRAFT',
  updatedBy: 'aDG1NPlCwKYggC7ONtUpE',
};
