import { MigrationInterface, QueryRunner } from 'typeorm'
import { logger } from '../../../../helper/logger'

export class FlowTemplateAddUserIdAndImageUrl1694380048802 implements MigrationInterface {
    name = 'FlowTemplateAddUserIdAndImageUrl1694380048802'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('CREATE TABLE "temporary_flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, CONSTRAINT "fk_flow_template_project_id" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)')
        await queryRunner.query('INSERT INTO "temporary_flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl" FROM "flow_template"')
        await queryRunner.query('DROP TABLE "flow_template"')
        await queryRunner.query('ALTER TABLE "temporary_flow_template" RENAME TO "flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('CREATE TABLE "temporary_flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar, CONSTRAINT "fk_flow_template_project_id" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)')
        await queryRunner.query('INSERT INTO "temporary_flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl" FROM "flow_template"')
        await queryRunner.query('DROP TABLE "flow_template"')
        await queryRunner.query('ALTER TABLE "temporary_flow_template" RENAME TO "flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('CREATE TABLE "temporary_flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar)')
        await queryRunner.query('INSERT INTO "temporary_flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl" FROM "flow_template"')
        await queryRunner.query('DROP TABLE "flow_template"')
        await queryRunner.query('ALTER TABLE "temporary_flow_template" RENAME TO "flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('CREATE TABLE "temporary_flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar NOT NULL, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar)')
        await queryRunner.query('INSERT INTO "temporary_flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl" FROM "flow_template"')
        await queryRunner.query('DROP TABLE "flow_template"')
        await queryRunner.query('ALTER TABLE "temporary_flow_template" RENAME TO "flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('CREATE TABLE "temporary_flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar NOT NULL, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar, CONSTRAINT "fk_flow_template_project_id" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "fk_flow_template_user_id" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)')
        await queryRunner.query('INSERT INTO "temporary_flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl" FROM "flow_template"')
        await queryRunner.query('DROP TABLE "flow_template"')
        await queryRunner.query('ALTER TABLE "temporary_flow_template" RENAME TO "flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')

        logger.info('FlowTemplateAddUserIdAndImageUrl1694380048802 up')
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('ALTER TABLE "flow_template" RENAME TO "temporary_flow_template"')
        await queryRunner.query('CREATE TABLE "flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar NOT NULL, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar)')
        await queryRunner.query('INSERT INTO "flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl" FROM "temporary_flow_template"')
        await queryRunner.query('DROP TABLE "temporary_flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('ALTER TABLE "flow_template" RENAME TO "temporary_flow_template"')
        await queryRunner.query('CREATE TABLE "flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar)')
        await queryRunner.query('INSERT INTO "flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl" FROM "temporary_flow_template"')
        await queryRunner.query('DROP TABLE "temporary_flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('ALTER TABLE "flow_template" RENAME TO "temporary_flow_template"')
        await queryRunner.query('CREATE TABLE "flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, "userId" varchar, "imageUrl" varchar, CONSTRAINT "fk_flow_template_project_id" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)')
        await queryRunner.query('INSERT INTO "flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl", "userId", "imageUrl" FROM "temporary_flow_template"')
        await queryRunner.query('DROP TABLE "temporary_flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('ALTER TABLE "flow_template" RENAME TO "temporary_flow_template"')
        await queryRunner.query('CREATE TABLE "flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "blogUrl" varchar, CONSTRAINT "fk_flow_template_project_id" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)')
        await queryRunner.query('INSERT INTO "flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl" FROM "temporary_flow_template"')
        await queryRunner.query('DROP TABLE "temporary_flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')
        await queryRunner.query('DROP INDEX "idx_flow_template_pieces"')
        await queryRunner.query('DROP INDEX "idx_flow_template_tags"')
        await queryRunner.query('ALTER TABLE "flow_template" RENAME TO "temporary_flow_template"')
        await queryRunner.query('CREATE TABLE "flow_template" ("id" varchar(21) PRIMARY KEY NOT NULL, "created" datetime NOT NULL DEFAULT (datetime(\'now\')), "updated" datetime NOT NULL DEFAULT (datetime(\'now\')), "name" varchar NOT NULL, "description" varchar NOT NULL, "projectId" varchar, "template" text NOT NULL, "tags" varchar array NOT NULL, "pieces" varchar array NOT NULL, "pinnedOrder" integer, "blogUrl" varchar, CONSTRAINT "fk_flow_template_project_id" FOREIGN KEY ("projectId") REFERENCES "project" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)')
        await queryRunner.query('INSERT INTO "flow_template"("id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl") SELECT "id", "created", "updated", "name", "description", "projectId", "template", "tags", "pieces", "blogUrl" FROM "temporary_flow_template"')
        await queryRunner.query('DROP TABLE "temporary_flow_template"')
        await queryRunner.query('CREATE INDEX "idx_flow_template_pieces" ON "flow_template" ("pieces") ')
        await queryRunner.query('CREATE INDEX "idx_flow_template_tags" ON "flow_template" ("tags") ')

        logger.info('FlowTemplateAddUserIdAndImageUrl1694380048802 down')
    }

}
