import { OutputSchema } from '@activepieces/pieces-framework';

import { reportFiltersFields, reportsFields } from '../../../output-schemas';

export const mauticCreateReportOutputSchema: OutputSchema = {
	fields: [
		{
			key: 'report',
			label: 'Report',
			children: [
				{ key: 'id', label: 'ID', format: 'number' },
				{ key: 'name', label: 'Name' },
				{ key: 'description', label: 'Description' },
				{ key: 'system', label: 'System', format: 'boolean' },
				{ key: 'isScheduled', label: 'Is Scheduled', format: 'boolean' },
				{ key: 'source', label: 'Source' },
				{ key: 'columns', label: 'Columns' },
				{ key: 'filters', label: 'Filters', listItems: reportFiltersFields },
				{ key: 'tableOrder', label: 'Table Order' },
				{ key: 'graphs', label: 'Graphs' },
				{ key: 'groupBy', label: 'Group By' },
				{
					key: 'settings',
					label: 'Settings',
					children: [
						{ key: 'showGraphsAboveTable', label: 'Show Graphs Above Table' },
						{ key: 'showDynamicFilters', label: 'Show Dynamic Filters' },
						{ key: 'hideDateRangeFilter', label: 'Hide Date Range Filter' },
					],
				},
				{ key: 'aggregators', label: 'Aggregators' },
				{ key: 'scheduleUnit', label: 'Schedule Unit' },
				{ key: 'toAddress', label: 'To Address' },
				{ key: 'scheduleDay', label: 'Schedule Day' },
				{ key: 'scheduleMonthFrequency', label: 'Schedule Month Frequency' },
			],
		},
	],
};

export const mauticDeleteReportOutputSchema: OutputSchema = {
	fields: [
		{
			key: 'report',
			label: 'Report',
			children: [
				{ key: 'id', label: 'ID' },
				{ key: 'name', label: 'Name' },
				{ key: 'description', label: 'Description' },
				{ key: 'system', label: 'System', format: 'boolean' },
				{ key: 'isScheduled', label: 'Is Scheduled', format: 'boolean' },
				{ key: 'source', label: 'Source' },
				{ key: 'columns', label: 'Columns' },
				{ key: 'filters', label: 'Filters', listItems: reportFiltersFields },
				{ key: 'tableOrder', label: 'Table Order' },
				{ key: 'graphs', label: 'Graphs' },
				{ key: 'groupBy', label: 'Group By' },
				{
					key: 'settings',
					label: 'Settings',
					children: [
						{ key: 'showDynamicFilters', label: 'Show Dynamic Filters' },
						{ key: 'hideDateRangeFilter', label: 'Hide Date Range Filter' },
						{ key: 'showGraphsAboveTable', label: 'Show Graphs Above Table' },
					],
				},
				{ key: 'aggregators', label: 'Aggregators' },
				{ key: 'scheduleUnit', label: 'Schedule Unit' },
				{ key: 'toAddress', label: 'To Address' },
				{ key: 'scheduleDay', label: 'Schedule Day' },
				{ key: 'scheduleMonthFrequency', label: 'Schedule Month Frequency' },
			],
		},
	],
};

export const mauticGetDashboardWidgetDataOutputSchema: OutputSchema = {
	fields: [
		{ key: 'success', label: 'Success', format: 'number' },
		{ key: 'cached', label: 'Cached', format: 'boolean' },
		{ key: 'execution_time', label: 'Execution Time', format: 'number' },
		{
			key: 'data',
			label: 'Data',
			children: [
				{ key: 'chartType', label: 'Chart Type' },
				{ key: 'chartHeight', label: 'Chart Height', format: 'number' },
				{
					key: 'chartData',
					label: 'Chart Data',
					children: [
						{ key: 'labels', label: 'Labels' },
						{
							key: 'datasets',
							label: 'Datasets',
							labelKey: 'label',
							listItems: [
								{ key: 'label', label: 'Label' },
								{ key: 'data', label: 'Data' },
								{ key: 'backgroundColor', label: 'Background Color' },
								{ key: 'borderColor', label: 'Border Color' },
								{ key: 'pointHoverBackgroundColor', label: 'Point Hover Background Color' },
								{ key: 'pointHoverBorderColor', label: 'Point Hover Border Color' },
								{ key: 'hoverBackgroundColor', label: 'Hover Background Color' },
							],
						},
					],
				},
			],
		},
	],
};

export const mauticGetReportOutputSchema: OutputSchema = {
	fields: [
		{ key: 'totalResults', label: 'Total Results', format: 'number' },
		{
			key: 'data',
			label: 'Data',
			labelKey: 'email',
			listItems: [
				{ key: 'id', label: 'ID' },
				{ key: 'email', label: 'Email', format: 'email' },
				{ key: 'firstname', label: 'First Name' },
			],
		},
		{
			key: 'dataColumns',
			label: 'Data Columns',
			children: [
				{ key: 'address1', label: 'Address 1' },
				{ key: 'address2', label: 'Address 2' },
				{ key: 'attribution', label: 'Attribution' },
				{ key: 'attribution_date', label: 'Attribution Date' },
				{ key: 'city', label: 'City' },
				{ key: 'companyaddress1', label: 'Company Address 1' },
				{ key: 'companyaddress2', label: 'Company Address 2' },
				{ key: 'companyannual_revenue', label: 'Company Annual Revenue' },
				{ key: 'companycity', label: 'Company City' },
				{ key: 'companyemail', label: 'Company Email' },
				{ key: 'companyname', label: 'Company Name' },
				{ key: 'companycountry', label: 'Company Country' },
				{ key: 'companydescription', label: 'Company Description' },
				{ key: 'companyfax', label: 'Company Fax' },
				{ key: 'comp_id', label: 'Comp ID' },
				{ key: 'companyindustry', label: 'Company Industry' },
				{ key: 'companynumber_of_employees', label: 'Company Number of Employees' },
				{ key: 'companyphone', label: 'Company Phone' },
				{ key: 'companystate', label: 'Company State' },
				{ key: 'companywebsite', label: 'Company Website' },
				{ key: 'companyzipcode', label: 'Company Zip Code' },
				{ key: 'id', label: 'ID' },
				{ key: 'country', label: 'Country' },
				{ key: 'date_added', label: 'Date Added' },
				{ key: 'last_active', label: 'Last Active' },
				{ key: 'date_added1', label: 'Date Added1' },
				{ key: 'date_identified', label: 'Date Identified' },
				{ key: 'email', label: 'Email' },
				{ key: 'facebook', label: 'Facebook' },
				{ key: 'fax', label: 'Fax' },
				{ key: 'firstname', label: 'First Name' },
				{ key: 'foursquare', label: 'Foursquare' },
				{ key: 'ip_address', label: 'IP Address' },
				{ key: 'instagram', label: 'Instagram' },
				{ key: 'is_primary', label: 'Is Primary' },
				{ key: 'lastname', label: 'Last Name' },
				{ key: 'linkedin', label: 'LinkedIn' },
				{ key: 'mobile', label: 'Mobile' },
				{ key: 'owner_id', label: 'Owner ID' },
				{ key: 'first_name', label: 'First Name' },
				{ key: 'last_name', label: 'Last Name' },
				{ key: 'phone', label: 'Phone' },
				{ key: 'points', label: 'Points' },
				{ key: 'position', label: 'Position' },
				{ key: 'preferred_locale', label: 'Preferred Locale' },
				{ key: 'timezone', label: 'Timezone' },
				{ key: 'company', label: 'Company' },
				{ key: 'skype', label: 'Skype' },
				{ key: 'stage_date_added', label: 'Stage Date Added' },
				{ key: 'stage_id', label: 'Stage ID' },
				{ key: 'stage_name', label: 'Stage Name' },
				{ key: 'state', label: 'State' },
				{ key: 'title', label: 'Title' },
				{ key: 'twitter', label: 'Twitter' },
				{ key: 'website', label: 'Website' },
				{ key: 'zipcode', label: 'Zip Code' },
				{ key: 'variant_hits', label: 'Variant Hits' },
				{ key: 'variant_start_date', label: 'Variant Start Date' },
				{ key: 'alias', label: 'Alias' },
				{ key: 'name', label: 'Name' },
				{ key: 'campaign_id', label: 'Campaign ID' },
				{ key: 'category_id', label: 'Category ID' },
				{ key: 'category_title', label: 'Category Title' },
				{ key: 'contactId', label: 'Contact ID' },
				{ key: 'title1', label: 'Title1' },
				{ key: 'p_created_by_user', label: 'P Created By User' },
				{ key: 'p_date_added', label: 'P Date Added' },
				{ key: 'date_hit', label: 'Date Hit' },
				{ key: 'p_date_modified', label: 'P Date Modified' },
				{ key: 'date_left', label: 'Date Left' },
				{ key: 'device', label: 'Device' },
				{ key: 'device_os_name', label: 'Device Os Name' },
				{ key: 'device_os_platform', label: 'Device Os Platform' },
				{ key: 'device_os_shortname', label: 'Device Os Shortname' },
				{ key: 'device_os_version', label: 'Device Os Version' },
				{ key: 'device_brand', label: 'Device Brand' },
				{ key: 'device_model', label: 'Device Model' },
				{ key: 'isp', label: 'Isp' },
				{ key: 'url', label: 'URL' },
				{ key: 'browser_languages', label: 'Browser Languages' },
				{ key: 'city1', label: 'City1' },
				{ key: 'code', label: 'Code' },
				{ key: 'hits', label: 'Hits' },
				{ key: 'country1', label: 'Country1' },
				{ key: 'organization', label: 'Organization' },
				{ key: 'url_title', label: 'URL Title' },
				{ key: 'referer', label: 'Referer' },
				{ key: 'region', label: 'Region' },
				{ key: 'remote_host', label: 'Remote Host' },
				{ key: 'user_agent', label: 'User Agent' },
				{ key: 'p_id', label: 'P ID' },
				{ key: 'p_is_published', label: 'P Is Published' },
				{ key: 'lang', label: 'Lang' },
				{ key: 'p_modified_by_user', label: 'P Modified By User' },
				{ key: 'source', label: 'Source' },
				{ key: 'source_id', label: 'Source ID' },
				{ key: 'id1', label: 'Id1' },
				{ key: 'url1', label: 'Url1' },
				{ key: 'hits1', label: 'Hits1' },
				{ key: 'unique_hits', label: 'Unique Hits' },
				{ key: 'revision', label: 'Revision' },
				{ key: 'p_publish_up', label: 'P Publish Up' },
				{ key: 'p_publish_down', label: 'P Publish Down' },
				{ key: 'title2', label: 'Title2' },
				{ key: 'id2', label: 'Id2' },
				{ key: 'title3', label: 'Title3' },
				{ key: 'unique_hits1', label: 'Unique Hits1' },
			],
		},
		{ key: 'limit', label: 'Limit', format: 'number' },
		{ key: 'page', label: 'Page', format: 'number' },
		{ key: 'debug', label: 'Debug' },
		{ key: 'aggregatorColumns', label: 'Aggregator Columns' },
		{
			key: 'report',
			label: 'Report',
			children: [
				{ key: 'isPublished', label: 'Published', format: 'boolean' },
				{ key: 'dateAdded', label: 'Date Added', format: 'datetime' },
				{ key: 'id', label: 'ID', format: 'number' },
				{ key: 'name', label: 'Name' },
				{ key: 'description', label: 'Description' },
				{ key: 'system', label: 'System', format: 'boolean' },
				{ key: 'isScheduled', label: 'Is Scheduled', format: 'boolean' },
				{ key: 'source', label: 'Source' },
				{ key: 'columns', label: 'Columns' },
				{
					key: 'filters',
					label: 'Filters',
					listItems: [
						{ key: 'column', label: 'Column' },
						{ key: 'condition', label: 'Condition' },
						{ key: 'value', label: 'Value' },
					],
				},
				{
					key: 'tableOrder',
					label: 'Table Order',
					listItems: [
						{ key: 'column', label: 'Column' },
						{ key: 'direction', label: 'Direction' },
					],
				},
				{ key: 'graphs', label: 'Graphs' },
				{ key: 'groupBy', label: 'Group By' },
				{ key: 'settings', label: 'Settings' },
				{ key: 'aggregators', label: 'Aggregators' },
				{ key: 'dateModified', label: 'Date Modified', format: 'datetime' },
			],
		},
		{ key: 'dateFrom', label: 'Date From', format: 'datetime' },
		{ key: 'dateTo', label: 'Date To', format: 'datetime' },
	],
};

export const mauticGetStatsOutputSchema: OutputSchema = {
	fields: [
		{ key: 'total', label: 'Total' },
		{ key: 'stats', label: 'Stats' },
		{ key: 'availableTables', label: 'Available Tables' },
		{
			key: 'tableColumns',
			label: 'Table Columns',
			children: [
				{ key: 'asset_downloads', label: 'Asset Downloads' },
				{ key: 'audit_log', label: 'Audit Log' },
				{ key: 'campaign_lead_event_log', label: 'Campaign Lead Event Log' },
				{ key: 'campaign_leads', label: 'Campaign Leads' },
				{ key: 'channel_url_trackables', label: 'Channel URL Trackables' },
				{ key: 'companies_leads', label: 'Companies Leads' },
				{ key: 'dynamic_content_lead_data', label: 'Dynamic Content Lead Data' },
				{ key: 'dynamic_content_stats', label: 'Dynamic Content Stats' },
				{ key: 'email_stat_replies', label: 'Email Stat Replies' },
				{ key: 'email_stats', label: 'Email Stats' },
				{ key: 'email_stats_devices', label: 'Email Stats Devices' },
				{ key: 'focus_stats', label: 'Focus Stats' },
				{ key: 'form_submissions', label: 'Form Submissions' },
				{ key: 'ip_addresses', label: 'IP Addresses' },
				{ key: 'lead_categories', label: 'Lead Categories' },
				{ key: 'lead_companies_change_log', label: 'Lead Companies Change Log' },
				{ key: 'lead_devices', label: 'Lead Devices' },
				{ key: 'lead_donotcontact', label: 'Lead Donotcontact' },
				{ key: 'lead_event_log', label: 'Lead Event Log' },
				{ key: 'lead_frequencyrules', label: 'Lead Frequencyrules' },
				{ key: 'lead_lists_leads', label: 'Lead Lists Leads' },
				{ key: 'lead_points_change_log', label: 'Lead Points Change Log' },
				{ key: 'lead_stages_change_log', label: 'Lead Stages Change Log' },
				{ key: 'lead_utmtags', label: 'Lead Utmtags' },
				{ key: 'page_hits', label: 'Page Hits' },
				{ key: 'page_redirects', label: 'Page Redirects' },
				{ key: 'point_lead_action_log', label: 'Point Lead Action Log' },
				{ key: 'point_lead_event_log', label: 'Point Lead Event Log' },
				{ key: 'push_notification_stats', label: 'Push Notification Stats' },
				{ key: 'sms_message_stats', label: 'Sms Message Stats' },
				{ key: 'stage_lead_action_log', label: 'Stage Lead Action Log' },
				{ key: 'tweet_stats', label: 'Tweet Stats' },
				{ key: 'video_hits', label: 'Video Hits' },
				{ key: 'webhook_logs', label: 'Webhook Logs' },
			],
		},
	],
};

export const mauticListDashboardWidgetTypesOutputSchema: OutputSchema = {
	fields: [
		{ key: 'success', label: 'Success', format: 'number' },
		{
			key: 'types',
			label: 'Types',
			children: [
				{
					key: 'Asset Widgets',
					label: 'Asset Widgets',
					children: [
						{
							key: 'asset.downloads.in.time',
							label: 'Asset Downloads In Time',
							value: "['asset.downloads.in.time']",
						},
						{
							key: 'unique.vs.repetitive.downloads',
							label: 'Unique Vs Repetitive Downloads',
							value: "['unique.vs.repetitive.downloads']",
						},
						{ key: 'popular.assets', label: 'Popular Assets', value: "['popular.assets']" },
						{ key: 'created.assets', label: 'Created Assets', value: "['created.assets']" },
					],
				},
				{
					key: 'Campaign Widgets',
					label: 'Campaign Widgets',
					children: [
						{ key: 'events.in.time', label: 'Events In Time', value: "['events.in.time']" },
						{
							key: 'leads.added.in.time',
							label: 'Leads Added In Time',
							value: "['leads.added.in.time']",
						},
					],
				},
				{
					key: 'Core Widgets',
					label: 'Core Widgets',
					children: [
						{ key: 'recent.activity', label: 'Recent Activity', value: "['recent.activity']" },
					],
				},
				{
					key: 'Email Widgets',
					label: 'Email Widgets',
					children: [
						{
							key: 'emails.best.hours',
							label: 'Emails Best Hours',
							value: "['emails.best.hours']",
						},
						{ key: 'emails.in.time', label: 'Emails In Time', value: "['emails.in.time']" },
						{
							key: 'sent.email.to.contacts',
							label: 'Sent Email To Contacts',
							value: "['sent.email.to.contacts']",
						},
						{
							key: 'most.hit.email.redirects',
							label: 'Most Hit Email Redirects',
							value: "['most.hit.email.redirects']",
						},
						{
							key: 'ignored.vs.read.emails',
							label: 'Ignored Vs Read Emails',
							value: "['ignored.vs.read.emails']",
						},
						{ key: 'upcoming.emails', label: 'Upcoming Emails', value: "['upcoming.emails']" },
						{ key: 'most.sent.emails', label: 'Most Sent Emails', value: "['most.sent.emails']" },
						{ key: 'most.read.emails', label: 'Most Read Emails', value: "['most.read.emails']" },
						{ key: 'created.emails', label: 'Created Emails', value: "['created.emails']" },
						{
							key: 'device.granularity.email',
							label: 'Device Granularity Email',
							value: "['device.granularity.email']",
						},
					],
				},
				{
					key: 'Form Widgets',
					label: 'Form Widgets',
					children: [
						{
							key: 'submissions.in.time',
							label: 'Submissions In Time',
							value: "['submissions.in.time']",
						},
						{
							key: 'top.submission.referrers',
							label: 'Top Submission Referrers',
							value: "['top.submission.referrers']",
						},
						{ key: 'top.submitters', label: 'Top Submitters', value: "['top.submitters']" },
						{ key: 'created.forms', label: 'Created Forms', value: "['created.forms']" },
					],
				},
				{
					key: 'Contact Widgets',
					label: 'Contact Widgets',
					children: [
						{
							key: 'created.leads.in.time',
							label: 'Created Leads In Time',
							value: "['created.leads.in.time']",
						},
						{
							key: 'anonymous.vs.identified.leads',
							label: 'Anonymous Vs Identified Leads',
							value: "['anonymous.vs.identified.leads']",
						},
						{ key: 'lead.lifetime', label: 'Lead Lifetime', value: "['lead.lifetime']" },
						{ key: 'map.of.leads', label: 'Map Of Leads', value: "['map.of.leads']" },
						{ key: 'top.lists', label: 'Top Lists', value: "['top.lists']" },
						{
							key: 'segments.build.time',
							label: 'Segments Build Time',
							value: "['segments.build.time']",
						},
						{ key: 'top.creators', label: 'Top Creators', value: "['top.creators']" },
						{ key: 'top.owners', label: 'Top Owners', value: "['top.owners']" },
						{ key: 'created.leads', label: 'Created Leads', value: "['created.leads']" },
					],
				},
				{
					key: 'Page Widgets',
					label: 'Page Widgets',
					children: [
						{
							key: 'page.hits.in.time',
							label: 'Page Hits In Time',
							value: "['page.hits.in.time']",
						},
						{
							key: 'unique.vs.returning.leads',
							label: 'Unique Vs Returning Leads',
							value: "['unique.vs.returning.leads']",
						},
						{ key: 'dwell.times', label: 'Dwell Times', value: "['dwell.times']" },
						{ key: 'popular.pages', label: 'Popular Pages', value: "['popular.pages']" },
						{ key: 'created.pages', label: 'Created Pages', value: "['created.pages']" },
						{
							key: 'device.granularity',
							label: 'Device Granularity',
							value: "['device.granularity']",
						},
					],
				},
				{
					key: 'Point Widgets',
					label: 'Point Widgets',
					children: [
						{ key: 'points.in.time', label: 'Points In Time', value: "['points.in.time']" },
					],
				},
				{
					key: 'Report Widgets',
					label: 'Report Widgets',
					children: [{ key: 'report', label: 'Report' }],
				},
				{
					key: 'Stage Widgets',
					label: 'Stage Widgets',
					children: [
						{ key: 'stages.in.time', label: 'Stages In Time', value: "['stages.in.time']" },
					],
				},
			],
		},
	],
};

export const mauticListReportsOutputSchema: OutputSchema = {
	fields: [
		{ key: 'total', label: 'Total', format: 'number' },
		{ key: 'reports', label: 'Reports', labelKey: 'name', listItems: reportsFields },
	],
};

export const mauticUpdateReportOutputSchema: OutputSchema = {
	fields: [{ key: 'report', label: 'Report', children: reportsFields }],
};
