import { createPiece, PieceCategory } from '@activepieces/pieces-framework';
import {
	addBarcodeToPdf,
	addImageToPdf,
	addPasswordToPdf,
	addTextToPdf,
	checkJobStatus,
	compressPdf,
	convertDocumentToPdf,
	convertHtmlTemplateToPdf,
	convertHtmlToPdf,
	convertPdfToImage,
	convertPdfToStructuredFormat,
	convertUrlToPdf,
	deletePdfPages,
	deleteTextFromPdf,
	extractTablesFromPdf,
	extractTextFromPdf,
	fillPdfForm,
	findTextInPdf,
	generateBarcode,
	getCreditBalance,
	getPdfFormFields,
	getPdfInfo,
	listDocumentParserTemplates,
	listHtmlTemplates,
	makePdfSearchable,
	mergePdfs,
	parseDocument,
	parseInvoiceWithAi,
	pdfCoConvertPdf,
	pdfCoEditPdf,
	pdfCoParseDocument,
	readBarcodes,
	removePasswordFromPdf,
	rotatePdfPages,
	searchAndReplaceText,
	splitPdf,
	uploadFile,
} from './lib/actions';
import { pdfCoAuth } from './lib/auth';

export const pdfCo = createPiece({
	displayName: 'PDF.co',
	description: 'Automate PDF conversion, editing, extraction',
	categories: [PieceCategory.PRODUCTIVITY, PieceCategory.CONTENT_AND_FILES],
	logoUrl: 'https://cdn.activepieces.com/pieces/pdf-co.png',
	auth: pdfCoAuth,
	minimumSupportedRelease: '0.88.2',
	authors: ['onyedikachi-david', 'kishanprmr'],
	actions: [
		addBarcodeToPdf,
		addImageToPdf,
		addTextToPdf,
		convertHtmlToPdf,
		convertPdfToStructuredFormat,
		extractTablesFromPdf,
		extractTextFromPdf,
		searchAndReplaceText,
		mergePdfs,
		splitPdf,
		deletePdfPages,
		rotatePdfPages,
		compressPdf,
		addPasswordToPdf,
		removePasswordFromPdf,
		makePdfSearchable,
		getPdfInfo,
		getPdfFormFields,
		fillPdfForm,
		findTextInPdf,
		deleteTextFromPdf,
		readBarcodes,
		generateBarcode,
		convertPdfToImage,
		convertUrlToPdf,
		convertDocumentToPdf,
		convertHtmlTemplateToPdf,
		listHtmlTemplates,
		parseDocument,
		listDocumentParserTemplates,
		parseInvoiceWithAi,
		uploadFile,
		checkJobStatus,
		getCreditBalance,
		pdfCoConvertPdf,
		pdfCoEditPdf,
		pdfCoParseDocument,
	],
	triggers: [],
});
