export enum PropertyType {
	SHORT_TEXT = 'SHORT_TEXT',
	LONG_TEXT = 'LONG_TEXT',
	DROPDOWN = 'DROPDOWN',
	NUMBER = 'NUMBER',
	CHECKBOX = 'CHECKBOX',
	OAUTH2 = 'OAUTH2',
	SECRET_TEXT = 'SECRET_TEXT',
	ARRAY = 'ARRAY',
	OBJECT = 'OBJECT',
	BASIC_AUTH = "BASIC_AUTH",
	JSON = 'JSON',
}
