import { PlanName } from "@activepieces/ee-shared"
import { PiecesFilterType, PlatformPlanLimits } from "@activepieces/shared"

export const FREE_CLOUD_PLAN: PlatformPlanLimits = {
    tasksLimit: 1000,
    includedTasks: 1000,
    aiCreditsLimit: 100,
    includedAiCredits: 100,
    activeFlowsLimit: 2,
    userSeatsLimit: 1,
    projectsLimit: 1,
    tablesLimit: 1,
    mcpLimit: 1,

    tablesEnabled: true,
    todosEnabled: true,

    embeddingEnabled: false,
    globalConnectionsEnabled: false,
    customRolesEnabled: false,
    environmentsEnabled: false,
    analyticsEnabled: false,
    showPoweredBy: false,
    auditLogEnabled: false,
    managePiecesEnabled: false,
    manageTemplatesEnabled: false,
    customAppearanceEnabled: false,
    manageProjectsEnabled: false,
    projectRolesEnabled: false,
    customDomainsEnabled: false,
    apiKeysEnabled: false,
    alertsEnabled: false,
    ssoEnabled: false,
}

export const PLUS_CLOUD_PLAN: PlatformPlanLimits = {
    includedTasks: 1000000,
    aiCreditsLimit: 500,
    includedAiCredits: 500,
    activeFlowsLimit: 10,
    userSeatsLimit: 1,
    projectsLimit: 1,
    mcpLimit: 5,

    tablesEnabled: true,
    todosEnabled: true,

    embeddingEnabled: false,
    globalConnectionsEnabled: false,
    customRolesEnabled: false,
    environmentsEnabled: false,
    analyticsEnabled: false,
    managePiecesEnabled: false,
    manageTemplatesEnabled: false,
    customAppearanceEnabled: false,
    manageProjectsEnabled: false,
    projectRolesEnabled: false,
    customDomainsEnabled: false,
    apiKeysEnabled: false,
    alertsEnabled: false,
    ssoEnabled: false,
    showPoweredBy: false,
    auditLogEnabled: false,
}


export const BUSINESS_CLOUD_PLAN: PlatformPlanLimits = {
    includedTasks: 1000000,
    aiCreditsLimit: 1000,
    includedAiCredits: 1000,
    activeFlowsLimit: 50,
    userSeatsLimit: 5,
    projectsLimit: 10,
    mcpLimit: 5,

    tablesEnabled: true,
    todosEnabled: true,

    embeddingEnabled: false,
    globalConnectionsEnabled: false,
    customRolesEnabled: false,
    environmentsEnabled: false,
    analyticsEnabled: false,
    managePiecesEnabled: false,
    manageTemplatesEnabled: false,
    customAppearanceEnabled: false,
    manageProjectsEnabled: false,
    projectRolesEnabled: false,
    customDomainsEnabled: false,
    apiKeysEnabled: false,
    alertsEnabled: false,
    ssoEnabled: false,
    showPoweredBy: false,
    auditLogEnabled: false,

}

export const OPENSOURCE_PLAN: PlatformPlanLimits = {
    embeddingEnabled: false,
    tablesEnabled: true,
    todosEnabled: true,
    globalConnectionsEnabled: false,
    customRolesEnabled: false,
    includedTasks: 0,
    includedAiCredits: 0,
    environmentsEnabled: false,
    analyticsEnabled: false,
    showPoweredBy: false,
    auditLogEnabled: false,
    managePiecesEnabled: false,
    manageTemplatesEnabled: false,
    customAppearanceEnabled: false,
    tasksLimit: undefined,
    manageProjectsEnabled: false,
    projectRolesEnabled: false,
    customDomainsEnabled: false,
    apiKeysEnabled: false,
    alertsEnabled: false,
    ssoEnabled: false,
    stripeCustomerId: undefined,
    stripeSubscriptionId: undefined,
    stripeSubscriptionStatus: undefined,
}