export enum TriggerType {
	SCHEDULE = 'SCHEDULE',
	EVENT = 'EVENT',
	EMPTY = 'EMPTY',
	WEBHOOK = 'WEBHOOK',
	COLLECTION_ENABLED = 'COLLECTION_ENABLED',
	COLLECTION_DISABLED = 'COLLECTION_DISABLED',
	COMPONENT = 'COMPONENT_TRIGGER',
}
