type EmojiEntry = { char: string; keywords: string };

const EMOJIS: EmojiEntry[] = [
  { char: '😀', keywords: 'grin happy smile' },
  { char: '😃', keywords: 'happy smile joy' },
  { char: '😄', keywords: 'happy laugh smile' },
  { char: '😁', keywords: 'grin beam happy' },
  { char: '😆', keywords: 'laugh haha happy' },
  { char: '😅', keywords: 'sweat phew nervous laugh' },
  { char: '😂', keywords: 'laugh lol joy tears' },
  { char: '🤣', keywords: 'rofl lol laughing' },
  { char: '🙂', keywords: 'smile slight' },
  { char: '🙃', keywords: 'upside down silly' },
  { char: '😉', keywords: 'wink' },
  { char: '😊', keywords: 'blush smile happy' },
  { char: '😇', keywords: 'angel innocent halo' },
  { char: '🥰', keywords: 'love hearts adore' },
  { char: '😍', keywords: 'love heart eyes' },
  { char: '🤩', keywords: 'star struck wow amazing' },
  { char: '😘', keywords: 'kiss love' },
  { char: '😋', keywords: 'yum tasty tongue' },
  { char: '😜', keywords: 'wink tongue silly' },
  { char: '🤪', keywords: 'zany crazy silly' },
  { char: '🤗', keywords: 'hug thanks' },
  { char: '🤭', keywords: 'oops giggle' },
  { char: '🤔', keywords: 'think hmm' },
  { char: '🤨', keywords: 'skeptic raised eyebrow' },
  { char: '😐', keywords: 'neutral meh' },
  { char: '😶', keywords: 'speechless blank' },
  { char: '🙄', keywords: 'eyeroll whatever' },
  { char: '😏', keywords: 'smirk' },
  { char: '😴', keywords: 'sleep tired' },
  { char: '😪', keywords: 'sleepy tired' },
  { char: '😬', keywords: 'grimace awkward yikes' },
  { char: '🙁', keywords: 'sad frown' },
  { char: '😟', keywords: 'worried' },
  { char: '😢', keywords: 'cry sad tear' },
  { char: '😭', keywords: 'sob cry sad' },
  { char: '😤', keywords: 'huff frustrated' },
  { char: '😠', keywords: 'angry mad' },
  { char: '😡', keywords: 'rage angry mad' },
  { char: '🤯', keywords: 'mind blown wow' },
  { char: '😳', keywords: 'flushed shocked' },
  { char: '🥵', keywords: 'hot heat' },
  { char: '😱', keywords: 'scream shock fear' },
  { char: '😰', keywords: 'anxious sweat nervous' },
  { char: '🤒', keywords: 'sick fever' },
  { char: '🤢', keywords: 'sick nausea gross' },
  { char: '🥳', keywords: 'party celebrate hat' },
  { char: '🥺', keywords: 'pleading please cute' },
  { char: '😎', keywords: 'cool sunglasses' },
  { char: '🤓', keywords: 'nerd geek' },
  { char: '🧐', keywords: 'monocle inspect' },
  { char: '👍', keywords: 'thumbs up yes ok like' },
  { char: '👎', keywords: 'thumbs down no dislike' },
  { char: '👌', keywords: 'ok perfect' },
  { char: '✌️', keywords: 'peace victory' },
  { char: '🤞', keywords: 'fingers crossed luck hope' },
  { char: '🤟', keywords: 'love you rock' },
  { char: '🤙', keywords: 'call shaka' },
  { char: '👏', keywords: 'clap applause bravo' },
  { char: '🙌', keywords: 'raise hands praise yay' },
  { char: '🤝', keywords: 'handshake deal' },
  { char: '🙏', keywords: 'pray thanks please' },
  { char: '💪', keywords: 'muscle strong flex' },
  { char: '👋', keywords: 'wave hi bye hello' },
  { char: '🤘', keywords: 'rock horns' },
  { char: '❤️', keywords: 'love heart red' },
  { char: '🧡', keywords: 'orange heart' },
  { char: '💛', keywords: 'yellow heart' },
  { char: '💚', keywords: 'green heart' },
  { char: '💙', keywords: 'blue heart' },
  { char: '💜', keywords: 'purple heart' },
  { char: '🖤', keywords: 'black heart' },
  { char: '🤍', keywords: 'white heart' },
  { char: '💖', keywords: 'sparkle heart love' },
  { char: '💕', keywords: 'hearts love' },
  { char: '💔', keywords: 'broken heart sad' },
  { char: '💯', keywords: 'hundred perfect score' },
  { char: '🎉', keywords: 'party celebrate tada' },
  { char: '🎊', keywords: 'confetti celebrate party' },
  { char: '🔥', keywords: 'fire lit hot awesome' },
  { char: '✨', keywords: 'sparkles shine magic' },
  { char: '⭐', keywords: 'star' },
  { char: '🌟', keywords: 'star glowing shine' },
  { char: '⚡', keywords: 'lightning fast power' },
  { char: '🚀', keywords: 'rocket launch ship fast' },
  { char: '🏆', keywords: 'trophy win champion' },
  { char: '✅', keywords: 'check done yes complete' },
  { char: '❌', keywords: 'cross no wrong' },
  { char: '⚠️', keywords: 'warning caution' },
  { char: '❓', keywords: 'question' },
  { char: '❗', keywords: 'exclamation important' },
  { char: '💡', keywords: 'idea lightbulb' },
  { char: '👀', keywords: 'eyes look watch' },
  { char: '🎯', keywords: 'target goal bullseye' },
  { char: '📈', keywords: 'chart growth up' },
  { char: '💰', keywords: 'money bag cash' },
  { char: '🐶', keywords: 'dog puppy' },
  { char: '🐱', keywords: 'cat kitten' },
  { char: '🦊', keywords: 'fox' },
  { char: '🐻', keywords: 'bear' },
  { char: '🐼', keywords: 'panda' },
  { char: '🦄', keywords: 'unicorn magic' },
  { char: '🍕', keywords: 'pizza food' },
  { char: '🍔', keywords: 'burger food' },
  { char: '🍩', keywords: 'donut sweet' },
  { char: '☕', keywords: 'coffee tea' },
  { char: '🍺', keywords: 'beer drink cheers' },
  { char: '🍷', keywords: 'wine drink' },
  { char: '🎂', keywords: 'cake birthday' },
  { char: '🌈', keywords: 'rainbow' },
  { char: '☀️', keywords: 'sun sunny' },
  { char: '🌙', keywords: 'moon night' },
  { char: '🎁', keywords: 'gift present' },
  { char: '⏰', keywords: 'clock alarm time' },
  { char: '🔒', keywords: 'lock secure' },
  { char: '🔑', keywords: 'key access' },
];

const POPULAR_CHARS = [
  '👍',
  '❤️',
  '😂',
  '🎉',
  '🔥',
  '😊',
  '🙏',
  '✅',
  '👀',
  '🚀',
  '😅',
  '😍',
  '💯',
  '🙌',
  '😎',
  '🤔',
  '😢',
  '🥳',
  '👏',
  '💪',
  '😀',
  '😉',
  '🤝',
  '✨',
];

const POPULAR: EmojiEntry[] = POPULAR_CHARS.map((char) =>
  EMOJIS.find((e) => e.char === char),
).filter((e): e is EmojiEntry => Boolean(e));

function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) {
    return EMOJIS;
  }
  return EMOJIS.filter((e) => e.keywords.includes(q));
}

export const emojiData = {
  all: EMOJIS,
  popular: POPULAR,
  search: searchEmojis,
};
