export const githubNewMilestoneTrigger = {
  name: 'milestone',
  displayName: 'New Milestone',
  description: 'Fires when a new milestone is created in a repository.',
  sampleData: {
    action: 'created',
    milestone: {
      url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
      html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
      labels_url:
        'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
      id: 2002605,
      node_id: 'MDk6TWlsZXN0b25lMjAwMjYwNQ==',
      number: 1,
      state: 'open',
      title: 'v1.0',
      description: 'Tracking milestone for version 1.0 release',
      creator: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        type: 'User',
        site_admin: false,
      },
      open_issues: 4,
      closed_issues: 8,
      created_at: '2023-07-15T12:34:56Z',
      updated_at: '2023-07-20T08:45:23Z',
      closed_at: null,
      due_on: '2023-08-01T23:59:59Z',
    },
    repository: {
      id: 1296269,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
      name: 'Hello-World',
      full_name: 'octocat/Hello-World',
      private: false,
      owner: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/octocat/Hello-World',
      description: 'This your first repo!',
      fork: false,
      url: 'https://api.github.com/repos/octocat/Hello-World',
      created_at: '2011-01-26T19:01:12Z',
      updated_at: '2011-01-26T19:14:43Z',
      pushed_at: '2011-01-26T19:06:43Z',
    },
    sender: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      type: 'User',
      site_admin: false,
    },
  },
};
