export const githubNewCollaboratorTrigger = {
  name: 'member', // GitHub "member" event
  displayName: 'New Collaborator',
  description: 'Fires when a new collaborator is added to a repository.',
  sampleData: {
    action: 'added',
    member: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      type: 'User',
      site_admin: false,
    },
    repository: {
      id: 1296269,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
      name: 'Hello-World',
      full_name: 'octocat/Hello-World',
      private: false,
      owner: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/octocat/Hello-World',
      description: 'This your first repo!',
      fork: false,
      url: 'https://api.github.com/repos/octocat/Hello-World',
      created_at: '2011-01-26T19:01:12Z',
      updated_at: '2011-01-26T19:14:43Z',
      pushed_at: '2011-01-26T19:06:43Z',
    },
    sender: {
      login: 'repo-owner',
      id: 2,
      node_id: 'MDQ6VXNlcjI=',
      avatar_url: 'https://github.com/images/error/repo_owner.png',
      url: 'https://api.github.com/users/repo-owner',
      html_url: 'https://github.com/repo-owner',
      type: 'User',
      site_admin: false,
    },
  },
};
