export const githubNewReleaseTrigger = {
  name: 'release',
  displayName: 'New Release',
  description: 'Fires when a new release is published in a repository.',
  sampleData: {
    action: 'published',
    release: {
      url: 'https://api.github.com/repos/octocat/Hello-World/releases/1',
      html_url: 'https://github.com/octocat/Hello-World/releases/v1.0.0',
      assets_url:
        'https://api.github.com/repos/octocat/Hello-World/releases/1/assets',
      upload_url:
        'https://uploads.github.com/repos/octocat/Hello-World/releases/1/assets{?name,label}',
      tarball_url:
        'https://api.github.com/repos/octocat/Hello-World/tarball/v1.0.0',
      zipball_url:
        'https://api.github.com/repos/octocat/Hello-World/zipball/v1.0.0',
      id: 1,
      node_id: 'MDc6UmVsZWFzZTE=',
      tag_name: 'v1.0.0',
      target_commitish: 'main',
      name: 'v1.0.0 Stable Release',
      draft: false,
      author: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        type: 'User',
        site_admin: false,
      },
      prerelease: false,
      created_at: '2023-07-15T12:00:00Z',
      published_at: '2023-07-15T12:30:00Z',
      body: '🎉 First stable release of the project.\n\nIncludes bug fixes, new features, and improvements.',
      assets: [
        {
          url: 'https://api.github.com/repos/octocat/Hello-World/releases/assets/1',
          browser_download_url:
            'https://github.com/octocat/Hello-World/releases/download/v1.0.0/app.zip',
          id: 123456,
          node_id: 'MDEyOlJlbGVhc2VBc3NldDEyMzQ1Ng==',
          name: 'app.zip',
          label: 'Build for Windows',
          state: 'uploaded',
          content_type: 'application/zip',
          size: 102400,
          download_count: 42,
          created_at: '2023-07-15T12:10:00Z',
          updated_at: '2023-07-15T12:20:00Z',
          uploader: {
            login: 'octocat',
            id: 1,
            node_id: 'MDQ6VXNlcjE=',
            avatar_url: 'https://github.com/images/error/octocat_happy.gif',
            url: 'https://api.github.com/users/octocat',
            html_url: 'https://github.com/octocat',
            type: 'User',
            site_admin: false,
          },
        },
      ],
    },
    repository: {
      id: 1296269,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
      name: 'Hello-World',
      full_name: 'octocat/Hello-World',
      private: false,
      owner: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/octocat/Hello-World',
      description: 'This your first repo!',
      fork: false,
      url: 'https://api.github.com/repos/octocat/Hello-World',
      created_at: '2011-01-26T19:01:12Z',
      updated_at: '2011-01-26T19:14:43Z',
      pushed_at: '2011-01-26T19:06:43Z',
    },
    sender: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      type: 'User',
      site_admin: false,
    },
  },
};
