export const githubNewBranchTrigger = {
  name: 'create', // GitHub "create" event (branch or tag)
  displayName: 'New Branch',
  description: 'Fires when a new branch is created.',
  sampleData: {
    ref: 'feature/new-ui',
    ref_type: 'branch',
    master_branch: 'main',
    description: null,
    pusher_type: 'user',
    repository: {
      id: 123456789,
      node_id: 'MDEwOlJlcG9zaXRvcnkxMjM0NTY3ODk=',
      name: 'example-repo',
      full_name: 'octocat/example-repo',
      private: false,
      owner: {
        login: 'octocat',
        id: 1,
        node_id: 'MDQ6VXNlcjE=',
        avatar_url: 'https://github.com/images/error/octocat_happy.gif',
        gravatar_id: '',
        url: 'https://api.github.com/users/octocat',
        html_url: 'https://github.com/octocat',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/octocat/example-repo',
      description: 'This is an example repo',
      fork: false,
      url: 'https://api.github.com/repos/octocat/example-repo',
      forks_count: 9,
      stargazers_count: 80,
      watchers_count: 80,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks: 9,
      open_issues: 0,
      watchers: 80,
      default_branch: 'main',
    },
    sender: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      type: 'User',
      site_admin: false,
    },
    organization: {
      login: 'octo-org',
      id: 1234567,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjEyMzQ1Njc=',
      url: 'https://api.github.com/orgs/octo-org',
      repos_url: 'https://api.github.com/orgs/octo-org/repos',
      events_url: 'https://api.github.com/orgs/octo-org/events',
      hooks_url: 'https://api.github.com/orgs/octo-org/hooks',
      issues_url: 'https://api.github.com/orgs/octo-org/issues',
      members_url: 'https://api.github.com/orgs/octo-org/members{/member}',
      public_members_url:
        'https://api.github.com/orgs/octo-org/public_members{/member}',
      avatar_url: 'https://avatars.githubusercontent.com/u/1234567?v=4',
      description: 'Octo Organization for demo',
    },
    installation: {
      id: 987654321,
      node_id: 'MDExOkluc3RhbGxhdGlvbjk4NzY1NDMyMQ==',
    },
  },
};
