export enum BikaFieldType {
  SINGLE_TEXT = 'SINGLE_TEXT',
  LONG_TEXT = 'LONG_TEXT',
  URL = 'URL',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  NUMBER = 'NUMBER',
  CURRENCY = 'CURRENCY',
  PERCENT = 'PERCENT',
  RATING = 'RATING',
  CHECKBOX = 'CHECKBOX',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  MEMBER = 'MEMBER',
  DATETIME = 'DATETIME',
  DATERANGE = 'DATERANGE',
  ATTACHMENT = 'ATTACHMENT',
  LINK = 'LINK',
  ONE_WAY_LINK = 'ONE_WAY_LINK',
  LOOKUP = 'LOOKUP',
  FORMULA = 'FORMULA',
  AUTO_NUMBER = 'AUTO_NUMBER',
  CREATED_TIME = 'CREATED_TIME',
  MODIFIED_TIME = 'MODIFIED_TIME',
  CREATED_BY = 'CREATED_BY',
  MODIFIED_BY = 'MODIFIED_BY',
  CASCADER = 'CASCADER',
  JSON = 'JSON',
  AI_TEXT = 'AI_TEXT',
  WORK_DOC = 'WORK_DOC',
  BUTTON = 'BUTTON',
}

export const BIKA_WRITE_FORMATS: Record<string, string> = {
  [BikaFieldType.SINGLE_TEXT]: 'string',
  [BikaFieldType.LONG_TEXT]: 'string',
  [BikaFieldType.URL]: 'string (URL)',
  [BikaFieldType.EMAIL]: 'string (email address)',
  [BikaFieldType.PHONE]: 'string (phone number)',
  [BikaFieldType.NUMBER]: 'number',
  [BikaFieldType.CURRENCY]: 'number',
  [BikaFieldType.PERCENT]: 'number',
  [BikaFieldType.RATING]: 'number',
  [BikaFieldType.CHECKBOX]: 'boolean',
  [BikaFieldType.SINGLE_SELECT]: 'string: one option name',
  [BikaFieldType.MULTI_SELECT]: 'array of option names',
  [BikaFieldType.MEMBER]: 'array of member, team or role IDs',
  [BikaFieldType.DATETIME]: 'ISO 8601 date-time string',
  [BikaFieldType.DATERANGE]: 'string "start/end" with two ISO 8601 date-times',
  [BikaFieldType.ATTACHMENT]: 'array of {"id": "<attachment ID>"} objects from an earlier upload',
  [BikaFieldType.LINK]: 'array of record IDs from the linked database',
  [BikaFieldType.ONE_WAY_LINK]: 'array of record IDs from the linked database',
};

export const BIKA_READ_ONLY_FIELD_TYPES: string[] = [
  BikaFieldType.LOOKUP,
  BikaFieldType.FORMULA,
  BikaFieldType.AUTO_NUMBER,
  BikaFieldType.CREATED_TIME,
  BikaFieldType.MODIFIED_TIME,
  BikaFieldType.CREATED_BY,
  BikaFieldType.MODIFIED_BY,
  BikaFieldType.BUTTON,
];
