export const enum OBJECT_TYPE {
  CONTACT = 'contact',
  COMPANY = 'company',
  DEAL = 'deal',
  TICKET = 'ticket',
}

export const DEFAULT_CONTACT_PROPERTIES = [
  'firstname',
  'lastname',
  'email',
  'company',
  'website',
  'mobilephone',
  'phone',
  'fax',
  'address',
  'city',
  'state',
  'zip',
  'salutation',
  'country',
  'jobtitle',
  'hs_createdate',
  'hs_email_domain',
  'hs_object_id',
  'lastmodifieddate',
  'hs_persona',
  'hs_language',
  'lifecyclestage',
  'createdate',
  'numemployees',
  'annualrevenue',
  'industry',
];

export const DEFAULT_DEAL_PROPERTIES = [
  'dealtype',
  'dealname',
  'amount',
  'description',
  'closedate',
  'createdate',
  'num_associated_contacts',
  'hs_forecast_amount',
  'hs_forecast_probability',
  'hs_manual_forecast_category',
  'hs_next_step',
  'hs_object_id',
  'hs_lastmodifieddate',
  'hubspot_owner_id',
  'hubspot_team_id',
];

export const DEFAULT_TICKET_PROPERTIES = [
  'subject',
  'content',
  'source_type',
  'createdate',
  'hs_pipeline',
  'hs_pipeline_stage',
  'hs_resolution',
  'hs_ticket_category',
  'hs_ticket_id',
  'hs_ticket_priority',
  'hs_lastmodifieddate',
  'hubspot_owner_id',
  'hubspot_team_id',
];
