export enum AiStepAction {
    ASK_AI = 'ASK_AI',
    SUMMARIZE_TEXT = 'SUMMARIZE_TEXT',
    CLASSIFY_TEXT = 'CLASSIFY_TEXT',
    EXTRACT_STRUCTURED_DATA = 'EXTRACT_STRUCTURED_DATA',
    GENERATE_IMAGE = 'GENERATE_IMAGE',
}
