// docs: https://learn.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/mt608066(v=crm.8)

export const EntityDetails: {
  [key: string]: {
    displayName: string;
    value: string;
    urlPath: string;
    primaryKey: string;
    primaryNameAttribute: string;
  };
} = {
  account: {
    displayName: 'Account',
    value: 'account',
    urlPath: 'accounts',
    primaryKey: 'accountid',
    primaryNameAttribute: 'name',
  },
  actioncard: {
    displayName: 'Action Card',
    value: 'actioncard',
    urlPath: 'actioncards',
    primaryKey: 'actioncardid',
    primaryNameAttribute: 'title',
  },
  actioncarduserstate: {
    displayName: 'ActionCardUserState',
    value: 'actioncarduserstate',
    urlPath: 'actioncarduserstates',
    primaryKey: 'actioncarduserstateid',
    primaryNameAttribute: 'actioncarduserstateid',
  },
  calendar: {
    displayName: 'Calendar',
    value: 'calendar',
    urlPath: 'calendars',
    primaryKey: 'calendarid',
    primaryNameAttribute: 'name',
  },
  contact: {
    displayName: 'Contact',
    value: 'contact',
    urlPath: 'contacts',
    primaryKey: 'contractid',
    primaryNameAttribute: 'fullname',
  },
  campaign: {
    displayName: 'Campaingn',
    value: 'campaign',
    urlPath: 'campaigns',
    primaryKey: 'campaignid',
    primaryNameAttribute: 'name',
  },
  campaignactivity: {
    displayName: 'Campaign Activity',
    value: 'campaignactivity',
    urlPath: 'campaignactivities',
    primaryKey: 'activityid',
    primaryNameAttribute: 'subject',
  },
  campaignactivityitem: {
    displayName: 'Campaign Activity Item',
    value: 'campaignactivityitem',
    urlPath: 'campaignactivityitems',
    primaryKey: 'campaignactivityitemid',
    primaryNameAttribute: 'campaignactivityitemid ',
  },
  campaignitem: {
    displayName: 'Campaign Item',
    value: 'campaignitem',
    urlPath: 'campaignitems',
    primaryKey: 'campaignitemid',
    primaryNameAttribute: 'campaignitemid',
  },
  campaignresponse: {
    displayName: 'Campaign Response',
    value: 'campaignresponse',
    urlPath: 'campaignresponses',
    primaryKey: 'activityid',
    primaryNameAttribute: 'subject',
  },
  category: {
    displayName: 'Category',
    value: 'category',
    urlPath: 'categories',
    primaryKey: 'categoryid',
    primaryNameAttribute: 'title',
  },
  characteristic: {
    displayName: 'Characteristic',
    value: 'characteristic',
    urlPath: 'characteristics',
    primaryKey: 'characteristicid',
    primaryNameAttribute: 'name',
  },
  goal: {
    displayName: 'Goal',
    value: 'goal',
    urlPath: 'goals',
    primaryKey: 'goalid',
    primaryNameAttribute: 'title',
  },
  lead: {
    displayName: 'Lead',
    value: 'lead',
    urlPath: 'leads',
    primaryKey: 'leadid',
    primaryNameAttribute: 'fullname',
  },
  incident: {
    displayName: 'Case / Incident',
    value: 'incident',
    urlPath: 'incidents',
    primaryKey: 'incidentid',
    primaryNameAttribute: 'title',
  },
  invoice: {
    displayName: 'Invoice',
    value: 'invoice',
    urlPath: 'invoices',
    primaryKey: 'invoiceid',
    primaryNameAttribute: 'name',
  },
  invoicedetail: {
    displayName: 'Invoice Product',
    value: 'invoicedetail',
    urlPath: 'invoicedetails',
    primaryKey: 'invoicedetailid',
    primaryNameAttribute: 'productidname',
  },
  kbarticle: {
    displayName: 'Article',
    value: 'kbarticle',
    urlPath: 'kbarticles',
    primaryKey: 'kbarticleid',
    primaryNameAttribute: 'title',
  },
  kbarticlecomment: {
    displayName: 'Article Comment',
    value: 'kbarticlecomment',
    urlPath: 'kbarticlecomments',
    primaryKey: 'kbarticlecommentid',
    primaryNameAttribute: 'title',
  },
  list: {
    displayName: 'Marketing List',
    value: 'list',
    urlPath: 'lists',
    primaryKey: 'listid',
    primaryNameAttribute: 'listname',
  },
  listmember: {
    displayName: 'Marketing List Member',
    value: 'listmember',
    urlPath: 'listmembers',
    primaryKey: 'listmemberid',
    primaryNameAttribute: 'listmemberid',
  },
  feedback: {
    displayName: 'Feedback',
    value: 'feedback',
    urlPath: 'feedback',
    primaryKey: 'feedbackid',
    primaryNameAttribute: 'title',
  },
  opportunity: {
    displayName: 'Opportunity',
    value: 'opportunity',
    urlPath: 'opportunities',
    primaryKey: 'opportunityid',
    primaryNameAttribute: 'name',
  },
  organization: {
    displayName: 'Organization',
    value: 'organization',
    urlPath: 'organizations',
    primaryKey: 'organizationid',
    primaryNameAttribute: 'name',
  },
  post: {
    displayName: 'Post',
    value: 'post',
    urlPath: 'posts',
    primaryKey: 'postid',
    primaryNameAttribute: 'text',
  },
  postcomment: {
    displayName: 'Post Comment',
    value: 'postcomment',
    urlPath: 'postcomments',
    primaryKey: 'postcommentid',
    primaryNameAttribute: 'text',
  },
  product: {
    displayName: 'Product',
    value: 'product',
    urlPath: 'products',
    primaryKey: 'productid',
    primaryNameAttribute: 'name',
  },
  publisher: {
    displayName: 'Publisher',
    value: 'publisher',
    urlPath: 'publishers',
    primaryKey: 'publisherid',
    primaryNameAttribute: 'friendlyname',
  },
  quote: {
    displayName: 'Quote',
    value: 'quote',
    urlPath: 'quotes',
    primaryKey: 'quoteid',
    primaryNameAttribute: 'name',
  },
  quotedetail: {
    displayName: 'Quote Product',
    value: 'quotedetail',
    urlPath: 'quotedetails',
    primaryKey: 'quotedetailid',
    primaryNameAttribute: 'productidname',
  },
  salesorder: {
    displayName: 'Order',
    value: 'salesorder',
    urlPath: 'salesorders',
    primaryKey: 'salesorderid',
    primaryNameAttribute: 'name',
  },
  salesorderdetail: {
    displayName: 'Order Product',
    value: 'salesorderdetail',
    urlPath: 'salesorderdetails',
    primaryKey: 'salesorderdetailid',
    primaryNameAttribute: 'productidname',
  },
  task: {
    displayName: 'Task',
    value: 'task',
    urlPath: 'tasks',
    primaryKey: 'activityid',
    primaryNameAttribute: 'subject',
  },
};

export enum EntityAttributeType {
  PICKLIST = 'Picklist',
  VIRTUAL = 'Virtual',
  UNIQUE_IDENTIFIER = 'Uniqueidentifier',
  STRING = 'String',
  MEMO = 'Memo',
  MONEY = 'Money',
  DOUBLE = 'Double',
  INTEGER = 'Integer',
  LOOKUP = 'Lookup',
  DATETIME = 'DateTime',
  BOOLEAN = 'Boolean',
  BIGINT = 'BigInt',
  DECIMAL = 'Decimal',
  OWNER = 'Owner',
  ENTITY_NAME = 'EntityName',
  STATE = 'State',
  STATUS = 'Status',
}
