"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.piecePropertiesUtils = exports.InputPropertyMap = exports.PiecePropertyMap = exports.CustomProperty = exports.PieceProperty = exports.JsonProperty = exports.CustomAuthProperty = exports.SecretTextProperty = exports.BasicAuthProperty = exports.FileProperty = exports.OAuth2Property = exports.StaticDropdownProperty = exports.StaticMultiSelectDropdownProperty = exports.BasicAuthPropertyValue = exports.OAuth2AuthorizationMethod = exports.OAuth2Props = exports.ObjectProperty = exports.NumberProperty = exports.LongTextProperty = exports.DateTimeProperty = exports.CheckboxProperty = exports.BasePropertySchema = exports.ArraySubProps = exports.ArrayProperty = exports.ShortTextProperty = exports.DEFAULT_CONNECTION_DISPLAY_NAME = exports.PieceAuthProperty = exports.OAuth2PropertyValue = exports.DropdownState = exports.DropdownOption = exports.DynamicPropsValue = exports.getAuthPropertyForValue = exports.PieceAuth = exports.Property = exports.PropertyType = exports.DynamicProp = exports.DynamicProperties = exports.MultiSelectDropdownProperty = exports.DropdownProperty = exports.ApFile = void 0;
const tslib_1 = require("tslib");
const input_1 = require("./input");
const authentication_1 = require("./authentication");
const typebox_1 = require("@sinclair/typebox");
// EXPORTED
var file_property_1 = require("./input/file-property");
Object.defineProperty(exports, "ApFile", { enumerable: true, get: function () { return file_property_1.ApFile; } });
var dropdown_prop_1 = require("./input/dropdown/dropdown-prop");
Object.defineProperty(exports, "DropdownProperty", { enumerable: true, get: function () { return dropdown_prop_1.DropdownProperty; } });
Object.defineProperty(exports, "MultiSelectDropdownProperty", { enumerable: true, get: function () { return dropdown_prop_1.MultiSelectDropdownProperty; } });
var dynamic_prop_1 = require("./input/dynamic-prop");
Object.defineProperty(exports, "DynamicProperties", { enumerable: true, get: function () { return dynamic_prop_1.DynamicProperties; } });
Object.defineProperty(exports, "DynamicProp", { enumerable: true, get: function () { return dynamic_prop_1.DynamicProp; } });
var property_type_1 = require("./input/property-type");
Object.defineProperty(exports, "PropertyType", { enumerable: true, get: function () { return property_type_1.PropertyType; } });
var input_2 = require("./input");
Object.defineProperty(exports, "Property", { enumerable: true, get: function () { return input_2.Property; } });
var authentication_2 = require("./authentication");
Object.defineProperty(exports, "PieceAuth", { enumerable: true, get: function () { return authentication_2.PieceAuth; } });
Object.defineProperty(exports, "getAuthPropertyForValue", { enumerable: true, get: function () { return authentication_2.getAuthPropertyForValue; } });
var dynamic_prop_2 = require("./input/dynamic-prop");
Object.defineProperty(exports, "DynamicPropsValue", { enumerable: true, get: function () { return dynamic_prop_2.DynamicPropsValue; } });
var common_1 = require("./input/dropdown/common");
Object.defineProperty(exports, "DropdownOption", { enumerable: true, get: function () { return common_1.DropdownOption; } });
Object.defineProperty(exports, "DropdownState", { enumerable: true, get: function () { return common_1.DropdownState; } });
var oauth2_prop_1 = require("./authentication/oauth2-prop");
Object.defineProperty(exports, "OAuth2PropertyValue", { enumerable: true, get: function () { return oauth2_prop_1.OAuth2PropertyValue; } });
var authentication_3 = require("./authentication");
Object.defineProperty(exports, "PieceAuthProperty", { enumerable: true, get: function () { return authentication_3.PieceAuthProperty; } });
Object.defineProperty(exports, "DEFAULT_CONNECTION_DISPLAY_NAME", { enumerable: true, get: function () { return authentication_3.DEFAULT_CONNECTION_DISPLAY_NAME; } });
var text_property_1 = require("./input/text-property");
Object.defineProperty(exports, "ShortTextProperty", { enumerable: true, get: function () { return text_property_1.ShortTextProperty; } });
var array_property_1 = require("./input/array-property");
Object.defineProperty(exports, "ArrayProperty", { enumerable: true, get: function () { return array_property_1.ArrayProperty; } });
Object.defineProperty(exports, "ArraySubProps", { enumerable: true, get: function () { return array_property_1.ArraySubProps; } });
var common_2 = require("./input/common");
Object.defineProperty(exports, "BasePropertySchema", { enumerable: true, get: function () { return common_2.BasePropertySchema; } });
var checkbox_property_1 = require("./input/checkbox-property");
Object.defineProperty(exports, "CheckboxProperty", { enumerable: true, get: function () { return checkbox_property_1.CheckboxProperty; } });
var date_time_property_1 = require("./input/date-time-property");
Object.defineProperty(exports, "DateTimeProperty", { enumerable: true, get: function () { return date_time_property_1.DateTimeProperty; } });
var text_property_2 = require("./input/text-property");
Object.defineProperty(exports, "LongTextProperty", { enumerable: true, get: function () { return text_property_2.LongTextProperty; } });
var number_property_1 = require("./input/number-property");
Object.defineProperty(exports, "NumberProperty", { enumerable: true, get: function () { return number_property_1.NumberProperty; } });
var object_property_1 = require("./input/object-property");
Object.defineProperty(exports, "ObjectProperty", { enumerable: true, get: function () { return object_property_1.ObjectProperty; } });
var oauth2_prop_2 = require("./authentication/oauth2-prop");
Object.defineProperty(exports, "OAuth2Props", { enumerable: true, get: function () { return oauth2_prop_2.OAuth2Props; } });
var oauth2_prop_3 = require("./authentication/oauth2-prop");
Object.defineProperty(exports, "OAuth2AuthorizationMethod", { enumerable: true, get: function () { return oauth2_prop_3.OAuth2AuthorizationMethod; } });
var basic_auth_prop_1 = require("./authentication/basic-auth-prop");
Object.defineProperty(exports, "BasicAuthPropertyValue", { enumerable: true, get: function () { return basic_auth_prop_1.BasicAuthPropertyValue; } });
var static_dropdown_1 = require("./input/dropdown/static-dropdown");
Object.defineProperty(exports, "StaticMultiSelectDropdownProperty", { enumerable: true, get: function () { return static_dropdown_1.StaticMultiSelectDropdownProperty; } });
var static_dropdown_2 = require("./input/dropdown/static-dropdown");
Object.defineProperty(exports, "StaticDropdownProperty", { enumerable: true, get: function () { return static_dropdown_2.StaticDropdownProperty; } });
tslib_1.__exportStar(require("./authentication/custom-auth-prop"), exports);
var oauth2_prop_4 = require("./authentication/oauth2-prop");
Object.defineProperty(exports, "OAuth2Property", { enumerable: true, get: function () { return oauth2_prop_4.OAuth2Property; } });
var file_property_2 = require("./input/file-property");
Object.defineProperty(exports, "FileProperty", { enumerable: true, get: function () { return file_property_2.FileProperty; } });
var basic_auth_prop_2 = require("./authentication/basic-auth-prop");
Object.defineProperty(exports, "BasicAuthProperty", { enumerable: true, get: function () { return basic_auth_prop_2.BasicAuthProperty; } });
var secret_text_property_1 = require("./authentication/secret-text-property");
Object.defineProperty(exports, "SecretTextProperty", { enumerable: true, get: function () { return secret_text_property_1.SecretTextProperty; } });
var custom_auth_prop_1 = require("./authentication/custom-auth-prop");
Object.defineProperty(exports, "CustomAuthProperty", { enumerable: true, get: function () { return custom_auth_prop_1.CustomAuthProperty; } });
var json_property_1 = require("./input/json-property");
Object.defineProperty(exports, "JsonProperty", { enumerable: true, get: function () { return json_property_1.JsonProperty; } });
exports.PieceProperty = typebox_1.Type.Union([input_1.InputProperty, authentication_1.PieceAuthProperty]);
var custom_property_1 = require("./input/custom-property");
Object.defineProperty(exports, "CustomProperty", { enumerable: true, get: function () { return custom_property_1.CustomProperty; } });
exports.PiecePropertyMap = typebox_1.Type.Record(typebox_1.Type.String(), exports.PieceProperty);
exports.InputPropertyMap = typebox_1.Type.Record(typebox_1.Type.String(), input_1.InputProperty);
var util_1 = require("./util");
Object.defineProperty(exports, "piecePropertiesUtils", { enumerable: true, get: function () { return util_1.piecePropertiesUtils; } });
//# sourceMappingURL=index.js.map