// core
export * from './lib/core/common'
export * from './lib/core/common/activepieces-error'
export * from './lib/core/common/telemetry'
export * from './lib/core/common/seek-page'
export * from './lib/core/common/id-generator'
export * from './lib/core/common/base-model'
export * from './lib/core/authentication/dto/authentication-response'
export * from './lib/core/authentication/dto/sign-up-request'
export * from './lib/core/authentication/dto/sign-in-request'
export * from './lib/core/authentication/model/principal-type'
export * from './lib/core/authentication/model/principal'
export * from './lib/core/authentication/user-identity'
export * from './lib/core/user'
export * from './lib/core/federated-authn'
export * from './lib/core/file'
export * from './lib/core/flag'
export * from './lib/core/property/markdown'
export * from './lib/core/store-entry/dto/store-entry-request'
export * from './lib/core/store-entry/store-entry'
export * from './lib/core/tag'
export * from './lib/core/license-keys'
export * from './lib/core/support-url'
export * from './lib/core/feedback-url'
export * from './lib/core/health'

// management
export * from './lib/management/platform'
export * from './lib/management/project'
export * from './lib/management/project-role/project-role'
export * from './lib/management/project-role/project-role.request'
export * from './lib/management/invitations'
export * from './lib/management/analytics'
export * from './lib/management/ai-providers'
export * from './lib/management/template'

// automation
export * from './lib/automation/flows/actions/action'
export * from './lib/automation/flows/operations'
export * from './lib/automation/flows/operations/paste-operations'
export * from './lib/automation/flows/triggers/trigger'
export * from './lib/automation/flows/triggers/trigger-events/trigger-events-dto'
export * from './lib/automation/flows/triggers/trigger-events/trigger-event'
export * from './lib/automation/flows/triggers/trigger-run'
export * from './lib/automation/flows/flow-version'
export * from './lib/automation/flows/flow'
export * from './lib/automation/flows/dto/count-flows-request'
export * from './lib/automation/flows/dto/create-flow-request'
export * from './lib/automation/flows/dto/list-flows-request'
export * from './lib/automation/flows/dto/flow-mcp.requests'
export * from './lib/automation/flows/sample-data'
export * from './lib/automation/flows/folders/folder'
export * from './lib/automation/flows/folders/folder-requests'
export * from './lib/automation/flows/util/flow-structure-util'
export * from './lib/automation/flows/util/flow-piece-util'
export * from './lib/automation/flows'
export * from './lib/automation/flow-run/dto/list-flow-runs-request'
export * from './lib/automation/flow-run/execution/execution-journal'
export * from './lib/automation/flow-run/execution/execution-output'
export * from './lib/automation/flow-run/execution/step-output'
export * from './lib/automation/flow-run/execution/flow-execution'
export * from './lib/automation/flow-run/flow-run'
export * from './lib/automation/flow-run/test-flow-run-request'
export * from './lib/automation/flow-run/log-serializer'
export * from './lib/automation/app-connection/app-connection'
export * from './lib/automation/app-connection/dto/read-app-connection-request'
export * from './lib/automation/app-connection/dto/upsert-app-connection-request'
export * from './lib/automation/engine'
export * from './lib/automation/pieces'
export * from './lib/automation/webhook'
export * from './lib/automation/trigger'
export * from './lib/automation/workers/job-data'
export * from './lib/automation/workers/queue-metrics'
export * from './lib/automation/workers'
export * from './lib/automation/forms'
export * from './lib/automation/mcp'
export * from './lib/automation/agents'
export * from './lib/automation/tables'
export * from './lib/automation/project-release/project-release'
export * from './lib/automation/project-release/project-release.request'
export * from './lib/automation/project-release/project-state'
export * from './lib/automation/websocket'

// ee
export * from './lib/ee/billing'
export * from './lib/ee/audit-events'
export * from './lib/ee/git-repo'
export * from './lib/ee/api-key'
export * from './lib/ee/custom-domains'
export * from './lib/ee/project-members/project-member-request'
export * from './lib/ee/project-members/project-member'
export * from './lib/ee/product-embed/app-credentials/index'
export * from './lib/ee/product-embed/connection-keys/index'
export * from './lib/ee/signing-key'
export * from './lib/ee/managed-authn'
export * from './lib/ee/oauth-apps'
export * from './lib/ee/otp'
export * from './lib/ee/authn'
export * from './lib/ee/alerts'
export * from './lib/ee/event-destinations'
export * from './lib/ee/secret-managers'
export * from './lib/management/project/project-requests'

// Sets TypeSystemPolicy for TypeBox
// Look at https://github.com/sinclairzx81/typebox/issues/350
import { TypeSystemPolicy } from '@sinclair/typebox/system'
TypeSystemPolicy.ExactOptionalPropertyTypes = false
