import { Static } from '@sinclair/typebox';
export declare const VerifyLicenseKeyRequestBody: import("@sinclair/typebox").TObject<{
    licenseKey: import("@sinclair/typebox").TString;
    platformId: import("@sinclair/typebox").TString;
}>;
export type VerifyLicenseKeyRequestBody = Static<typeof VerifyLicenseKeyRequestBody>;
export declare const LicenseKeyEntity: import("@sinclair/typebox").TObject<{
    id: import("@sinclair/typebox").TString;
    email: import("@sinclair/typebox").TString;
    expiresAt: import("@sinclair/typebox").TString;
    activatedAt: import("@sinclair/typebox").TString;
    createdAt: import("@sinclair/typebox").TString;
    key: import("@sinclair/typebox").TString;
    ssoEnabled: import("@sinclair/typebox").TBoolean;
    environmentsEnabled: import("@sinclair/typebox").TBoolean;
    showPoweredBy: import("@sinclair/typebox").TBoolean;
    embeddingEnabled: import("@sinclair/typebox").TBoolean;
    auditLogEnabled: import("@sinclair/typebox").TBoolean;
    customAppearanceEnabled: import("@sinclair/typebox").TBoolean;
    manageProjectsEnabled: import("@sinclair/typebox").TBoolean;
    managePiecesEnabled: import("@sinclair/typebox").TBoolean;
    manageTemplatesEnabled: import("@sinclair/typebox").TBoolean;
    apiKeysEnabled: import("@sinclair/typebox").TBoolean;
    customDomainsEnabled: import("@sinclair/typebox").TBoolean;
    projectRolesEnabled: import("@sinclair/typebox").TBoolean;
    analyticsEnabled: import("@sinclair/typebox").TBoolean;
    globalConnectionsEnabled: import("@sinclair/typebox").TBoolean;
    customRolesEnabled: import("@sinclair/typebox").TBoolean;
    agentsEnabled: import("@sinclair/typebox").TBoolean;
    tablesEnabled: import("@sinclair/typebox").TBoolean;
    todosEnabled: import("@sinclair/typebox").TBoolean;
    mcpsEnabled: import("@sinclair/typebox").TBoolean;
}>;
export declare const CreateTrialLicenseKeyRequestBody: import("@sinclair/typebox").TObject<{
    email: import("@sinclair/typebox").TString;
    companyName: import("@sinclair/typebox").TString;
    goal: import("@sinclair/typebox").TString;
    keyType: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TString>;
    environmentsEnabled: import("@sinclair/typebox").TBoolean;
    analyticsEnabled: import("@sinclair/typebox").TBoolean;
    showPoweredBy: import("@sinclair/typebox").TBoolean;
    agentsEnabled: import("@sinclair/typebox").TBoolean;
    mcpsEnabled: import("@sinclair/typebox").TBoolean;
    tablesEnabled: import("@sinclair/typebox").TBoolean;
    todosEnabled: import("@sinclair/typebox").TBoolean;
    auditLogEnabled: import("@sinclair/typebox").TBoolean;
    embeddingEnabled: import("@sinclair/typebox").TBoolean;
    managePiecesEnabled: import("@sinclair/typebox").TBoolean;
    manageTemplatesEnabled: import("@sinclair/typebox").TBoolean;
    customAppearanceEnabled: import("@sinclair/typebox").TBoolean;
    projectRolesEnabled: import("@sinclair/typebox").TBoolean;
    customDomainsEnabled: import("@sinclair/typebox").TBoolean;
    globalConnectionsEnabled: import("@sinclair/typebox").TBoolean;
    customRolesEnabled: import("@sinclair/typebox").TBoolean;
    apiKeysEnabled: import("@sinclair/typebox").TBoolean;
    ssoEnabled: import("@sinclair/typebox").TBoolean;
    manageProjectsEnabled: import("@sinclair/typebox").TBoolean;
}>;
export type CreateTrialLicenseKeyRequestBody = Static<typeof CreateTrialLicenseKeyRequestBody>;
export type LicenseKeyEntity = Static<typeof LicenseKeyEntity>;
