export const API_URL = 'http://127.0.0.1:3000/'
export const BASE_CODE_DIRECTORY = process.env.AP_BASE_CODE_DIRECTORY ?? './codes'
export const INPUT_FILE = './input.json'
export const OUTPUT_FILE = './output.json'
export const PIECE_SOURCES = process.env.AP_PIECES_SOURCE ?? 'dev'
