import { PieceAuth, createPiece } from '@activepieces/pieces-framework'
import {
  checkRedirect,
  getAddressBlocksValidated,
  getAddressByHash,
  getAddressCoinBalanceHistory,
  getAddressCoinBalanceHistoryByDay,
  getAddressCounters,
  getAddressLogs,
  getAddressTokenBalances,
  getAddressTokenTransfers,
  getAddressTokens,
  getAddressTransactions,
  getAddressWithdrawals,
  getAddresses,
  getBlockByHash,
  getBlockTransactions,
  getBlockWithdrawals,
  getBlocks,
  getMainPageBlocks,
  getMainPageTransactions,
  getTokenByAddress,
  getTokenCounters,
  getTokenHolders,
  getTokenInstances,
  getTokenTransfers,
  getTokens,
  getTransactionByHash,
  getTransactionInternalTransactions,
  getTransactionLogs,
  getTransactionRawTrace,
  getTransactionStateChanges,
  getTransactionSummary,
  getTransactionTokenTransfers,
  getTransactions,
  search,
} from './lib/actions'

export const blockscout = createPiece({
  displayName: 'Blockscout',
  description: 'Blockscout is a tool for inspecting and analyzing EVM chains.',
  auth: PieceAuth.None(),
  logoUrl: 'https://cdn.activepieces.com/pieces/blockscout.png',
  authors: ['reemayoush'],
  actions: [
    search,
    checkRedirect,
    getBlocks,
    getMainPageBlocks,
    getBlockByHash,
    getBlockTransactions,
    getBlockWithdrawals,
    getTransactions,
    getMainPageTransactions,
    getTransactionByHash,
    getTransactionTokenTransfers,
    getTransactionInternalTransactions,
    getTransactionLogs,
    getTransactionRawTrace,
    getTransactionStateChanges,
    getTransactionSummary,
    getAddresses,
    getAddressByHash,
    getAddressCounters,
    getAddressTransactions,
    getAddressTokenTransfers,
    getAddressLogs,
    getAddressBlocksValidated,
    getAddressTokenBalances,
    getAddressTokens,
    getAddressWithdrawals,
    getAddressCoinBalanceHistory,
    getAddressCoinBalanceHistoryByDay,
    getTokens,
    getTokenByAddress,
    getTokenTransfers,
    getTokenHolders,
    getTokenCounters,
    getTokenInstances,
  ],
  triggers: [],
})
