import { Property } from '@activepieces/pieces-framework';

export const countryDropdown = Property.StaticDropdown({
    displayName: 'Country',
    description: 'Country to use for the search',
    required: false,
    options: {
        options: [
            { label: 'us (United States)', value: 'us' },
            { label: 'af (Afghanistan)', value: 'af' },
            { label: 'al (Albania)', value: 'al' },
            { label: 'dz (Algeria)', value: 'dz' },
            { label: 'as (American Samoa)', value: 'as' },
            { label: 'ad (Andorra)', value: 'ad' },
            { label: 'ao (Angola)', value: 'ao' },
            { label: 'ai (Anguilla)', value: 'ai' },
            { label: 'aq (Antarctica)', value: 'aq' },
            { label: 'ag (Antigua and Barbuda)', value: 'ag' },
            { label: 'ar (Argentina)', value: 'ar' },
            { label: 'am (Armenia)', value: 'am' },
            { label: 'aw (Aruba)', value: 'aw' },
            { label: 'au (Australia)', value: 'au' },
            { label: 'at (Austria)', value: 'at' },
            { label: 'az (Azerbaijan)', value: 'az' },
            { label: 'bs (Bahamas)', value: 'bs' },
            { label: 'bh (Bahrain)', value: 'bh' },
            { label: 'bd (Bangladesh)', value: 'bd' },
            { label: 'bb (Barbados)', value: 'bb' },
            { label: 'by (Belarus)', value: 'by' },
            { label: 'be (Belgium)', value: 'be' },
            { label: 'bz (Belize)', value: 'bz' },
            { label: 'bj (Benin)', value: 'bj' },
            { label: 'bm (Bermuda)', value: 'bm' },
            { label: 'bt (Bhutan)', value: 'bt' },
            { label: 'bo (Bolivia)', value: 'bo' },
            { label: 'ba (Bosnia and Herzegovina)', value: 'ba' },
            { label: 'bw (Botswana)', value: 'bw' },
            { label: 'bv (Bouvet Island)', value: 'bv' },
            { label: 'br (Brazil)', value: 'br' },
            { label: 'io (British Indian Ocean Territory)', value: 'io' },
            { label: 'bn (Brunei Darussalam)', value: 'bn' },
            { label: 'bg (Bulgaria)', value: 'bg' },
            { label: 'bf (Burkina Faso)', value: 'bf' },
            { label: 'bi (Burundi)', value: 'bi' },
            { label: 'kh (Cambodia)', value: 'kh' },
            { label: 'cm (Cameroon)', value: 'cm' },
            { label: 'ca (Canada)', value: 'ca' },
            { label: 'cv (Cape Verde)', value: 'cv' },
            { label: 'ky (Cayman Islands)', value: 'ky' },
            { label: 'cf (Central African Republic)', value: 'cf' },
            { label: 'td (Chad)', value: 'td' },
            { label: 'cl (Chile)', value: 'cl' },
            { label: 'cn (China)', value: 'cn' },
            { label: 'cx (Christmas Island)', value: 'cx' },
            { label: 'cc (Cocos (Keeling) Islands)', value: 'cc' },
            { label: 'co (Colombia)', value: 'co' },
            { label: 'km (Comoros)', value: 'km' },
            { label: 'cg (Congo)', value: 'cg' },
            { label: 'cd (Congo, the Democratic Republic of the)', value: 'cd' },
            { label: 'ck (Cook Islands)', value: 'ck' },
            { label: 'cr (Costa Rica)', value: 'cr' },
            { label: 'ci (Cote D\'ivoire)', value: 'ci' },
            { label: 'hr (Croatia)', value: 'hr' },
            { label: 'cu (Cuba)', value: 'cu' },
            { label: 'cy (Cyprus)', value: 'cy' },
            { label: 'cz (Czech Republic)', value: 'cz' },
            { label: 'dk (Denmark)', value: 'dk' },
            { label: 'dj (Djibouti)', value: 'dj' },
            { label: 'dm (Dominica)', value: 'dm' },
            { label: 'do (Dominican Republic)', value: 'do' },
            { label: 'ec (Ecuador)', value: 'ec' },
            { label: 'eg (Egypt)', value: 'eg' },
            { label: 'sv (El Salvador)', value: 'sv' },
            { label: 'gq (Equatorial Guinea)', value: 'gq' },
            { label: 'er (Eritrea)', value: 'er' },
            { label: 'ee (Estonia)', value: 'ee' },
            { label: 'et (Ethiopia)', value: 'et' },
            { label: 'fk (Falkland Islands (Malvinas))', value: 'fk' },
            { label: 'fo (Faroe Islands)', value: 'fo' },
            { label: 'fj (Fiji)', value: 'fj' },
            { label: 'fi (Finland)', value: 'fi' },
            { label: 'fr (France)', value: 'fr' },
            { label: 'gf (French Guiana)', value: 'gf' },
            { label: 'pf (French Polynesia)', value: 'pf' },
            { label: 'tf (French Southern Territories)', value: 'tf' },
            { label: 'ga (Gabon)', value: 'ga' },
            { label: 'gm (Gambia)', value: 'gm' },
            { label: 'ge (Georgia)', value: 'ge' },
            { label: 'de (Germany)', value: 'de' },
            { label: 'gh (Ghana)', value: 'gh' },
            { label: 'gi (Gibraltar)', value: 'gi' },
            { label: 'gr (Greece)', value: 'gr' },
            { label: 'gl (Greenland)', value: 'gl' },
            { label: 'gd (Grenada)', value: 'gd' },
            { label: 'gp (Guadeloupe)', value: 'gp' },
            { label: 'gu (Guam)', value: 'gu' },
            { label: 'gt (Guatemala)', value: 'gt' },
            { label: 'gg (Guernsey)', value: 'gg' },
            { label: 'gn (Guinea)', value: 'gn' },
            { label: 'gw (Guinea-Bissau)', value: 'gw' },
            { label: 'gy (Guyana)', value: 'gy' },
            { label: 'ht (Haiti)', value: 'ht' },
            { label: 'hm (Heard Island and Mcdonald Islands)', value: 'hm' },
            { label: 'va (Holy See (Vatican City State))', value: 'va' },
            { label: 'hn (Honduras)', value: 'hn' },
            { label: 'hk (Hong Kong)', value: 'hk' },
            { label: 'hu (Hungary)', value: 'hu' },
            { label: 'is (Iceland)', value: 'is' },
            { label: 'in (India)', value: 'in' },
            { label: 'id (Indonesia)', value: 'id' },
            { label: 'ir (Iran, Islamic Republic of)', value: 'ir' },
            { label: 'iq (Iraq)', value: 'iq' },
            { label: 'ie (Ireland)', value: 'ie' },
            { label: 'im (Isle of Man)', value: 'im' },
            { label: 'il (Israel)', value: 'il' },
            { label: 'it (Italy)', value: 'it' },
            { label: 'je (Jersey)', value: 'je' },
            { label: 'jm (Jamaica)', value: 'jm' },
            { label: 'jp (Japan)', value: 'jp' },
            { label: 'jo (Jordan)', value: 'jo' },
            { label: 'kz (Kazakhstan)', value: 'kz' },
            { label: 'ke (Kenya)', value: 'ke' },
            { label: 'ki (Kiribati)', value: 'ki' },
            { label: 'kp (Korea, Democratic People\'s Republic of)', value: 'kp' },
            { label: 'kr (Korea, Republic of)', value: 'kr' },
            { label: 'kw (Kuwait)', value: 'kw' },
            { label: 'kg (Kyrgyzstan)', value: 'kg' },
            { label: 'la (Lao People\'s Democratic Republic)', value: 'la' },
            { label: 'lv (Latvia)', value: 'lv' },
            { label: 'lb (Lebanon)', value: 'lb' },
            { label: 'ls (Lesotho)', value: 'ls' },
            { label: 'lr (Liberia)', value: 'lr' },
            { label: 'ly (Libyan Arab Jamahiriya)', value: 'ly' },
            { label: 'li (Liechtenstein)', value: 'li' },
            { label: 'lt (Lithuania)', value: 'lt' },
            { label: 'lu (Luxembourg)', value: 'lu' },
            { label: 'mo (Macao)', value: 'mo' },
            { label: 'mk (Macedonia, the Former Yugosalv Republic of)', value: 'mk' },
            { label: 'mg (Madagascar)', value: 'mg' },
            { label: 'mw (Malawi)', value: 'mw' },
            { label: 'my (Malaysia)', value: 'my' },
            { label: 'mv (Maldives)', value: 'mv' },
            { label: 'ml (Mali)', value: 'ml' },
            { label: 'mt (Malta)', value: 'mt' },
            { label: 'mh (Marshall Islands)', value: 'mh' },
            { label: 'mq (Martinique)', value: 'mq' },
            { label: 'mr (Mauritania)', value: 'mr' },
            { label: 'mu (Mauritius)', value: 'mu' },
            { label: 'yt (Mayotte)', value: 'yt' },
            { label: 'mx (Mexico)', value: 'mx' },
            { label: 'fm (Micronesia, Federated States of)', value: 'fm' },
            { label: 'md (Moldova, Republic of)', value: 'md' },
            { label: 'mc (Monaco)', value: 'mc' },
            { label: 'mn (Mongolia)', value: 'mn' },
            { label: 'me (Montenegro)', value: 'me' },
            { label: 'ms (Montserrat)', value: 'ms' },
            { label: 'ma (Morocco)', value: 'ma' },
            { label: 'mz (Mozambique)', value: 'mz' },
            { label: 'mm (Myanmar)', value: 'mm' },
            { label: 'na (Namibia)', value: 'na' },
            { label: 'nr (Nauru)', value: 'nr' },
            { label: 'np (Nepal)', value: 'np' },
            { label: 'nl (Netherlands)', value: 'nl' },
            { label: 'an (Netherlands Antilles)', value: 'an' },
            { label: 'nc (New Caledonia)', value: 'nc' },
            { label: 'nz (New Zealand)', value: 'nz' },
            { label: 'ni (Nicaragua)', value: 'ni' },
            { label: 'ne (Niger)', value: 'ne' },
            { label: 'ng (Nigeria)', value: 'ng' },
            { label: 'nu (Niue)', value: 'nu' },
            { label: 'nf (Norfolk Island)', value: 'nf' },
            { label: 'mp (Northern Mariana Islands)', value: 'mp' },
            { label: 'no (Norway)', value: 'no' },
            { label: 'om (Oman)', value: 'om' },
            { label: 'pk (Pakistan)', value: 'pk' },
            { label: 'pw (Palau)', value: 'pw' },
            { label: 'ps (Palestinian Territory, Occupied)', value: 'ps' },
            { label: 'pa (Panama)', value: 'pa' },
            { label: 'pg (Papua New Guinea)', value: 'pg' },
            { label: 'py (Paraguay)', value: 'py' },
            { label: 'pe (Peru)', value: 'pe' },
            { label: 'ph (Philippines)', value: 'ph' },
            { label: 'pn (Pitcairn)', value: 'pn' },
            { label: 'pl (Poland)', value: 'pl' },
            { label: 'pt (Portugal)', value: 'pt' },
            { label: 'pr (Puerto Rico)', value: 'pr' },
            { label: 'qa (Qatar)', value: 'qa' },
            { label: 're (Reunion)', value: 're' },
            { label: 'ro (Romania)', value: 'ro' },
            { label: 'ru (Russian Federation)', value: 'ru' },
            { label: 'rw (Rwanda)', value: 'rw' },
            { label: 'sh (Saint Helena)', value: 'sh' },
            { label: 'kn (Saint Kitts and Nevis)', value: 'kn' },
            { label: 'lc (Saint Lucia)', value: 'lc' },
            { label: 'pm (Saint Pierre and Miquelon)', value: 'pm' },
            { label: 'vc (Saint Vincent and the Grenadines)', value: 'vc' },
            { label: 'ws (Samoa)', value: 'ws' },
            { label: 'sm (San Marino)', value: 'sm' },
            { label: 'st (Sao Tome and Principe)', value: 'st' },
            { label: 'sa (Saudi Arabia)', value: 'sa' },
            { label: 'sn (Senegal)', value: 'sn' },
            { label: 'rs (Serbia)', value: 'rs' },
            { label: 'sc (Seychelles)', value: 'sc' },
            { label: 'sl (Sierra Leone)', value: 'sl' },
            { label: 'sg (Singapore)', value: 'sg' },
            { label: 'sk (Slovakia)', value: 'sk' },
            { label: 'si (Slovenia)', value: 'si' },
            { label: 'sb (Solomon Islands)', value: 'sb' },
            { label: 'so (Somalia)', value: 'so' },
            { label: 'za (South Africa)', value: 'za' },
            { label: 'gs (South Georgia and the South Sandwich Islands)', value: 'gs' },
            { label: 'es (Spain)', value: 'es' },
            { label: 'lk (Sri Lanka)', value: 'lk' },
            { label: 'sd (Sudan)', value: 'sd' },
            { label: 'sr (Suriname)', value: 'sr' },
            { label: 'sj (Svalbard and Jan Mayen)', value: 'sj' },
            { label: 'sz (Swaziland)', value: 'sz' },
            { label: 'se (Sweden)', value: 'se' },
            { label: 'ch (Switzerland)', value: 'ch' },
            { label: 'sy (Syrian Arab Republic)', value: 'sy' },
            { label: 'tw (Taiwan, Province of China)', value: 'tw' },
            { label: 'tj (Tajikistan)', value: 'tj' },
            { label: 'tz (Tanzania, United Republic of)', value: 'tz' },
            { label: 'th (Thailand)', value: 'th' },
            { label: 'tl (Timor-Leste)', value: 'tl' },
            { label: 'tg (Togo)', value: 'tg' },
            { label: 'tk (Tokelau)', value: 'tk' },
            { label: 'to (Tonga)', value: 'to' },
            { label: 'tt (Trinidad and Tobago)', value: 'tt' },
            { label: 'tn (Tunisia)', value: 'tn' },
            { label: 'tr (Turkiye)', value: 'tr' },
            { label: 'tm (Turkmenistan)', value: 'tm' },
            { label: 'tc (Turks and Caicos Islands)', value: 'tc' },
            { label: 'tv (Tuvalu)', value: 'tv' },
            { label: 'ug (Uganda)', value: 'ug' },
            { label: 'ua (Ukraine)', value: 'ua' },
            { label: 'ae (United Arab Emirates)', value: 'ae' },
            { label: 'uk (United Kingdom)', value: 'uk' },
            { label: 'gb (United Kingdom)', value: 'gb' },
            { label: 'um (United States Minor Outlying Islands)', value: 'um' },
            { label: 'uy (Uruguay)', value: 'uy' },
            { label: 'uz (Uzbekistan)', value: 'uz' },
            { label: 'vu (Vanuatu)', value: 'vu' },
            { label: 've (Venezuela)', value: 've' },
            { label: 'vn (Viet Nam)', value: 'vn' },
            { label: 'vg (Virgin Islands, British)', value: 'vg' },
            { label: 'vi (Virgin Islands, U.S.)', value: 'vi' },
            { label: 'wf (Wallis and Futuna)', value: 'wf' },
            { label: 'eh (Western Sahara)', value: 'eh' },
            { label: 'ye (Yemen)', value: 'ye' },
            { label: 'zm (Zambia)', value: 'zm' },
            { label: 'zw (Zimbabwe)', value: 'zw' },
        ],
    },
});

export const languageDropdown = Property.StaticDropdown({
    displayName: 'Language',
    description: 'Language to use for the search',
    required: false,
    options: {
        options: [
            { label: 'English', value: 'en' },
            { label: 'Afrikaans', value: 'af' },
            { label: 'Akan', value: 'ak' },
            { label: 'Albanian', value: 'sq' },
            { label: 'Amharic', value: 'am' },
            { label: 'Arabic', value: 'ar' },
            { label: 'Armenian', value: 'hy' },
            { label: 'Azerbaijani', value: 'az' },
            { label: 'Basque', value: 'eu' },
            { label: 'Belarusian', value: 'be' },
            { label: 'Bemba', value: 'bem' },
            { label: 'Bengali', value: 'bn' },
            { label: 'Bihari', value: 'bh' },
            { label: 'Bosnian', value: 'bs' },
            { label: 'Breton', value: 'br' },
            { label: 'Bulgarian', value: 'bg' },
            { label: 'Bhutanese', value: 'bt' },
            { label: 'Cambodian', value: 'km' },
            { label: 'Catalan', value: 'ca' },
            { label: 'Cherokee', value: 'chr' },
            { label: 'Chichewa', value: 'ny' },
            { label: 'Chinese (Simplified)', value: 'zh-cn' },
            { label: 'Chinese (Traditional)', value: 'zh-tw' },
            { label: 'Corsican', value: 'co' },
            { label: 'Croatian', value: 'hr' },
            { label: 'Czech', value: 'cs' },
            { label: 'Danish', value: 'da' },
            { label: 'Dutch', value: 'nl' },
            { label: 'Esperanto', value: 'eo' },
            { label: 'Estonian', value: 'et' },
            { label: 'Ewe', value: 'ee' },
            { label: 'Faroese', value: 'fo' },
            { label: 'Filipino', value: 'tl' },
            { label: 'Finnish', value: 'fi' },
            { label: 'French', value: 'fr' },
            { label: 'Frisian', value: 'fy' },
            { label: 'Ga', value: 'gaa' },
            { label: 'Galician', value: 'gl' },
            { label: 'Georgian', value: 'ka' },
            { label: 'German', value: 'de' },
            { label: 'Greek', value: 'el' },
            { label: 'Greenlandic', value: 'kl' },
            { label: 'Guarani', value: 'gn' },
            { label: 'Gujarati', value: 'gu' },
            { label: 'Haitian Creole', value: 'ht' },
            { label: 'Hausa', value: 'ha' },
            { label: 'Hawaiian', value: 'haw' },
            { label: 'Hebrew', value: 'he' },
            { label: 'Hindi', value: 'hi' },
            { label: 'Hungarian', value: 'hu' },
            { label: 'Icelandic', value: 'is' },
            { label: 'Igbo', value: 'ig' },
            { label: 'Indonesian', value: 'id' },
            { label: 'Interlingua', value: 'ia' },
            { label: 'Irish', value: 'ga' },
            { label: 'Italian', value: 'it' },
            { label: 'Japanese', value: 'ja' },
            { label: 'Javanese', value: 'jw' },
            { label: 'Kannada', value: 'kn' },
            { label: 'Kazakh', value: 'kk' },
            { label: 'Kinyarwanda', value: 'rw' },
            { label: 'Kirundi', value: 'rn' },
            { label: 'Kongo', value: 'kg' },
            { label: 'Korean', value: 'ko' },
            { label: 'Krio (Sierra Leone)', value: 'kri' },
            { label: 'Kurdish', value: 'ku' },
            { label: 'Kurdish (Soranî)', value: 'ckb' },
            { label: 'Kyrgyz', value: 'ky' },
            { label: 'Laothian', value: 'lo' },
            { label: 'Latin', value: 'la' },
            { label: 'Latvian', value: 'lv' },
            { label: 'Lingala', value: 'ln' },
            { label: 'Lithuanian', value: 'lt' },
            { label: 'Lozi', value: 'loz' },
            { label: 'Luganda', value: 'lg' },
            { label: 'Luo', value: 'ach' },
            { label: 'Macedonian', value: 'mk' },
            { label: 'Malagasy', value: 'mg' },
            { label: 'Malay', value: 'ms' },
            { label: 'Malayalam', value: 'ml' },
            { label: 'Maltese', value: 'mt' },
            { label: 'Maldives', value: 'mv' },
            { label: 'Maori', value: 'mi' },
            { label: 'Marathi', value: 'mr' },
            { label: 'Mauritian Creole', value: 'mfe' },
            { label: 'Moldavian', value: 'mo' },
            { label: 'Mongolian', value: 'mn' },
            { label: 'Montenegrin', value: 'sr-me' },
            { label: 'Myanmar', value: 'my' },
            { label: 'Nepali', value: 'ne' },
            { label: 'Nigerian Pidgin', value: 'pcm' },
            { label: 'Northern Sotho', value: 'nso' },
            { label: 'Norwegian', value: 'no' },
            { label: 'Norwegian (Nynorsk)', value: 'nn' },
            { label: 'Occitan', value: 'oc' },
            { label: 'Oriya', value: 'or' },
            { label: 'Oromo', value: 'om' },
            { label: 'Pashto', value: 'ps' },
            { label: 'Persian', value: 'fa' },
            { label: 'Polish', value: 'pl' },
            { label: 'Portuguese', value: 'pt' },
            { label: 'Portuguese (Brazil)', value: 'pt-br' },
            { label: 'Portuguese (Portugal)', value: 'pt-pt' },
            { label: 'Punjabi', value: 'pa' },
            { label: 'Quechua', value: 'qu' },
            { label: 'Romanian', value: 'ro' },
            { label: 'Romansh', value: 'rm' },
            { label: 'Runyakitara', value: 'nyn' },
            { label: 'Russian', value: 'ru' },
            { label: 'Samoa', value: 'ws' },
            { label: 'Scots Gaelic', value: 'gd' },
            { label: 'Serbian', value: 'sr' },
            { label: 'Serbo-Croatian', value: 'sh' },
            { label: 'Sesotho', value: 'st' },
            { label: 'Setswana', value: 'tn' },
            { label: 'Seychellois Creole', value: 'crs' },
            { label: 'Shona', value: 'sn' },
            { label: 'Sindhi', value: 'sd' },
            { label: 'Sinhalese', value: 'si' },
            { label: 'Slovak', value: 'sk' },
            { label: 'Slovenian', value: 'sl' },
            { label: 'Somali', value: 'so' },
            { label: 'Spanish', value: 'es' },
            { label: 'Spanish (Latin American)', value: 'es-419' },
            { label: 'Sundanese', value: 'su' },
            { label: 'Swahili', value: 'sw' },
            { label: 'Swedish', value: 'sv' },
            { label: 'Tajik', value: 'tg' },
            { label: 'Tamil', value: 'ta' },
            { label: 'Tatar', value: 'tt' },
            { label: 'Telugu', value: 'te' },
            { label: 'Thai', value: 'th' },
            { label: 'Tigrinya', value: 'ti' },
            { label: 'Tonga', value: 'to' },
            { label: 'Tshiluba', value: 'lua' },
            { label: 'Tumbuka', value: 'tum' },
            { label: 'Turkish', value: 'tr' },
            { label: 'Turkmen', value: 'tk' },
            { label: 'Twi', value: 'tw' },
            { label: 'Uighur', value: 'ug' },
            { label: 'Ukrainian', value: 'uk' },
            { label: 'Urdu', value: 'ur' },
            { label: 'Uzbek', value: 'uz' },
            { label: 'Vanuatu', value: 'vu' },
            { label: 'Vietnamese', value: 'vi' },
            { label: 'Welsh', value: 'cy' },
            { label: 'Wolof', value: 'wo' },
            { label: 'Xhosa', value: 'xh' },
            { label: 'Yiddish', value: 'yi' },
            { label: 'Yoruba', value: 'yo' },
            { label: 'Zulu', value: 'zu' },
        ],
    },
});








