import { createTrigger, Property, TriggerStrategy } from '@activepieces/pieces-framework';
import { filloutFormsAuth } from '../common/auth';

const markdown = `
To set up the trigger for new form responses, follow these steps:

1. Go to your Fillout form settings
2. Navigate to the "Integrations" or "Webhooks" section  
3. Add a new webhook with this URL:
   \`\`\`text
   {{webhookUrl}}
   \`\`\`
4. Select the events you want to trigger on (typically "form submitted")
5. Save the webhook configuration

Your flow will now trigger whenever someone submits your form.
`;

export const newFormResponse = createTrigger({
  auth: filloutFormsAuth,
  name: 'new_form_response',
  displayName: 'New Form Response',
  description: 'Triggers when a Fillout form receives a new submission',
  props: {
    formId: Property.ShortText({
      displayName: 'Form ID',
      required: true,
      description: 'The ID of the form to monitor for new responses'
    }),
    instructions: Property.MarkDown({
      value: markdown,
    }),
  },
  type: TriggerStrategy.WEBHOOK,
  sampleData: {
    formId: 'your-form-id',
    submissionId: 'sub_123456789',
    submittedAt: '2024-01-15T10:30:00.000Z',
    responses: [
      {
        questionId: 'q1',
        question: 'What is your name?',
        answer: 'John Doe'
      }
    ]
  },
  async onEnable(context) {
    // Webhook URL is automatically generated by Activepieces
    // Users need to manually configure it in Fillout
  },
  async onDisable(context) {
    // No cleanup needed for manual webhook setup
  },
  async run(context) {
    // Return the form submission data
    return [context.payload.body];
  },
}); 