import { createManualWebhookTrigger } from './_manual-webhook-trigger';

export const accountUpdatedTrigger = createManualWebhookTrigger({
  name: 'account_updated',
  displayName: 'Account Updated',
  description: 'Triggers when an existing account is updated in Outseta.',
  sampleData: {
    Name: 'Acme Corp',
    InvoiceNotes: '',
    IsDemo: false,
    BillingAddress: {
      City: 'New York',
      State: 'NY',
      PostalCode: '10001',
      Country: 'United States',
      Uid: 'addr_billing_example',
      _objectType: 'Address',
    },
    AccountStage: 3,
    AccountStageLabel: 'Subscribing',
    PersonAccount: [
      {
        Person: {
          Email: 'jane.doe@example.com',
          FirstName: 'Jane',
          LastName: 'Doe',
          FullName: 'Jane Doe',
          PhoneMobile: '+1234567890',
          HasLoggedIn: true,
          Uid: 'per_example1',
          _objectType: 'Person',
          Created: '2024-01-15T10:00:00',
          Updated: '2024-02-01T10:00:00',
        },
        IsPrimary: true,
        ReceiveInvoices: false,
        Uid: 'pa_example1',
        _objectType: 'PersonAccount',
      },
    ],
    CurrentSubscription: {
      BillingRenewalTerm: 1,
      Plan: {
        Name: 'Professional',
        PlanFamily: { Name: 'Main Plans', Uid: 'pf_example1', _objectType: 'PlanFamily' },
        MonthlyRate: 49.00,
        IsActive: true,
        Uid: 'plan_example1',
        _objectType: 'Plan',
      },
      StartDate: '2024-02-01T00:00:00',
      RenewalDate: '2024-03-01T00:00:00',
      Rate: 49.00,
      Uid: 'sub_example1',
      _objectType: 'Subscription',
    },
    HasLoggedIn: true,
    LifetimeRevenue: 49.00,
    PrimaryContact: {
      Email: 'jane.doe@example.com',
      FirstName: 'Jane',
      LastName: 'Doe',
      FullName: 'Jane Doe',
      Uid: 'per_example1',
      _objectType: 'Person',
    },
    ActivityEventData: {
      Name: 'Acme Inc',
      AccountStage: 3,
      AccountStageLabel: 'Subscribing',
      Uid: 'acc_example1',
      _objectType: 'Account',
    },
    Uid: 'acc_example1',
    _objectType: 'Account',
    Created: '2024-01-15T10:00:00',
    Updated: '2024-02-01T10:00:00',
  },
});
