import { createManualWebhookTrigger } from './_manual-webhook-trigger';

export const accountPaidSubscriptionCreatedTrigger = createManualWebhookTrigger({
  name: 'account_paid_subscription_created',
  displayName: 'Account Paid Subscription Created',
  description: 'Triggers when a paid subscription is created for an account in Outseta.',
  sampleData: {
    Name: 'Acme Corp',
    IsDemo: false,
    AccountStage: 3,
    AccountStageLabel: 'Subscribing',
    PersonAccount: [
      {
        Person: {
          Email: 'jane.doe@example.com',
          FirstName: 'Jane',
          LastName: 'Doe',
          FullName: 'Jane Doe',
          Uid: 'per_example1',
          _objectType: 'Person',
        },
        IsPrimary: true,
        Uid: 'pa_example1',
        _objectType: 'PersonAccount',
      },
    ],
    CurrentSubscription: {
      BillingRenewalTerm: 1,
      Plan: {
        Name: 'Professional',
        PlanFamily: { Name: 'Main Plans', Uid: 'pf_example1', _objectType: 'PlanFamily' },
        MonthlyRate: 49.00,
        AnnualRate: 490.00,
        SetupFee: 0,
        IsActive: true,
        IsPerUser: false,
        RequirePaymentInformation: true,
        TrialPeriodDays: 0,
        PlanAddOns: [],
        ContentGroups: [],
        Uid: 'plan_example1',
        _objectType: 'Plan',
      },
      StartDate: '2024-02-01T00:00:00',
      RenewalDate: '2024-03-01T00:00:00',
      IsPlanUpgradeRequired: false,
      SubscriptionAddOns: [],
      DiscountCouponSubscriptions: [],
      Rate: 49.00,
      Uid: 'sub_example1',
      _objectType: 'Subscription',
      Created: '2024-02-01T00:00:00',
      Updated: '2024-02-01T00:00:00',
    },
    HasLoggedIn: true,
    LifetimeRevenue: 49.00,
    Uid: 'acc_example1',
    _objectType: 'Account',
    Created: '2024-01-15T10:00:00',
    Updated: '2024-02-01T00:00:00',
  },
});
