import { createManualWebhookTrigger } from './_manual-webhook-trigger';

export const accountAddedTrigger = createManualWebhookTrigger({
  name: 'account_added',
  displayName: 'Account Added',
  description: 'Triggers when a new account is added in Outseta.',
  sampleData: {
    Name: 'Acme Corp',
    InvoiceNotes: '',
    IsDemo: false,
    BillingAddress: {
      City: 'New York',
      State: 'NY',
      PostalCode: '10001',
      Country: 'United States',
      Uid: 'addr_billing_example',
      _objectType: 'Address',
      Created: '2024-01-15T10:00:00',
      Updated: '2024-01-15T10:00:00',
    },
    MailingAddress: {
      City: 'New York',
      State: 'NY',
      PostalCode: '10001',
      Country: 'United States',
      Uid: 'addr_mailing_example',
      _objectType: 'Address',
      Created: '2024-01-15T10:00:00',
      Updated: '2024-01-15T10:00:00',
    },
    AccountStage: 2,
    AccountStageLabel: 'Trialing',
    PersonAccount: [
      {
        Person: {
          Email: 'jane.doe@example.com',
          FirstName: 'Jane',
          LastName: 'Doe',
          FullName: 'Jane Doe',
          PhoneMobile: '+1234567890',
          PhoneWork: '',
          Title: '',
          Timezone: 'America/New_York',
          Language: 'en',
          HasLoggedIn: false,
          OAuthIntegrationStatus: 0,
          Uid: 'per_example1',
          _objectType: 'Person',
          Created: '2024-01-15T10:00:00',
          Updated: '2024-01-15T10:00:00',
        },
        IsPrimary: true,
        ReceiveInvoices: false,
        Uid: 'pa_example1',
        _objectType: 'PersonAccount',
        Created: '2024-01-15T10:00:00',
        Updated: '2024-01-15T10:00:00',
      },
    ],
    Subscriptions: [],
    CurrentSubscription: null,
    LatestSubscription: null,
    Deals: [],
    HasLoggedIn: false,
    LifetimeRevenue: 0,
    PrimaryContact: {
      Email: 'jane.doe@example.com',
      FirstName: 'Jane',
      LastName: 'Doe',
      FullName: 'Jane Doe',
      Uid: 'per_example1',
      _objectType: 'Person',
    },
    Uid: 'acc_example1',
    _objectType: 'Account',
    Created: '2024-01-15T10:00:00',
    Updated: '2024-01-15T10:00:00',
  },
});
