const sampleAccount = {
  id: '109302436954721982',
  username: 'alice',
  acct: 'alice@fosstodon.org',
  display_name: 'Alice Martin',
  locked: false,
  bot: false,
  discoverable: true,
  indexable: true,
  group: false,
  created_at: '2022-11-08T00:00:00.000Z',
  note: '<p>Open-source maintainer. Coffee, bikes and automation.</p>',
  url: 'https://fosstodon.org/@alice',
  uri: 'https://fosstodon.org/users/alice',
  avatar: 'https://files.mastodon.social/cache/accounts/avatars/109/302/436/954/721/982/original/avatar.png',
  avatar_static: 'https://files.mastodon.social/cache/accounts/avatars/109/302/436/954/721/982/original/avatar.png',
  header: 'https://mastodon.social/headers/original/missing.png',
  header_static: 'https://mastodon.social/headers/original/missing.png',
  followers_count: 312,
  following_count: 180,
  statuses_count: 1024,
  last_status_at: '2026-09-23',
  emojis: [],
  fields: [],
};

const sampleStatus = {
  id: '117322188854695939',
  created_at: '2026-09-23T20:15:32.088Z',
  in_reply_to_id: null,
  in_reply_to_account_id: null,
  sensitive: false,
  spoiler_text: '',
  visibility: 'public',
  language: 'en',
  uri: 'https://fosstodon.org/users/alice/statuses/113208846513722012',
  url: 'https://fosstodon.org/@alice/113208846513722012',
  replies_count: 2,
  reblogs_count: 5,
  favourites_count: 14,
  edited_at: null,
  favourited: false,
  reblogged: false,
  muted: false,
  bookmarked: false,
  content:
    '<p>Just shipped a new release of our automation toolkit <a href="https://mastodon.social/tags/opensource" class="mention hashtag" rel="tag">#<span>opensource</span></a> <span class="h-card"><a href="https://mastodon.social/@example" class="u-url mention">@<span>example</span></a></span></p>',
  filtered: [],
  reblog: null,
  account: sampleAccount,
  media_attachments: [],
  mentions: [
    {
      id: '117320753014121404',
      username: 'example',
      url: 'https://mastodon.social/@example',
      acct: 'example',
    },
  ],
  tags: [{ name: 'opensource', url: 'https://mastodon.social/tags/opensource' }],
  emojis: [],
  card: null,
  poll: null,
};

export const mastodonSampleData = {
  status: sampleStatus,
  mentionNotification: {
    id: '622629923',
    type: 'mention',
    created_at: '2026-09-23T20:15:32.409Z',
    group_key: 'ungrouped-622629923',
    account: sampleAccount,
    status: sampleStatus,
  },
  followNotification: {
    id: '622629915',
    type: 'follow',
    created_at: '2026-09-23T20:15:30.346Z',
    group_key: 'follow-497276',
    account: sampleAccount,
  },
};
