import { createAction, Property } from '@activepieces/pieces-framework';
import { zooAuth } from '../../auth'
import { httpClient, HttpMethod } from '@activepieces/pieces-common';

export const listCadModelsAction = createAction({
  name: 'list_cad_models',
  displayName: 'List CAD Models',
  description: 'Retrieve a list of your generated 3D models',
  audience: 'both',
  aiMetadata: { description: 'List the text-to-CAD 3D models generated by the authenticated user, with optional limit/offset paging. Use to browse past generations or find a model ID to feed into give-model-feedback or an iteration. Read-only with no side effects.', idempotent: true },
  auth: zooAuth,
  // category: 'Machine Learning (ML)',
  props: {
    limit: Property.Number({
      displayName: 'Limit',
      required: false,
      description: 'Maximum number of models to return',
    }),
    offset: Property.Number({
      displayName: 'Offset',
      required: false,
      description: 'Number of models to skip',
    }),
  },
  async run({ auth, propsValue }) {
    const response = await httpClient.sendRequest({
      method: HttpMethod.GET,
      url: 'https://api.zoo.dev/user/text-to-cad',
      headers: {
        Authorization: `Bearer ${auth.secret_text}`,
      },
      queryParams: {
        ...(propsValue.limit && { limit: propsValue.limit.toString() }),
        ...(propsValue.offset && { offset: propsValue.offset.toString() }),
      },
    });
    return response.body;
  },
});
