import {
  Property,
  TriggerStrategy,
  createTrigger,
} from '@activepieces/pieces-framework';
import {
  MarkdownVariant,
  USE_DRAFT_QUERY_PARAM_NAME,
  ChatFormResponse,
} from '@activepieces/pieces-framework';
import { chatSubmissionTriggerOutputSchema } from '../output-schemas';

const responseMarkdown = `Needs a **Respond on UI** step to reply to the sender.`;

const markdown = `**Published Chat URL:**
\`\`\`text
{{chatUrl}}
\`\`\`
Production link. Serves the published version of the chat.

**Draft Chat URL:**
\`\`\`text
{{chatUrl}}?${USE_DRAFT_QUERY_PARAM_NAME}=true
\`\`\`
Testing link. Serves the draft you are editing now.
Or press **Open Chat** in the builder to try it in a side panel.
`;

export const onChatSubmission = createTrigger({
  name: 'chat_submission',
  classification: 'READ',
  displayName: 'Chat UI',
  description: 'Trigger the flow by sending a message',
  aiMetadata: {
    description: 'Fires each time a person sends a message in the hosted chat interface generated by this trigger, carrying the message text, the chat session id that groups one conversation, and any attached files. Represents a single turn of a human conversation with the flow, so the session id is what ties multiple turns together. The sender waits for a reply, so the flow must call the Respond on UI action; submissions missing a chat id or message are rejected.',
  },
  props: {
    about: Property.MarkDown({
      value: markdown,
      variant: MarkdownVariant.BORDERLESS,
    }),
    responseMarkdown: Property.MarkDown({
      value: responseMarkdown,
      variant: MarkdownVariant.WARNING,
    }),
    botName: Property.ShortText({
      displayName: 'Bot Name',
      description: 'Shown in the greeting above the chat box.',
      required: true,
      defaultValue: 'AI Bot',
    }),
  },
  sampleData: undefined,
  outputSchema: chatSubmissionTriggerOutputSchema,
  type: TriggerStrategy.WEBHOOK,
  async onEnable() {
    return;
  },
  async onDisable() {
    return;
  },
  async run(ctx) {
    const item = ctx.payload.body as { chatId?: string; message?: string };
    if (!item.chatId) {
      throw new Error('Chat ID is required');
    }
    if (!item.message) {
      throw new Error('Message is required');
    }
    const files = Object.entries(item)
      .filter(([key]) => key.startsWith('file'))
      .map(([key, value]) => {
        const index = Number(key.split('[')[1].split(']')[0]);
        return [index, value] as const;
      })
      .sort(([indexA], [indexB]) => indexA - indexB)
      .map(([_, value]) => value);

    const response: ChatFormResponse = {
      sessionId: item.chatId,
      message: item.message,
      files,
    }
    return [response];
  },
});
