export enum SystemProp {
  NODE_EXECUTABLE_PATH = "NODE_EXECUTABLE_PATH",

  POSTGRES_DATABASE = "POSTGRES_DATABASE",
  POSTGRES_HOST = "POSTGRES_HOST",
  POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
  POSTGRES_PORT = "POSTGRES_PORT",
  POSTGRES_USERNAME = "POSTGRES_USERNAME",

  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",

  SERVER_URL = "SERVER_URL",
  WARNING_TEXT_BODY = "WARNING_TEXT_BODY",
  WARNING_TEXT_HEADER = "WARNING_TEXT_HEADER",
}
