export enum SystemProp {
  POSTGRES_DATABASE = "POSTGRES_DATABASE",
  POSTGRES_HOST = "POSTGRES_HOST",
  POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
  POSTGRES_PORT = "POSTGRES_PORT",
  POSTGRES_USERNAME = "POSTGRES_USERNAME",

  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT",
}
