name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Days to retain runs'
        default: '30'
      minimum_runs:
        description: 'Minimum runs to keep'
        default: '6'

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days || '30' }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs || '6' }}
