name: Dev Testing Automate Deploy

on:
  workflow_dispatch:

jobs:
  Build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./package.json').version") >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/activepieces/activepieces:dev-testing

  Dev-Testing:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pre-prod.key
          chmod 600 ~/.ssh/pre-prod.key
          cat >>~/.ssh/config <<END
          Host pre-prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/pre-prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRE_PROD_USERNAME }}
          SSH_KEY: ${{ secrets.PRE_PROD_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PRE_PROD_HOST }}
          
      - name: Deploy with Docker Compose
        run: |
          ssh pre-prod -t -t 'bash -ic "cd dev-testing-activepieces && IMAGE_TAG=dev-testing docker compose pull && IMAGE_TAG=dev-testing docker compose up -d --force-recreate dev-testing-activepieces; exit"' 
