name: Validate publishable packages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/pieces/**'

jobs:
  validate-publishable-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: bun-${{ hashFiles('bun.lock', 'package.json') }}
          restore-keys: bun-

      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: validate publishable packages
        run: npx ts-node -r tsconfig-paths/register -P packages/server/engine/tsconfig.lib.json tools/scripts/validate-publishable-packages.ts
